# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/ilya/drec-fpga-intro/problems/2026/09_ps7_axil_led/fpga.xdc

# Block Designs: /home/ilya/drec-fpga-intro/problems/2026/09_ps7_axil_led/fpga/design_1/design_1.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: /home/ilya/drec-fpga-intro/problems/2026/09_ps7_axil_led/fpga/design_1/ip/design_1_processing_system7_0_0/design_1_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_processing_system7_0_0 || ORIG_REF_NAME==design_1_processing_system7_0_0} -quiet] -quiet

# IP: /home/ilya/drec-fpga-intro/problems/2026/09_ps7_axil_led/fpga/design_1/ip/design_1_axil2reg_0_0/design_1_axil2reg_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axil2reg_0_0 || ORIG_REF_NAME==design_1_axil2reg_0_0} -quiet] -quiet

# IP: /home/ilya/drec-fpga-intro/problems/2026/09_ps7_axil_led/fpga/design_1/ip/design_1_const_ok_0/design_1_const_ok_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_const_ok_0 || ORIG_REF_NAME==design_1_const_ok_0} -quiet] -quiet

# IP: /home/ilya/drec-fpga-intro/problems/2026/09_ps7_axil_led/fpga/design_1/ip/design_1_const_zero32_0/design_1_const_zero32_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_const_zero32_0 || ORIG_REF_NAME==design_1_const_zero32_0} -quiet] -quiet

# IP: /home/ilya/drec-fpga-intro/problems/2026/09_ps7_axil_led/fpga/design_1/ip/design_1_led_slice_0/design_1_led_slice_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_led_slice_0 || ORIG_REF_NAME==design_1_led_slice_0} -quiet] -quiet

# IP: /home/ilya/drec-fpga-intro/problems/2026/09_ps7_axil_led/fpga/design_1/ip/design_1_axi_protocol_convert_0_0/design_1_axi_protocol_convert_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_protocol_convert_0_0 || ORIG_REF_NAME==design_1_axi_protocol_convert_0_0} -quiet] -quiet

# IP: /home/ilya/drec-fpga-intro/problems/2026/09_ps7_axil_led/fpga/design_1/ip/design_1_proc_sys_reset_0_0/design_1_proc_sys_reset_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_proc_sys_reset_0_0 || ORIG_REF_NAME==design_1_proc_sys_reset_0_0} -quiet] -quiet

# XDC: /home/ilya/drec-fpga-intro/problems/2026/09_ps7_axil_led/fpga/design_1/design_1_ooc.xdc
