// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design implementation internals
// See Vtop.h for the primary calling header

#include "Vtop__pch.h"

// Parameter definitions for Vtop___024root
constexpr IData/*31:0*/ Vtop___024root::sa_credit_top__DOT__WIDTH;
constexpr IData/*31:0*/ Vtop___024root::sa_credit_top__DOT__SIZE;
constexpr IData/*31:0*/ Vtop___024root::sa_credit_top__DOT__DEPTH;
constexpr IData/*31:0*/ Vtop___024root::sa_credit_top__DOT__sa_top_inst__DOT__WIDTH;
constexpr IData/*31:0*/ Vtop___024root::sa_credit_top__DOT__sa_top_inst__DOT__SIZE;
constexpr IData/*31:0*/ Vtop___024root::sa_credit_top__DOT__sa_top_inst__DOT__we_line_inst__DOT__SIZE;
constexpr IData/*31:0*/ Vtop___024root::sa_credit_top__DOT__sa_top_inst__DOT__we_line_inst__DOT__dl_inst__DOT__WIDTH;
constexpr IData/*31:0*/ Vtop___024root::sa_credit_top__DOT__sa_top_inst__DOT__we_line_inst__DOT__dl_inst__DOT__SIZE;
constexpr IData/*31:0*/ Vtop___024root::sa_credit_top__DOT__sa_top_inst__DOT__we_line_inst__DOT__dl_inst__DOT__gen_sr__BRA__1__KET____DOT__sr_inst__DOT__WIDTH;
constexpr IData/*31:0*/ Vtop___024root::sa_credit_top__DOT__sa_top_inst__DOT__we_line_inst__DOT__dl_inst__DOT__gen_sr__BRA__1__KET____DOT__sr_inst__DOT__SIZE;
constexpr IData/*31:0*/ Vtop___024root::sa_credit_top__DOT__sa_top_inst__DOT__we_line_inst__DOT__dl_inst__DOT__gen_sr__BRA__2__KET____DOT__sr_inst__DOT__WIDTH;
constexpr IData/*31:0*/ Vtop___024root::sa_credit_top__DOT__sa_top_inst__DOT__we_line_inst__DOT__dl_inst__DOT__gen_sr__BRA__2__KET____DOT__sr_inst__DOT__SIZE;
constexpr IData/*31:0*/ Vtop___024root::sa_credit_top__DOT__sa_top_inst__DOT__we_line_inst__DOT__dl_inst__DOT__gen_sr__BRA__3__KET____DOT__sr_inst__DOT__WIDTH;
constexpr IData/*31:0*/ Vtop___024root::sa_credit_top__DOT__sa_top_inst__DOT__we_line_inst__DOT__dl_inst__DOT__gen_sr__BRA__3__KET____DOT__sr_inst__DOT__SIZE;
constexpr IData/*31:0*/ Vtop___024root::sa_credit_top__DOT__sa_top_inst__DOT__dl_a_vld_inst__DOT__WIDTH;
constexpr IData/*31:0*/ Vtop___024root::sa_credit_top__DOT__sa_top_inst__DOT__dl_a_vld_inst__DOT__SIZE;
constexpr IData/*31:0*/ Vtop___024root::sa_credit_top__DOT__sa_top_inst__DOT__dl_a_vld_inst__DOT__gen_sr__BRA__1__KET____DOT__sr_inst__DOT__WIDTH;
constexpr IData/*31:0*/ Vtop___024root::sa_credit_top__DOT__sa_top_inst__DOT__dl_a_vld_inst__DOT__gen_sr__BRA__1__KET____DOT__sr_inst__DOT__SIZE;
constexpr IData/*31:0*/ Vtop___024root::sa_credit_top__DOT__sa_top_inst__DOT__dl_a_vld_inst__DOT__gen_sr__BRA__2__KET____DOT__sr_inst__DOT__WIDTH;
constexpr IData/*31:0*/ Vtop___024root::sa_credit_top__DOT__sa_top_inst__DOT__dl_a_vld_inst__DOT__gen_sr__BRA__2__KET____DOT__sr_inst__DOT__SIZE;
constexpr IData/*31:0*/ Vtop___024root::sa_credit_top__DOT__sa_top_inst__DOT__dl_a_vld_inst__DOT__gen_sr__BRA__3__KET____DOT__sr_inst__DOT__WIDTH;
constexpr IData/*31:0*/ Vtop___024root::sa_credit_top__DOT__sa_top_inst__DOT__dl_a_vld_inst__DOT__gen_sr__BRA__3__KET____DOT__sr_inst__DOT__SIZE;
constexpr IData/*31:0*/ Vtop___024root::sa_credit_top__DOT__sa_top_inst__DOT__dl_c_vld_in_inst__DOT__WIDTH;
constexpr IData/*31:0*/ Vtop___024root::sa_credit_top__DOT__sa_top_inst__DOT__dl_c_vld_in_inst__DOT__SIZE;
constexpr IData/*31:0*/ Vtop___024root::sa_credit_top__DOT__sa_top_inst__DOT__dl_c_vld_in_inst__DOT__gen_sr__BRA__1__KET____DOT__sr_inst__DOT__WIDTH;
constexpr IData/*31:0*/ Vtop___024root::sa_credit_top__DOT__sa_top_inst__DOT__dl_c_vld_in_inst__DOT__gen_sr__BRA__1__KET____DOT__sr_inst__DOT__SIZE;
constexpr IData/*31:0*/ Vtop___024root::sa_credit_top__DOT__sa_top_inst__DOT__dl_c_vld_in_inst__DOT__gen_sr__BRA__2__KET____DOT__sr_inst__DOT__WIDTH;
constexpr IData/*31:0*/ Vtop___024root::sa_credit_top__DOT__sa_top_inst__DOT__dl_c_vld_in_inst__DOT__gen_sr__BRA__2__KET____DOT__sr_inst__DOT__SIZE;
constexpr IData/*31:0*/ Vtop___024root::sa_credit_top__DOT__sa_top_inst__DOT__dl_c_vld_in_inst__DOT__gen_sr__BRA__3__KET____DOT__sr_inst__DOT__WIDTH;
constexpr IData/*31:0*/ Vtop___024root::sa_credit_top__DOT__sa_top_inst__DOT__dl_c_vld_in_inst__DOT__gen_sr__BRA__3__KET____DOT__sr_inst__DOT__SIZE;
constexpr IData/*31:0*/ Vtop___024root::sa_credit_top__DOT__sa_top_inst__DOT__dl_a_inst__DOT__WIDTH;
constexpr IData/*31:0*/ Vtop___024root::sa_credit_top__DOT__sa_top_inst__DOT__dl_a_inst__DOT__SIZE;
constexpr IData/*31:0*/ Vtop___024root::sa_credit_top__DOT__sa_top_inst__DOT__dl_a_inst__DOT__gen_sr__BRA__1__KET____DOT__sr_inst__DOT__WIDTH;
constexpr IData/*31:0*/ Vtop___024root::sa_credit_top__DOT__sa_top_inst__DOT__dl_a_inst__DOT__gen_sr__BRA__1__KET____DOT__sr_inst__DOT__SIZE;
constexpr IData/*31:0*/ Vtop___024root::sa_credit_top__DOT__sa_top_inst__DOT__dl_a_inst__DOT__gen_sr__BRA__2__KET____DOT__sr_inst__DOT__WIDTH;
constexpr IData/*31:0*/ Vtop___024root::sa_credit_top__DOT__sa_top_inst__DOT__dl_a_inst__DOT__gen_sr__BRA__2__KET____DOT__sr_inst__DOT__SIZE;
constexpr IData/*31:0*/ Vtop___024root::sa_credit_top__DOT__sa_top_inst__DOT__dl_a_inst__DOT__gen_sr__BRA__3__KET____DOT__sr_inst__DOT__WIDTH;
constexpr IData/*31:0*/ Vtop___024root::sa_credit_top__DOT__sa_top_inst__DOT__dl_a_inst__DOT__gen_sr__BRA__3__KET____DOT__sr_inst__DOT__SIZE;
constexpr IData/*31:0*/ Vtop___024root::sa_credit_top__DOT__sa_top_inst__DOT__dl_c_vld_out_inst__DOT__WIDTH;
constexpr IData/*31:0*/ Vtop___024root::sa_credit_top__DOT__sa_top_inst__DOT__dl_c_vld_out_inst__DOT__SIZE;
constexpr IData/*31:0*/ Vtop___024root::sa_credit_top__DOT__sa_top_inst__DOT__dl_c_vld_out_inst__DOT__gen_sr__BRA__0__KET____DOT__sr_inst__DOT__WIDTH;
constexpr IData/*31:0*/ Vtop___024root::sa_credit_top__DOT__sa_top_inst__DOT__dl_c_vld_out_inst__DOT__gen_sr__BRA__0__KET____DOT__sr_inst__DOT__SIZE;
constexpr IData/*31:0*/ Vtop___024root::sa_credit_top__DOT__sa_top_inst__DOT__dl_c_vld_out_inst__DOT__gen_sr__BRA__1__KET____DOT__sr_inst__DOT__WIDTH;
constexpr IData/*31:0*/ Vtop___024root::sa_credit_top__DOT__sa_top_inst__DOT__dl_c_vld_out_inst__DOT__gen_sr__BRA__1__KET____DOT__sr_inst__DOT__SIZE;
constexpr IData/*31:0*/ Vtop___024root::sa_credit_top__DOT__sa_top_inst__DOT__dl_c_vld_out_inst__DOT__gen_sr__BRA__2__KET____DOT__sr_inst__DOT__WIDTH;
constexpr IData/*31:0*/ Vtop___024root::sa_credit_top__DOT__sa_top_inst__DOT__dl_c_vld_out_inst__DOT__gen_sr__BRA__2__KET____DOT__sr_inst__DOT__SIZE;
constexpr IData/*31:0*/ Vtop___024root::sa_credit_top__DOT__sa_top_inst__DOT__dl_c_out_inst__DOT__WIDTH;
constexpr IData/*31:0*/ Vtop___024root::sa_credit_top__DOT__sa_top_inst__DOT__dl_c_out_inst__DOT__SIZE;
constexpr IData/*31:0*/ Vtop___024root::sa_credit_top__DOT__sa_top_inst__DOT__dl_c_out_inst__DOT__gen_sr__BRA__0__KET____DOT__sr_inst__DOT__WIDTH;
constexpr IData/*31:0*/ Vtop___024root::sa_credit_top__DOT__sa_top_inst__DOT__dl_c_out_inst__DOT__gen_sr__BRA__0__KET____DOT__sr_inst__DOT__SIZE;
constexpr IData/*31:0*/ Vtop___024root::sa_credit_top__DOT__sa_top_inst__DOT__dl_c_out_inst__DOT__gen_sr__BRA__1__KET____DOT__sr_inst__DOT__WIDTH;
constexpr IData/*31:0*/ Vtop___024root::sa_credit_top__DOT__sa_top_inst__DOT__dl_c_out_inst__DOT__gen_sr__BRA__1__KET____DOT__sr_inst__DOT__SIZE;
constexpr IData/*31:0*/ Vtop___024root::sa_credit_top__DOT__sa_top_inst__DOT__dl_c_out_inst__DOT__gen_sr__BRA__2__KET____DOT__sr_inst__DOT__WIDTH;
constexpr IData/*31:0*/ Vtop___024root::sa_credit_top__DOT__sa_top_inst__DOT__dl_c_out_inst__DOT__gen_sr__BRA__2__KET____DOT__sr_inst__DOT__SIZE;
constexpr IData/*31:0*/ Vtop___024root::sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__WIDTH;
constexpr IData/*31:0*/ Vtop___024root::sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__SIZE;
constexpr IData/*31:0*/ Vtop___024root::sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__gen_pe_row__BRA__0__KET____DOT__gen_pe_col__BRA__0__KET____DOT__pe_inst__DOT__WIDTH;
constexpr IData/*31:0*/ Vtop___024root::sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__gen_pe_row__BRA__0__KET____DOT__gen_pe_col__BRA__1__KET____DOT__pe_inst__DOT__WIDTH;
constexpr IData/*31:0*/ Vtop___024root::sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__gen_pe_row__BRA__0__KET____DOT__gen_pe_col__BRA__2__KET____DOT__pe_inst__DOT__WIDTH;
constexpr IData/*31:0*/ Vtop___024root::sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__gen_pe_row__BRA__0__KET____DOT__gen_pe_col__BRA__3__KET____DOT__pe_inst__DOT__WIDTH;
constexpr IData/*31:0*/ Vtop___024root::sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__gen_pe_row__BRA__1__KET____DOT__gen_pe_col__BRA__0__KET____DOT__pe_inst__DOT__WIDTH;
constexpr IData/*31:0*/ Vtop___024root::sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__gen_pe_row__BRA__1__KET____DOT__gen_pe_col__BRA__1__KET____DOT__pe_inst__DOT__WIDTH;
constexpr IData/*31:0*/ Vtop___024root::sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__gen_pe_row__BRA__1__KET____DOT__gen_pe_col__BRA__2__KET____DOT__pe_inst__DOT__WIDTH;
constexpr IData/*31:0*/ Vtop___024root::sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__gen_pe_row__BRA__1__KET____DOT__gen_pe_col__BRA__3__KET____DOT__pe_inst__DOT__WIDTH;
constexpr IData/*31:0*/ Vtop___024root::sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__gen_pe_row__BRA__2__KET____DOT__gen_pe_col__BRA__0__KET____DOT__pe_inst__DOT__WIDTH;
constexpr IData/*31:0*/ Vtop___024root::sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__gen_pe_row__BRA__2__KET____DOT__gen_pe_col__BRA__1__KET____DOT__pe_inst__DOT__WIDTH;
constexpr IData/*31:0*/ Vtop___024root::sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__gen_pe_row__BRA__2__KET____DOT__gen_pe_col__BRA__2__KET____DOT__pe_inst__DOT__WIDTH;
constexpr IData/*31:0*/ Vtop___024root::sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__gen_pe_row__BRA__2__KET____DOT__gen_pe_col__BRA__3__KET____DOT__pe_inst__DOT__WIDTH;
constexpr IData/*31:0*/ Vtop___024root::sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__gen_pe_row__BRA__3__KET____DOT__gen_pe_col__BRA__0__KET____DOT__pe_inst__DOT__WIDTH;
constexpr IData/*31:0*/ Vtop___024root::sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__gen_pe_row__BRA__3__KET____DOT__gen_pe_col__BRA__1__KET____DOT__pe_inst__DOT__WIDTH;
constexpr IData/*31:0*/ Vtop___024root::sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__gen_pe_row__BRA__3__KET____DOT__gen_pe_col__BRA__2__KET____DOT__pe_inst__DOT__WIDTH;
constexpr IData/*31:0*/ Vtop___024root::sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__gen_pe_row__BRA__3__KET____DOT__gen_pe_col__BRA__3__KET____DOT__pe_inst__DOT__WIDTH;
constexpr IData/*31:0*/ Vtop___024root::sa_credit_top__DOT__fifo_inst__DOT__DATA_WIDTH;
constexpr IData/*31:0*/ Vtop___024root::sa_credit_top__DOT__fifo_inst__DOT__DEPTH;
constexpr IData/*31:0*/ Vtop___024root::sa_credit_top__DOT__fifo_inst__DOT__ADDR_WIDTH;
constexpr IData/*31:0*/ Vtop___024root::sa_credit_top__DOT__credit_inst__DOT__DEPTH;


void Vtop___024root___ctor_var_reset(Vtop___024root* vlSelf);

Vtop___024root::Vtop___024root(Vtop__Syms* symsp, const char* v__name)
    : VerilatedModule{v__name}
    , vlSymsp{symsp}
 {
    // Reset structure values
    Vtop___024root___ctor_var_reset(this);
}

void Vtop___024root::__Vconfigure(bool first) {
    (void)first;  // Prevent unused variable warning
}

Vtop___024root::~Vtop___024root() {
}
