domain_path: /home/ilya/drec-fpga-intro/problems/2026/09_ps7_axil_led/vitis/zynq_platform/zynq_fsbl/zynq_fsbl_bsp
app_src_dir: /tools/Xilinx/2025.1/Vitis/data/embeddedsw/lib/sw_apps/zynq_fsbl
template: zynq_fsbl
lang: c
