set_property SRC_FILE_INFO {cfile:/home/ilya/drec-fpga-intro/problems/2026/08_down_led/xdc/fpga.xdc rfile:../../../../xdc/fpga.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { LOC K17 IOSTANDARD LVCMOS18 } [get_ports clk]
set_property src_info {type:XDC file:1 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { LOC M20 IOSTANDARD LVCMOS18 } [get_ports rst_n]
set_property src_info {type:XDC file:1 line:10 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { LOC T12 IOSTANDARD LVCMOS18 } [get_ports {led[3]}]
set_property src_info {type:XDC file:1 line:11 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { LOC U12 IOSTANDARD LVCMOS18 } [get_ports {led[2]}]
set_property src_info {type:XDC file:1 line:12 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { LOC V12 IOSTANDARD LVCMOS18 } [get_ports {led[1]}]
set_property src_info {type:XDC file:1 line:13 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { LOC W13 IOSTANDARD LVCMOS18 } [get_ports {led[0]}]
