// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Tracing implementation internals
#include "verilated_vcd_c.h"
#include "Vsa_axi_top_tb__Syms.h"


void Vsa_axi_top_tb___024root__trace_chg_0_sub_0(Vsa_axi_top_tb___024root* vlSelf, VerilatedVcd::Buffer* bufp);

void Vsa_axi_top_tb___024root__trace_chg_0(void* voidSelf, VerilatedVcd::Buffer* bufp) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vsa_axi_top_tb___024root__trace_chg_0\n"); );
    // Body
    Vsa_axi_top_tb___024root* const __restrict vlSelf VL_ATTR_UNUSED = static_cast<Vsa_axi_top_tb___024root*>(voidSelf);
    Vsa_axi_top_tb__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    if (VL_UNLIKELY(!vlSymsp->__Vm_activity)) return;
    Vsa_axi_top_tb___024root__trace_chg_0_sub_0((&vlSymsp->TOP), bufp);
}

void Vsa_axi_top_tb___024root__trace_chg_0_sub_0(Vsa_axi_top_tb___024root* vlSelf, VerilatedVcd::Buffer* bufp) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vsa_axi_top_tb___024root__trace_chg_0_sub_0\n"); );
    Vsa_axi_top_tb__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    auto& vlSelfRef = std::ref(*vlSelf).get();
    // Body
    uint32_t* const oldp VL_ATTR_UNUSED = bufp->oldp(vlSymsp->__Vm_baseCode + 1);
    if (VL_UNLIKELY(((vlSelfRef.__Vm_traceActivity[1U] 
                      | vlSelfRef.__Vm_traceActivity
                      [2U])))) {
        bufp->chgBit(oldp+0,(vlSelfRef.sa_axi_top_tb__DOT__rst_n));
        bufp->chgBit(oldp+1,(vlSelfRef.sa_axi_top_tb__DOT__i_start_b));
        bufp->chgBit(oldp+2,(vlSelfRef.sa_axi_top_tb__DOT__i_start_ac));
        bufp->chgIData(oldp+3,(vlSelfRef.sa_axi_top_tb__DOT__i_addr_b),32);
        bufp->chgIData(oldp+4,(vlSelfRef.sa_axi_top_tb__DOT__i_addr_a),32);
        bufp->chgIData(oldp+5,(vlSelfRef.sa_axi_top_tb__DOT__i_addr_c),32);
        bufp->chgSData(oldp+6,(vlSelfRef.sa_axi_top_tb__DOT__matrix_a
                               [0U][0U]),16);
        bufp->chgSData(oldp+7,(vlSelfRef.sa_axi_top_tb__DOT__matrix_a
                               [0U][1U]),16);
        bufp->chgSData(oldp+8,(vlSelfRef.sa_axi_top_tb__DOT__matrix_a
                               [0U][2U]),16);
        bufp->chgSData(oldp+9,(vlSelfRef.sa_axi_top_tb__DOT__matrix_a
                               [0U][3U]),16);
        bufp->chgSData(oldp+10,(vlSelfRef.sa_axi_top_tb__DOT__matrix_a
                                [1U][0U]),16);
        bufp->chgSData(oldp+11,(vlSelfRef.sa_axi_top_tb__DOT__matrix_a
                                [1U][1U]),16);
        bufp->chgSData(oldp+12,(vlSelfRef.sa_axi_top_tb__DOT__matrix_a
                                [1U][2U]),16);
        bufp->chgSData(oldp+13,(vlSelfRef.sa_axi_top_tb__DOT__matrix_a
                                [1U][3U]),16);
        bufp->chgSData(oldp+14,(vlSelfRef.sa_axi_top_tb__DOT__matrix_a
                                [2U][0U]),16);
        bufp->chgSData(oldp+15,(vlSelfRef.sa_axi_top_tb__DOT__matrix_a
                                [2U][1U]),16);
        bufp->chgSData(oldp+16,(vlSelfRef.sa_axi_top_tb__DOT__matrix_a
                                [2U][2U]),16);
        bufp->chgSData(oldp+17,(vlSelfRef.sa_axi_top_tb__DOT__matrix_a
                                [2U][3U]),16);
        bufp->chgSData(oldp+18,(vlSelfRef.sa_axi_top_tb__DOT__matrix_a
                                [3U][0U]),16);
        bufp->chgSData(oldp+19,(vlSelfRef.sa_axi_top_tb__DOT__matrix_a
                                [3U][1U]),16);
        bufp->chgSData(oldp+20,(vlSelfRef.sa_axi_top_tb__DOT__matrix_a
                                [3U][2U]),16);
        bufp->chgSData(oldp+21,(vlSelfRef.sa_axi_top_tb__DOT__matrix_a
                                [3U][3U]),16);
        bufp->chgSData(oldp+22,(vlSelfRef.sa_axi_top_tb__DOT__matrix_b
                                [0U][0U]),16);
        bufp->chgSData(oldp+23,(vlSelfRef.sa_axi_top_tb__DOT__matrix_b
                                [0U][1U]),16);
        bufp->chgSData(oldp+24,(vlSelfRef.sa_axi_top_tb__DOT__matrix_b
                                [0U][2U]),16);
        bufp->chgSData(oldp+25,(vlSelfRef.sa_axi_top_tb__DOT__matrix_b
                                [0U][3U]),16);
        bufp->chgSData(oldp+26,(vlSelfRef.sa_axi_top_tb__DOT__matrix_b
                                [1U][0U]),16);
        bufp->chgSData(oldp+27,(vlSelfRef.sa_axi_top_tb__DOT__matrix_b
                                [1U][1U]),16);
        bufp->chgSData(oldp+28,(vlSelfRef.sa_axi_top_tb__DOT__matrix_b
                                [1U][2U]),16);
        bufp->chgSData(oldp+29,(vlSelfRef.sa_axi_top_tb__DOT__matrix_b
                                [1U][3U]),16);
        bufp->chgSData(oldp+30,(vlSelfRef.sa_axi_top_tb__DOT__matrix_b
                                [2U][0U]),16);
        bufp->chgSData(oldp+31,(vlSelfRef.sa_axi_top_tb__DOT__matrix_b
                                [2U][1U]),16);
        bufp->chgSData(oldp+32,(vlSelfRef.sa_axi_top_tb__DOT__matrix_b
                                [2U][2U]),16);
        bufp->chgSData(oldp+33,(vlSelfRef.sa_axi_top_tb__DOT__matrix_b
                                [2U][3U]),16);
        bufp->chgSData(oldp+34,(vlSelfRef.sa_axi_top_tb__DOT__matrix_b
                                [3U][0U]),16);
        bufp->chgSData(oldp+35,(vlSelfRef.sa_axi_top_tb__DOT__matrix_b
                                [3U][1U]),16);
        bufp->chgSData(oldp+36,(vlSelfRef.sa_axi_top_tb__DOT__matrix_b
                                [3U][2U]),16);
        bufp->chgSData(oldp+37,(vlSelfRef.sa_axi_top_tb__DOT__matrix_b
                                [3U][3U]),16);
        bufp->chgSData(oldp+38,(vlSelfRef.sa_axi_top_tb__DOT__matrix_c_ref
                                [0U][0U]),16);
        bufp->chgSData(oldp+39,(vlSelfRef.sa_axi_top_tb__DOT__matrix_c_ref
                                [0U][1U]),16);
        bufp->chgSData(oldp+40,(vlSelfRef.sa_axi_top_tb__DOT__matrix_c_ref
                                [0U][2U]),16);
        bufp->chgSData(oldp+41,(vlSelfRef.sa_axi_top_tb__DOT__matrix_c_ref
                                [0U][3U]),16);
        bufp->chgSData(oldp+42,(vlSelfRef.sa_axi_top_tb__DOT__matrix_c_ref
                                [1U][0U]),16);
        bufp->chgSData(oldp+43,(vlSelfRef.sa_axi_top_tb__DOT__matrix_c_ref
                                [1U][1U]),16);
        bufp->chgSData(oldp+44,(vlSelfRef.sa_axi_top_tb__DOT__matrix_c_ref
                                [1U][2U]),16);
        bufp->chgSData(oldp+45,(vlSelfRef.sa_axi_top_tb__DOT__matrix_c_ref
                                [1U][3U]),16);
        bufp->chgSData(oldp+46,(vlSelfRef.sa_axi_top_tb__DOT__matrix_c_ref
                                [2U][0U]),16);
        bufp->chgSData(oldp+47,(vlSelfRef.sa_axi_top_tb__DOT__matrix_c_ref
                                [2U][1U]),16);
        bufp->chgSData(oldp+48,(vlSelfRef.sa_axi_top_tb__DOT__matrix_c_ref
                                [2U][2U]),16);
        bufp->chgSData(oldp+49,(vlSelfRef.sa_axi_top_tb__DOT__matrix_c_ref
                                [2U][3U]),16);
        bufp->chgSData(oldp+50,(vlSelfRef.sa_axi_top_tb__DOT__matrix_c_ref
                                [3U][0U]),16);
        bufp->chgSData(oldp+51,(vlSelfRef.sa_axi_top_tb__DOT__matrix_c_ref
                                [3U][1U]),16);
        bufp->chgSData(oldp+52,(vlSelfRef.sa_axi_top_tb__DOT__matrix_c_ref
                                [3U][2U]),16);
        bufp->chgSData(oldp+53,(vlSelfRef.sa_axi_top_tb__DOT__matrix_c_ref
                                [3U][3U]),16);
        bufp->chgIData(oldp+54,(vlSelfRef.sa_axi_top_tb__DOT__errors),32);
        bufp->chgIData(oldp+55,(vlSelfRef.sa_axi_top_tb__DOT__unnamedblk13__DOT__i),32);
        bufp->chgIData(oldp+56,(vlSelfRef.sa_axi_top_tb__DOT__unnamedblk13__DOT__unnamedblk14__DOT__j),32);
        bufp->chgSData(oldp+57,(vlSelfRef.sa_axi_top_tb__DOT__unnamedblk13__DOT__unnamedblk14__DOT__unnamedblk15__DOT__expected),16);
        bufp->chgSData(oldp+58,(vlSelfRef.sa_axi_top_tb__DOT__unnamedblk13__DOT__unnamedblk14__DOT__unnamedblk15__DOT__actual),16);
    }
    if (VL_UNLIKELY(((vlSelfRef.__Vm_traceActivity[1U] 
                      | vlSelfRef.__Vm_traceActivity
                      [3U])))) {
        bufp->chgSData(oldp+59,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT__c_sig
                                [0U][0U]),16);
        bufp->chgSData(oldp+60,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT__c_sig
                                [0U][1U]),16);
        bufp->chgSData(oldp+61,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT__c_sig
                                [0U][2U]),16);
        bufp->chgSData(oldp+62,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT__c_sig
                                [0U][3U]),16);
        bufp->chgSData(oldp+63,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT__c_sig
                                [0U][4U]),16);
        bufp->chgSData(oldp+64,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT__c_sig
                                [1U][0U]),16);
        bufp->chgSData(oldp+65,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT__c_sig
                                [1U][1U]),16);
        bufp->chgSData(oldp+66,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT__c_sig
                                [1U][2U]),16);
        bufp->chgSData(oldp+67,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT__c_sig
                                [1U][3U]),16);
        bufp->chgSData(oldp+68,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT__c_sig
                                [1U][4U]),16);
        bufp->chgSData(oldp+69,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT__c_sig
                                [2U][0U]),16);
        bufp->chgSData(oldp+70,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT__c_sig
                                [2U][1U]),16);
        bufp->chgSData(oldp+71,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT__c_sig
                                [2U][2U]),16);
        bufp->chgSData(oldp+72,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT__c_sig
                                [2U][3U]),16);
        bufp->chgSData(oldp+73,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT__c_sig
                                [2U][4U]),16);
        bufp->chgSData(oldp+74,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT__c_sig
                                [3U][0U]),16);
        bufp->chgSData(oldp+75,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT__c_sig
                                [3U][1U]),16);
        bufp->chgSData(oldp+76,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT__c_sig
                                [3U][2U]),16);
        bufp->chgSData(oldp+77,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT__c_sig
                                [3U][3U]),16);
        bufp->chgSData(oldp+78,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT__c_sig
                                [3U][4U]),16);
        bufp->chgSData(oldp+79,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT__c_sig
                                [4U][0U]),16);
        bufp->chgSData(oldp+80,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT__c_sig
                                [4U][1U]),16);
        bufp->chgSData(oldp+81,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT__c_sig
                                [4U][2U]),16);
        bufp->chgSData(oldp+82,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT__c_sig
                                [4U][3U]),16);
        bufp->chgSData(oldp+83,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT__c_sig
                                [4U][4U]),16);
        bufp->chgSData(oldp+84,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT__c_sig
                                [0U][0U]),16);
        bufp->chgSData(oldp+85,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT__c_sig
                                [0U][1U]),16);
        bufp->chgSData(oldp+86,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT__c_sig
                                [0U][2U]),16);
        bufp->chgSData(oldp+87,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT__c_sig
                                [0U][3U]),16);
        bufp->chgSData(oldp+88,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT__c_sig
                                [1U][0U]),16);
        bufp->chgSData(oldp+89,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT__c_sig
                                [1U][1U]),16);
        bufp->chgSData(oldp+90,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT__c_sig
                                [1U][2U]),16);
        bufp->chgSData(oldp+91,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT__c_sig
                                [1U][3U]),16);
        bufp->chgSData(oldp+92,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT__c_sig
                                [2U][0U]),16);
        bufp->chgSData(oldp+93,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT__c_sig
                                [2U][1U]),16);
        bufp->chgSData(oldp+94,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT__c_sig
                                [2U][2U]),16);
        bufp->chgSData(oldp+95,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT__c_sig
                                [2U][3U]),16);
        bufp->chgSData(oldp+96,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT__c_sig
                                [3U][0U]),16);
        bufp->chgSData(oldp+97,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT__c_sig
                                [3U][1U]),16);
        bufp->chgSData(oldp+98,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT__c_sig
                                [3U][2U]),16);
        bufp->chgSData(oldp+99,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT__c_sig
                                [3U][3U]),16);
        bufp->chgCData(oldp+100,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__we_line_inst__DOT__we_shift_reg),4);
    }
    if (VL_UNLIKELY((vlSelfRef.__Vm_traceActivity[3U]))) {
        bufp->chgBit(oldp+101,((0U != (IData)(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__addr_gen_inst__DOT__state))));
        bufp->chgBit(oldp+102,(vlSelfRef.sa_axi_top_tb__DOT__m_axi_arvalid));
        bufp->chgBit(oldp+103,(vlSelfRef.sa_axi_top_tb__DOT__m_axi_arready));
        bufp->chgIData(oldp+104,(vlSelfRef.sa_axi_top_tb__DOT__m_axi_araddr),32);
        bufp->chgBit(oldp+105,(vlSelfRef.sa_axi_top_tb__DOT__m_axi_rvalid));
        bufp->chgBit(oldp+106,(vlSelfRef.sa_axi_top_tb__DOT__m_axi_rready));
        bufp->chgIData(oldp+107,(vlSelfRef.sa_axi_top_tb__DOT__m_axi_rdata),32);
        bufp->chgBit(oldp+108,(vlSelfRef.sa_axi_top_tb__DOT__m_axi_rlast));
        bufp->chgBit(oldp+109,(vlSelfRef.sa_axi_top_tb__DOT__m_axi_awvalid));
        bufp->chgBit(oldp+110,(vlSelfRef.sa_axi_top_tb__DOT__m_axi_awready));
        bufp->chgIData(oldp+111,(vlSelfRef.sa_axi_top_tb__DOT__m_axi_awaddr),32);
        bufp->chgBit(oldp+112,(vlSelfRef.sa_axi_top_tb__DOT__m_axi_wvalid));
        bufp->chgBit(oldp+113,(vlSelfRef.sa_axi_top_tb__DOT__m_axi_wready));
        bufp->chgIData(oldp+114,(((IData)(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT____VdfgRegularize_hed751b34_0_0)
                                   ? (0x0000ffffU & (IData)(
                                                            (vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__write_buffer 
                                                             >> 
                                                             (0x0000003fU 
                                                              & VL_SHIFTL_III(6,6,32, 
                                                                              ((IData)(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__write_elem_cnt) 
                                                                               - (IData)(1U)), 4U)))))
                                   : 0U)),32);
        bufp->chgBit(oldp+115,((4U == (IData)(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__write_elem_cnt))));
        bufp->chgBit(oldp+116,(vlSelfRef.sa_axi_top_tb__DOT__m_axi_bvalid));
        bufp->chgCData(oldp+117,(vlSelfRef.sa_axi_top_tb__DOT__m_axi_bresp),2);
        bufp->chgIData(oldp+118,(vlSelfRef.sa_axi_top_tb__DOT__read_addr),32);
        bufp->chgCData(oldp+119,(vlSelfRef.sa_axi_top_tb__DOT__read_len),8);
        bufp->chgCData(oldp+120,(vlSelfRef.sa_axi_top_tb__DOT__read_cnt),8);
        bufp->chgBit(oldp+121,(vlSelfRef.sa_axi_top_tb__DOT__read_active));
        bufp->chgIData(oldp+122,(vlSelfRef.sa_axi_top_tb__DOT__write_addr),32);
        bufp->chgCData(oldp+123,(vlSelfRef.sa_axi_top_tb__DOT__write_len),8);
        bufp->chgCData(oldp+124,(vlSelfRef.sa_axi_top_tb__DOT__write_cnt),8);
        bufp->chgBit(oldp+125,(vlSelfRef.sa_axi_top_tb__DOT__write_active));
        bufp->chgBit(oldp+126,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__load_b));
        bufp->chgBit(oldp+127,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__load_a));
        bufp->chgBit(oldp+128,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__store_c));
        bufp->chgQData(oldp+129,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__b_line_data),64);
        bufp->chgQData(oldp+131,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__a_line_data),64);
        bufp->chgQData(oldp+133,((((QData)((IData)(
                                                   (((IData)(
                                                             (vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__c_line_out 
                                                              >> 0x00000030U)) 
                                                     << 0x00000010U) 
                                                    | vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__dl_c_out_inst__DOT__gen_shift_reg__BRA__2__KET____DOT__sr_inst__DOT__shift_reg
                                                    [0U]))) 
                                   << 0x00000020U) 
                                  | (QData)((IData)(
                                                    ((vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__dl_c_out_inst__DOT__gen_shift_reg__BRA__1__KET____DOT__sr_inst__DOT__shift_reg
                                                      [1U] 
                                                      << 0x00000010U) 
                                                     | vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__dl_c_out_inst__DOT__gen_shift_reg__BRA__0__KET____DOT__sr_inst__DOT__shift_reg
                                                     [2U]))))),64);
        bufp->chgBit(oldp+135,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__b_we_valid));
        bufp->chgBit(oldp+136,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__a_valid));
        bufp->chgBit(oldp+137,((((IData)(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__c_vld_line_out) 
                                 >> 3U) & (vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__dl_c_vld_out_inst__DOT__gen_shift_reg__BRA__2__KET____DOT__sr_inst__DOT__shift_reg
                                           [0U] & (
                                                   vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__dl_c_vld_out_inst__DOT__gen_shift_reg__BRA__1__KET____DOT__sr_inst__DOT__shift_reg
                                                   [1U] 
                                                   & vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__dl_c_vld_out_inst__DOT__gen_shift_reg__BRA__0__KET____DOT__sr_inst__DOT__shift_reg
                                                   [2U])))));
        bufp->chgQData(oldp+138,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__read_buffer),64);
        bufp->chgCData(oldp+140,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__read_elem_cnt),8);
        bufp->chgBit(oldp+141,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__reading_b));
        bufp->chgBit(oldp+142,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__reading_a));
        bufp->chgQData(oldp+143,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__write_buffer),64);
        bufp->chgCData(oldp+145,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__write_elem_cnt),8);
        bufp->chgBit(oldp+146,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__writing_c));
        bufp->chgCData(oldp+147,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__b_burst_cnt),8);
        bufp->chgCData(oldp+148,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__a_burst_cnt),8);
        bufp->chgCData(oldp+149,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__c_burst_cnt),8);
        bufp->chgBit(oldp+150,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__burst_done_b));
        bufp->chgBit(oldp+151,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__burst_done_a));
        bufp->chgBit(oldp+152,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__burst_done_c));
        bufp->chgCData(oldp+153,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__addr_gen_inst__DOT__state),3);
        bufp->chgCData(oldp+154,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__addr_gen_inst__DOT__row_cnt_b),8);
        bufp->chgCData(oldp+155,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__addr_gen_inst__DOT__row_cnt_a),8);
        bufp->chgCData(oldp+156,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__addr_gen_inst__DOT__row_cnt_c),8);
        bufp->chgIData(oldp+157,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__addr_gen_inst__DOT__current_addr_b),32);
        bufp->chgIData(oldp+158,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__addr_gen_inst__DOT__current_addr_a),32);
        bufp->chgIData(oldp+159,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__addr_gen_inst__DOT__current_addr_c),32);
        bufp->chgBit(oldp+160,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__addr_gen_inst__DOT__start_b_reg));
        bufp->chgBit(oldp+161,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__addr_gen_inst__DOT__start_ac_reg));
        bufp->chgCData(oldp+162,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__we_line_inst__DOT__dl_inst__DOT__o_data),4);
        bufp->chgCData(oldp+163,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__dl_a_vld_inst__DOT__o_data),4);
        bufp->chgCData(oldp+164,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__dl_c_vld_in_inst__DOT__o_data),4);
        bufp->chgQData(oldp+165,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__dl_a_inst__DOT__o_data),64);
        bufp->chgCData(oldp+167,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__c_vld_line_out),4);
        bufp->chgCData(oldp+168,(((((2U & ((IData)(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__c_vld_line_out) 
                                           >> 2U)) 
                                    | vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__dl_c_vld_out_inst__DOT__gen_shift_reg__BRA__2__KET____DOT__sr_inst__DOT__shift_reg
                                    [0U]) << 2U) | 
                                  ((vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__dl_c_vld_out_inst__DOT__gen_shift_reg__BRA__1__KET____DOT__sr_inst__DOT__shift_reg
                                    [1U] << 1U) | vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__dl_c_vld_out_inst__DOT__gen_shift_reg__BRA__0__KET____DOT__sr_inst__DOT__shift_reg
                                   [2U]))),4);
        bufp->chgQData(oldp+169,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__c_line_out),64);
        bufp->chgSData(oldp+171,((0x0000ffffU & (IData)(
                                                        (vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__a_line_data 
                                                         >> 0x00000010U)))),16);
        bufp->chgSData(oldp+172,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__dl_a_inst__DOT__gen_shift_reg__BRA__1__KET____DOT__sr_inst__DOT__shift_reg
                                 [0U]),16);
        bufp->chgSData(oldp+173,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__dl_a_inst__DOT__gen_shift_reg__BRA__1__KET____DOT__sr_inst__DOT__shift_reg[0]),16);
        bufp->chgIData(oldp+174,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__dl_a_inst__DOT__gen_shift_reg__BRA__1__KET____DOT__sr_inst__DOT__unnamedblk1__DOT__i),32);
        bufp->chgIData(oldp+175,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__dl_a_inst__DOT__gen_shift_reg__BRA__1__KET____DOT__sr_inst__DOT__unnamedblk2__DOT__i),32);
        bufp->chgSData(oldp+176,((0x0000ffffU & (IData)(
                                                        (vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__a_line_data 
                                                         >> 0x00000020U)))),16);
        bufp->chgSData(oldp+177,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__dl_a_inst__DOT__gen_shift_reg__BRA__2__KET____DOT__sr_inst__DOT__shift_reg
                                 [1U]),16);
        bufp->chgSData(oldp+178,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__dl_a_inst__DOT__gen_shift_reg__BRA__2__KET____DOT__sr_inst__DOT__shift_reg[0]),16);
        bufp->chgSData(oldp+179,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__dl_a_inst__DOT__gen_shift_reg__BRA__2__KET____DOT__sr_inst__DOT__shift_reg[1]),16);
        bufp->chgIData(oldp+180,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__dl_a_inst__DOT__gen_shift_reg__BRA__2__KET____DOT__sr_inst__DOT__unnamedblk1__DOT__i),32);
        bufp->chgIData(oldp+181,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__dl_a_inst__DOT__gen_shift_reg__BRA__2__KET____DOT__sr_inst__DOT__unnamedblk2__DOT__i),32);
        bufp->chgSData(oldp+182,((0x0000ffffU & (IData)(
                                                        (vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__a_line_data 
                                                         >> 0x00000030U)))),16);
        bufp->chgSData(oldp+183,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__dl_a_inst__DOT__gen_shift_reg__BRA__3__KET____DOT__sr_inst__DOT__shift_reg
                                 [2U]),16);
        bufp->chgSData(oldp+184,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__dl_a_inst__DOT__gen_shift_reg__BRA__3__KET____DOT__sr_inst__DOT__shift_reg[0]),16);
        bufp->chgSData(oldp+185,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__dl_a_inst__DOT__gen_shift_reg__BRA__3__KET____DOT__sr_inst__DOT__shift_reg[1]),16);
        bufp->chgSData(oldp+186,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__dl_a_inst__DOT__gen_shift_reg__BRA__3__KET____DOT__sr_inst__DOT__shift_reg[2]),16);
        bufp->chgIData(oldp+187,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__dl_a_inst__DOT__gen_shift_reg__BRA__3__KET____DOT__sr_inst__DOT__unnamedblk1__DOT__i),32);
        bufp->chgIData(oldp+188,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__dl_a_inst__DOT__gen_shift_reg__BRA__3__KET____DOT__sr_inst__DOT__unnamedblk2__DOT__i),32);
        bufp->chgCData(oldp+189,((0x0000000fU & (- (IData)((IData)(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__a_valid))))),4);
        bufp->chgBit(oldp+190,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__dl_a_vld_inst__DOT__gen_shift_reg__BRA__1__KET____DOT__sr_inst__DOT__shift_reg
                               [0U]));
        bufp->chgBit(oldp+191,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__dl_a_vld_inst__DOT__gen_shift_reg__BRA__1__KET____DOT__sr_inst__DOT__shift_reg[0]));
        bufp->chgIData(oldp+192,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__dl_a_vld_inst__DOT__gen_shift_reg__BRA__1__KET____DOT__sr_inst__DOT__unnamedblk1__DOT__i),32);
        bufp->chgIData(oldp+193,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__dl_a_vld_inst__DOT__gen_shift_reg__BRA__1__KET____DOT__sr_inst__DOT__unnamedblk2__DOT__i),32);
        bufp->chgBit(oldp+194,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__dl_a_vld_inst__DOT__gen_shift_reg__BRA__2__KET____DOT__sr_inst__DOT__shift_reg
                               [1U]));
        bufp->chgBit(oldp+195,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__dl_a_vld_inst__DOT__gen_shift_reg__BRA__2__KET____DOT__sr_inst__DOT__shift_reg[0]));
        bufp->chgBit(oldp+196,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__dl_a_vld_inst__DOT__gen_shift_reg__BRA__2__KET____DOT__sr_inst__DOT__shift_reg[1]));
        bufp->chgIData(oldp+197,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__dl_a_vld_inst__DOT__gen_shift_reg__BRA__2__KET____DOT__sr_inst__DOT__unnamedblk1__DOT__i),32);
        bufp->chgIData(oldp+198,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__dl_a_vld_inst__DOT__gen_shift_reg__BRA__2__KET____DOT__sr_inst__DOT__unnamedblk2__DOT__i),32);
        bufp->chgBit(oldp+199,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__dl_a_vld_inst__DOT__gen_shift_reg__BRA__3__KET____DOT__sr_inst__DOT__shift_reg
                               [2U]));
        bufp->chgBit(oldp+200,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__dl_a_vld_inst__DOT__gen_shift_reg__BRA__3__KET____DOT__sr_inst__DOT__shift_reg[0]));
        bufp->chgBit(oldp+201,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__dl_a_vld_inst__DOT__gen_shift_reg__BRA__3__KET____DOT__sr_inst__DOT__shift_reg[1]));
        bufp->chgBit(oldp+202,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__dl_a_vld_inst__DOT__gen_shift_reg__BRA__3__KET____DOT__sr_inst__DOT__shift_reg[2]));
        bufp->chgIData(oldp+203,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__dl_a_vld_inst__DOT__gen_shift_reg__BRA__3__KET____DOT__sr_inst__DOT__unnamedblk1__DOT__i),32);
        bufp->chgIData(oldp+204,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__dl_a_vld_inst__DOT__gen_shift_reg__BRA__3__KET____DOT__sr_inst__DOT__unnamedblk2__DOT__i),32);
        bufp->chgSData(oldp+205,((0x0000ffffU & (IData)(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__c_line_out))),16);
        bufp->chgSData(oldp+206,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__dl_c_out_inst__DOT__gen_shift_reg__BRA__0__KET____DOT__sr_inst__DOT__shift_reg
                                 [2U]),16);
        bufp->chgSData(oldp+207,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__dl_c_out_inst__DOT__gen_shift_reg__BRA__0__KET____DOT__sr_inst__DOT__shift_reg[0]),16);
        bufp->chgSData(oldp+208,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__dl_c_out_inst__DOT__gen_shift_reg__BRA__0__KET____DOT__sr_inst__DOT__shift_reg[1]),16);
        bufp->chgSData(oldp+209,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__dl_c_out_inst__DOT__gen_shift_reg__BRA__0__KET____DOT__sr_inst__DOT__shift_reg[2]),16);
        bufp->chgIData(oldp+210,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__dl_c_out_inst__DOT__gen_shift_reg__BRA__0__KET____DOT__sr_inst__DOT__unnamedblk1__DOT__i),32);
        bufp->chgIData(oldp+211,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__dl_c_out_inst__DOT__gen_shift_reg__BRA__0__KET____DOT__sr_inst__DOT__unnamedblk2__DOT__i),32);
        bufp->chgSData(oldp+212,((0x0000ffffU & (IData)(
                                                        (vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__c_line_out 
                                                         >> 0x00000010U)))),16);
        bufp->chgSData(oldp+213,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__dl_c_out_inst__DOT__gen_shift_reg__BRA__1__KET____DOT__sr_inst__DOT__shift_reg
                                 [1U]),16);
        bufp->chgSData(oldp+214,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__dl_c_out_inst__DOT__gen_shift_reg__BRA__1__KET____DOT__sr_inst__DOT__shift_reg[0]),16);
        bufp->chgSData(oldp+215,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__dl_c_out_inst__DOT__gen_shift_reg__BRA__1__KET____DOT__sr_inst__DOT__shift_reg[1]),16);
        bufp->chgIData(oldp+216,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__dl_c_out_inst__DOT__gen_shift_reg__BRA__1__KET____DOT__sr_inst__DOT__unnamedblk1__DOT__i),32);
        bufp->chgIData(oldp+217,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__dl_c_out_inst__DOT__gen_shift_reg__BRA__1__KET____DOT__sr_inst__DOT__unnamedblk2__DOT__i),32);
        bufp->chgSData(oldp+218,((0x0000ffffU & (IData)(
                                                        (vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__c_line_out 
                                                         >> 0x00000020U)))),16);
        bufp->chgSData(oldp+219,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__dl_c_out_inst__DOT__gen_shift_reg__BRA__2__KET____DOT__sr_inst__DOT__shift_reg
                                 [0U]),16);
        bufp->chgSData(oldp+220,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__dl_c_out_inst__DOT__gen_shift_reg__BRA__2__KET____DOT__sr_inst__DOT__shift_reg[0]),16);
        bufp->chgIData(oldp+221,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__dl_c_out_inst__DOT__gen_shift_reg__BRA__2__KET____DOT__sr_inst__DOT__unnamedblk1__DOT__i),32);
        bufp->chgIData(oldp+222,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__dl_c_out_inst__DOT__gen_shift_reg__BRA__2__KET____DOT__sr_inst__DOT__unnamedblk2__DOT__i),32);
        bufp->chgBit(oldp+223,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__dl_c_vld_in_inst__DOT__gen_shift_reg__BRA__1__KET____DOT__sr_inst__DOT__shift_reg
                               [0U]));
        bufp->chgBit(oldp+224,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__dl_c_vld_in_inst__DOT__gen_shift_reg__BRA__1__KET____DOT__sr_inst__DOT__shift_reg[0]));
        bufp->chgIData(oldp+225,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__dl_c_vld_in_inst__DOT__gen_shift_reg__BRA__1__KET____DOT__sr_inst__DOT__unnamedblk1__DOT__i),32);
        bufp->chgIData(oldp+226,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__dl_c_vld_in_inst__DOT__gen_shift_reg__BRA__1__KET____DOT__sr_inst__DOT__unnamedblk2__DOT__i),32);
        bufp->chgBit(oldp+227,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__dl_c_vld_in_inst__DOT__gen_shift_reg__BRA__2__KET____DOT__sr_inst__DOT__shift_reg
                               [1U]));
        bufp->chgBit(oldp+228,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__dl_c_vld_in_inst__DOT__gen_shift_reg__BRA__2__KET____DOT__sr_inst__DOT__shift_reg[0]));
        bufp->chgBit(oldp+229,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__dl_c_vld_in_inst__DOT__gen_shift_reg__BRA__2__KET____DOT__sr_inst__DOT__shift_reg[1]));
        bufp->chgIData(oldp+230,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__dl_c_vld_in_inst__DOT__gen_shift_reg__BRA__2__KET____DOT__sr_inst__DOT__unnamedblk1__DOT__i),32);
        bufp->chgIData(oldp+231,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__dl_c_vld_in_inst__DOT__gen_shift_reg__BRA__2__KET____DOT__sr_inst__DOT__unnamedblk2__DOT__i),32);
        bufp->chgBit(oldp+232,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__dl_c_vld_in_inst__DOT__gen_shift_reg__BRA__3__KET____DOT__sr_inst__DOT__shift_reg
                               [2U]));
        bufp->chgBit(oldp+233,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__dl_c_vld_in_inst__DOT__gen_shift_reg__BRA__3__KET____DOT__sr_inst__DOT__shift_reg[0]));
        bufp->chgBit(oldp+234,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__dl_c_vld_in_inst__DOT__gen_shift_reg__BRA__3__KET____DOT__sr_inst__DOT__shift_reg[1]));
        bufp->chgBit(oldp+235,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__dl_c_vld_in_inst__DOT__gen_shift_reg__BRA__3__KET____DOT__sr_inst__DOT__shift_reg[2]));
        bufp->chgIData(oldp+236,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__dl_c_vld_in_inst__DOT__gen_shift_reg__BRA__3__KET____DOT__sr_inst__DOT__unnamedblk1__DOT__i),32);
        bufp->chgIData(oldp+237,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__dl_c_vld_in_inst__DOT__gen_shift_reg__BRA__3__KET____DOT__sr_inst__DOT__unnamedblk2__DOT__i),32);
        bufp->chgBit(oldp+238,((1U & (IData)(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__c_vld_line_out))));
        bufp->chgBit(oldp+239,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__dl_c_vld_out_inst__DOT__gen_shift_reg__BRA__0__KET____DOT__sr_inst__DOT__shift_reg
                               [2U]));
        bufp->chgBit(oldp+240,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__dl_c_vld_out_inst__DOT__gen_shift_reg__BRA__0__KET____DOT__sr_inst__DOT__shift_reg[0]));
        bufp->chgBit(oldp+241,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__dl_c_vld_out_inst__DOT__gen_shift_reg__BRA__0__KET____DOT__sr_inst__DOT__shift_reg[1]));
        bufp->chgBit(oldp+242,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__dl_c_vld_out_inst__DOT__gen_shift_reg__BRA__0__KET____DOT__sr_inst__DOT__shift_reg[2]));
        bufp->chgIData(oldp+243,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__dl_c_vld_out_inst__DOT__gen_shift_reg__BRA__0__KET____DOT__sr_inst__DOT__unnamedblk1__DOT__i),32);
        bufp->chgIData(oldp+244,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__dl_c_vld_out_inst__DOT__gen_shift_reg__BRA__0__KET____DOT__sr_inst__DOT__unnamedblk2__DOT__i),32);
        bufp->chgBit(oldp+245,((1U & ((IData)(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__c_vld_line_out) 
                                      >> 1U))));
        bufp->chgBit(oldp+246,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__dl_c_vld_out_inst__DOT__gen_shift_reg__BRA__1__KET____DOT__sr_inst__DOT__shift_reg
                               [1U]));
        bufp->chgBit(oldp+247,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__dl_c_vld_out_inst__DOT__gen_shift_reg__BRA__1__KET____DOT__sr_inst__DOT__shift_reg[0]));
        bufp->chgBit(oldp+248,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__dl_c_vld_out_inst__DOT__gen_shift_reg__BRA__1__KET____DOT__sr_inst__DOT__shift_reg[1]));
        bufp->chgIData(oldp+249,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__dl_c_vld_out_inst__DOT__gen_shift_reg__BRA__1__KET____DOT__sr_inst__DOT__unnamedblk1__DOT__i),32);
        bufp->chgIData(oldp+250,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__dl_c_vld_out_inst__DOT__gen_shift_reg__BRA__1__KET____DOT__sr_inst__DOT__unnamedblk2__DOT__i),32);
        bufp->chgBit(oldp+251,((1U & ((IData)(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__c_vld_line_out) 
                                      >> 2U))));
        bufp->chgBit(oldp+252,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__dl_c_vld_out_inst__DOT__gen_shift_reg__BRA__2__KET____DOT__sr_inst__DOT__shift_reg
                               [0U]));
        bufp->chgBit(oldp+253,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__dl_c_vld_out_inst__DOT__gen_shift_reg__BRA__2__KET____DOT__sr_inst__DOT__shift_reg[0]));
        bufp->chgIData(oldp+254,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__dl_c_vld_out_inst__DOT__gen_shift_reg__BRA__2__KET____DOT__sr_inst__DOT__unnamedblk1__DOT__i),32);
        bufp->chgIData(oldp+255,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__dl_c_vld_out_inst__DOT__gen_shift_reg__BRA__2__KET____DOT__sr_inst__DOT__unnamedblk2__DOT__i),32);
        bufp->chgBit(oldp+256,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT__we_sig
                               [0U][0U]));
        bufp->chgBit(oldp+257,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT__we_sig
                               [0U][1U]));
        bufp->chgBit(oldp+258,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT__we_sig
                               [0U][2U]));
        bufp->chgBit(oldp+259,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT__we_sig
                               [0U][3U]));
        bufp->chgBit(oldp+260,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT__we_sig
                               [0U][4U]));
        bufp->chgBit(oldp+261,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT__we_sig
                               [1U][0U]));
        bufp->chgBit(oldp+262,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT__we_sig
                               [1U][1U]));
        bufp->chgBit(oldp+263,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT__we_sig
                               [1U][2U]));
        bufp->chgBit(oldp+264,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT__we_sig
                               [1U][3U]));
        bufp->chgBit(oldp+265,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT__we_sig
                               [1U][4U]));
        bufp->chgBit(oldp+266,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT__we_sig
                               [2U][0U]));
        bufp->chgBit(oldp+267,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT__we_sig
                               [2U][1U]));
        bufp->chgBit(oldp+268,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT__we_sig
                               [2U][2U]));
        bufp->chgBit(oldp+269,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT__we_sig
                               [2U][3U]));
        bufp->chgBit(oldp+270,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT__we_sig
                               [2U][4U]));
        bufp->chgBit(oldp+271,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT__we_sig
                               [3U][0U]));
        bufp->chgBit(oldp+272,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT__we_sig
                               [3U][1U]));
        bufp->chgBit(oldp+273,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT__we_sig
                               [3U][2U]));
        bufp->chgBit(oldp+274,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT__we_sig
                               [3U][3U]));
        bufp->chgBit(oldp+275,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT__we_sig
                               [3U][4U]));
        bufp->chgBit(oldp+276,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT__we_sig
                               [4U][0U]));
        bufp->chgBit(oldp+277,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT__we_sig
                               [4U][1U]));
        bufp->chgBit(oldp+278,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT__we_sig
                               [4U][2U]));
        bufp->chgBit(oldp+279,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT__we_sig
                               [4U][3U]));
        bufp->chgBit(oldp+280,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT__we_sig
                               [4U][4U]));
        bufp->chgBit(oldp+281,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT__a_vld_sig
                               [0U][0U]));
        bufp->chgBit(oldp+282,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT__a_vld_sig
                               [0U][1U]));
        bufp->chgBit(oldp+283,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT__a_vld_sig
                               [0U][2U]));
        bufp->chgBit(oldp+284,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT__a_vld_sig
                               [0U][3U]));
        bufp->chgBit(oldp+285,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT__a_vld_sig
                               [0U][4U]));
        bufp->chgBit(oldp+286,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT__a_vld_sig
                               [1U][0U]));
        bufp->chgBit(oldp+287,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT__a_vld_sig
                               [1U][1U]));
        bufp->chgBit(oldp+288,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT__a_vld_sig
                               [1U][2U]));
        bufp->chgBit(oldp+289,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT__a_vld_sig
                               [1U][3U]));
        bufp->chgBit(oldp+290,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT__a_vld_sig
                               [1U][4U]));
        bufp->chgBit(oldp+291,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT__a_vld_sig
                               [2U][0U]));
        bufp->chgBit(oldp+292,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT__a_vld_sig
                               [2U][1U]));
        bufp->chgBit(oldp+293,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT__a_vld_sig
                               [2U][2U]));
        bufp->chgBit(oldp+294,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT__a_vld_sig
                               [2U][3U]));
        bufp->chgBit(oldp+295,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT__a_vld_sig
                               [2U][4U]));
        bufp->chgBit(oldp+296,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT__a_vld_sig
                               [3U][0U]));
        bufp->chgBit(oldp+297,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT__a_vld_sig
                               [3U][1U]));
        bufp->chgBit(oldp+298,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT__a_vld_sig
                               [3U][2U]));
        bufp->chgBit(oldp+299,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT__a_vld_sig
                               [3U][3U]));
        bufp->chgBit(oldp+300,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT__a_vld_sig
                               [3U][4U]));
        bufp->chgBit(oldp+301,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT__a_vld_sig
                               [4U][0U]));
        bufp->chgBit(oldp+302,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT__a_vld_sig
                               [4U][1U]));
        bufp->chgBit(oldp+303,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT__a_vld_sig
                               [4U][2U]));
        bufp->chgBit(oldp+304,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT__a_vld_sig
                               [4U][3U]));
        bufp->chgBit(oldp+305,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT__a_vld_sig
                               [4U][4U]));
        bufp->chgBit(oldp+306,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT__c_vld_sig
                               [0U][0U]));
        bufp->chgBit(oldp+307,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT__c_vld_sig
                               [0U][1U]));
        bufp->chgBit(oldp+308,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT__c_vld_sig
                               [0U][2U]));
        bufp->chgBit(oldp+309,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT__c_vld_sig
                               [0U][3U]));
        bufp->chgBit(oldp+310,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT__c_vld_sig
                               [0U][4U]));
        bufp->chgBit(oldp+311,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT__c_vld_sig
                               [1U][0U]));
        bufp->chgBit(oldp+312,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT__c_vld_sig
                               [1U][1U]));
        bufp->chgBit(oldp+313,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT__c_vld_sig
                               [1U][2U]));
        bufp->chgBit(oldp+314,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT__c_vld_sig
                               [1U][3U]));
        bufp->chgBit(oldp+315,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT__c_vld_sig
                               [1U][4U]));
        bufp->chgBit(oldp+316,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT__c_vld_sig
                               [2U][0U]));
        bufp->chgBit(oldp+317,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT__c_vld_sig
                               [2U][1U]));
        bufp->chgBit(oldp+318,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT__c_vld_sig
                               [2U][2U]));
        bufp->chgBit(oldp+319,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT__c_vld_sig
                               [2U][3U]));
        bufp->chgBit(oldp+320,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT__c_vld_sig
                               [2U][4U]));
        bufp->chgBit(oldp+321,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT__c_vld_sig
                               [3U][0U]));
        bufp->chgBit(oldp+322,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT__c_vld_sig
                               [3U][1U]));
        bufp->chgBit(oldp+323,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT__c_vld_sig
                               [3U][2U]));
        bufp->chgBit(oldp+324,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT__c_vld_sig
                               [3U][3U]));
        bufp->chgBit(oldp+325,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT__c_vld_sig
                               [3U][4U]));
        bufp->chgBit(oldp+326,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT__c_vld_sig
                               [4U][0U]));
        bufp->chgBit(oldp+327,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT__c_vld_sig
                               [4U][1U]));
        bufp->chgBit(oldp+328,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT__c_vld_sig
                               [4U][2U]));
        bufp->chgBit(oldp+329,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT__c_vld_sig
                               [4U][3U]));
        bufp->chgBit(oldp+330,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT__c_vld_sig
                               [4U][4U]));
        bufp->chgSData(oldp+331,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT__a_sig
                                 [0U][0U]),16);
        bufp->chgSData(oldp+332,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT__a_sig
                                 [0U][1U]),16);
        bufp->chgSData(oldp+333,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT__a_sig
                                 [0U][2U]),16);
        bufp->chgSData(oldp+334,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT__a_sig
                                 [0U][3U]),16);
        bufp->chgSData(oldp+335,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT__a_sig
                                 [0U][4U]),16);
        bufp->chgSData(oldp+336,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT__a_sig
                                 [1U][0U]),16);
        bufp->chgSData(oldp+337,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT__a_sig
                                 [1U][1U]),16);
        bufp->chgSData(oldp+338,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT__a_sig
                                 [1U][2U]),16);
        bufp->chgSData(oldp+339,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT__a_sig
                                 [1U][3U]),16);
        bufp->chgSData(oldp+340,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT__a_sig
                                 [1U][4U]),16);
        bufp->chgSData(oldp+341,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT__a_sig
                                 [2U][0U]),16);
        bufp->chgSData(oldp+342,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT__a_sig
                                 [2U][1U]),16);
        bufp->chgSData(oldp+343,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT__a_sig
                                 [2U][2U]),16);
        bufp->chgSData(oldp+344,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT__a_sig
                                 [2U][3U]),16);
        bufp->chgSData(oldp+345,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT__a_sig
                                 [2U][4U]),16);
        bufp->chgSData(oldp+346,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT__a_sig
                                 [3U][0U]),16);
        bufp->chgSData(oldp+347,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT__a_sig
                                 [3U][1U]),16);
        bufp->chgSData(oldp+348,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT__a_sig
                                 [3U][2U]),16);
        bufp->chgSData(oldp+349,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT__a_sig
                                 [3U][3U]),16);
        bufp->chgSData(oldp+350,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT__a_sig
                                 [3U][4U]),16);
        bufp->chgSData(oldp+351,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT__a_sig
                                 [4U][0U]),16);
        bufp->chgSData(oldp+352,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT__a_sig
                                 [4U][1U]),16);
        bufp->chgSData(oldp+353,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT__a_sig
                                 [4U][2U]),16);
        bufp->chgSData(oldp+354,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT__a_sig
                                 [4U][3U]),16);
        bufp->chgSData(oldp+355,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT__a_sig
                                 [4U][4U]),16);
        bufp->chgBit(oldp+356,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT__we_sig
                               [0U][0U]));
        bufp->chgBit(oldp+357,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT__a_vld_sig
                               [0U][0U]));
        bufp->chgBit(oldp+358,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT__c_vld_sig
                               [0U][0U]));
        bufp->chgSData(oldp+359,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT__a_sig
                                 [0U][0U]),16);
        bufp->chgBit(oldp+360,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT____Vcellout__gen_pe_row__BRA__0__KET____DOT__gen_pe_col__BRA__0__KET____DOT__pe_inst__o_we));
        bufp->chgBit(oldp+361,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT____Vcellout__gen_pe_row__BRA__0__KET____DOT__gen_pe_col__BRA__0__KET____DOT__pe_inst__o_a_vld));
        bufp->chgBit(oldp+362,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT____Vcellout__gen_pe_row__BRA__0__KET____DOT__gen_pe_col__BRA__0__KET____DOT__pe_inst__o_c_vld));
        bufp->chgSData(oldp+363,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT____Vcellout__gen_pe_row__BRA__0__KET____DOT__gen_pe_col__BRA__0__KET____DOT__pe_inst__o_a),16);
        bufp->chgSData(oldp+364,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT____Vcellout__gen_pe_row__BRA__0__KET____DOT__gen_pe_col__BRA__0__KET____DOT__pe_inst__o_c),16);
        bufp->chgSData(oldp+365,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT__gen_pe_row__BRA__0__KET____DOT__gen_pe_col__BRA__0__KET____DOT__pe_inst__DOT__b_reg),16);
        bufp->chgBit(oldp+366,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT__we_sig
                               [0U][1U]));
        bufp->chgBit(oldp+367,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT__a_vld_sig
                               [0U][1U]));
        bufp->chgBit(oldp+368,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT__c_vld_sig
                               [0U][1U]));
        bufp->chgSData(oldp+369,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT__a_sig
                                 [0U][1U]),16);
        bufp->chgBit(oldp+370,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT____Vcellout__gen_pe_row__BRA__0__KET____DOT__gen_pe_col__BRA__1__KET____DOT__pe_inst__o_we));
        bufp->chgBit(oldp+371,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT____Vcellout__gen_pe_row__BRA__0__KET____DOT__gen_pe_col__BRA__1__KET____DOT__pe_inst__o_a_vld));
        bufp->chgBit(oldp+372,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT____Vcellout__gen_pe_row__BRA__0__KET____DOT__gen_pe_col__BRA__1__KET____DOT__pe_inst__o_c_vld));
        bufp->chgSData(oldp+373,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT____Vcellout__gen_pe_row__BRA__0__KET____DOT__gen_pe_col__BRA__1__KET____DOT__pe_inst__o_a),16);
        bufp->chgSData(oldp+374,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT____Vcellout__gen_pe_row__BRA__0__KET____DOT__gen_pe_col__BRA__1__KET____DOT__pe_inst__o_c),16);
        bufp->chgSData(oldp+375,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT__gen_pe_row__BRA__0__KET____DOT__gen_pe_col__BRA__1__KET____DOT__pe_inst__DOT__b_reg),16);
        bufp->chgBit(oldp+376,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT__we_sig
                               [0U][2U]));
        bufp->chgBit(oldp+377,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT__a_vld_sig
                               [0U][2U]));
        bufp->chgBit(oldp+378,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT__c_vld_sig
                               [0U][2U]));
        bufp->chgSData(oldp+379,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT__a_sig
                                 [0U][2U]),16);
        bufp->chgBit(oldp+380,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT____Vcellout__gen_pe_row__BRA__0__KET____DOT__gen_pe_col__BRA__2__KET____DOT__pe_inst__o_we));
        bufp->chgBit(oldp+381,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT____Vcellout__gen_pe_row__BRA__0__KET____DOT__gen_pe_col__BRA__2__KET____DOT__pe_inst__o_a_vld));
        bufp->chgBit(oldp+382,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT____Vcellout__gen_pe_row__BRA__0__KET____DOT__gen_pe_col__BRA__2__KET____DOT__pe_inst__o_c_vld));
        bufp->chgSData(oldp+383,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT____Vcellout__gen_pe_row__BRA__0__KET____DOT__gen_pe_col__BRA__2__KET____DOT__pe_inst__o_a),16);
        bufp->chgSData(oldp+384,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT____Vcellout__gen_pe_row__BRA__0__KET____DOT__gen_pe_col__BRA__2__KET____DOT__pe_inst__o_c),16);
        bufp->chgSData(oldp+385,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT__gen_pe_row__BRA__0__KET____DOT__gen_pe_col__BRA__2__KET____DOT__pe_inst__DOT__b_reg),16);
        bufp->chgBit(oldp+386,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT__we_sig
                               [0U][3U]));
        bufp->chgBit(oldp+387,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT__a_vld_sig
                               [0U][3U]));
        bufp->chgBit(oldp+388,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT__c_vld_sig
                               [0U][3U]));
        bufp->chgSData(oldp+389,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT__a_sig
                                 [0U][3U]),16);
        bufp->chgBit(oldp+390,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT____Vcellout__gen_pe_row__BRA__0__KET____DOT__gen_pe_col__BRA__3__KET____DOT__pe_inst__o_we));
        bufp->chgBit(oldp+391,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT____Vcellout__gen_pe_row__BRA__0__KET____DOT__gen_pe_col__BRA__3__KET____DOT__pe_inst__o_a_vld));
        bufp->chgBit(oldp+392,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT____Vcellout__gen_pe_row__BRA__0__KET____DOT__gen_pe_col__BRA__3__KET____DOT__pe_inst__o_c_vld));
        bufp->chgSData(oldp+393,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT____Vcellout__gen_pe_row__BRA__0__KET____DOT__gen_pe_col__BRA__3__KET____DOT__pe_inst__o_a),16);
        bufp->chgSData(oldp+394,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT____Vcellout__gen_pe_row__BRA__0__KET____DOT__gen_pe_col__BRA__3__KET____DOT__pe_inst__o_c),16);
        bufp->chgSData(oldp+395,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT__gen_pe_row__BRA__0__KET____DOT__gen_pe_col__BRA__3__KET____DOT__pe_inst__DOT__b_reg),16);
        bufp->chgBit(oldp+396,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT__we_sig
                               [1U][0U]));
        bufp->chgBit(oldp+397,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT__a_vld_sig
                               [1U][0U]));
        bufp->chgBit(oldp+398,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT__c_vld_sig
                               [1U][0U]));
        bufp->chgSData(oldp+399,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT__a_sig
                                 [1U][0U]),16);
        bufp->chgBit(oldp+400,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT____Vcellout__gen_pe_row__BRA__1__KET____DOT__gen_pe_col__BRA__0__KET____DOT__pe_inst__o_we));
        bufp->chgBit(oldp+401,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT____Vcellout__gen_pe_row__BRA__1__KET____DOT__gen_pe_col__BRA__0__KET____DOT__pe_inst__o_a_vld));
        bufp->chgBit(oldp+402,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT____Vcellout__gen_pe_row__BRA__1__KET____DOT__gen_pe_col__BRA__0__KET____DOT__pe_inst__o_c_vld));
        bufp->chgSData(oldp+403,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT____Vcellout__gen_pe_row__BRA__1__KET____DOT__gen_pe_col__BRA__0__KET____DOT__pe_inst__o_a),16);
        bufp->chgSData(oldp+404,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT____Vcellout__gen_pe_row__BRA__1__KET____DOT__gen_pe_col__BRA__0__KET____DOT__pe_inst__o_c),16);
        bufp->chgSData(oldp+405,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT__gen_pe_row__BRA__1__KET____DOT__gen_pe_col__BRA__0__KET____DOT__pe_inst__DOT__b_reg),16);
        bufp->chgBit(oldp+406,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT__we_sig
                               [1U][1U]));
        bufp->chgBit(oldp+407,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT__a_vld_sig
                               [1U][1U]));
        bufp->chgBit(oldp+408,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT__c_vld_sig
                               [1U][1U]));
        bufp->chgSData(oldp+409,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT__a_sig
                                 [1U][1U]),16);
        bufp->chgBit(oldp+410,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT____Vcellout__gen_pe_row__BRA__1__KET____DOT__gen_pe_col__BRA__1__KET____DOT__pe_inst__o_we));
        bufp->chgBit(oldp+411,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT____Vcellout__gen_pe_row__BRA__1__KET____DOT__gen_pe_col__BRA__1__KET____DOT__pe_inst__o_a_vld));
        bufp->chgBit(oldp+412,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT____Vcellout__gen_pe_row__BRA__1__KET____DOT__gen_pe_col__BRA__1__KET____DOT__pe_inst__o_c_vld));
        bufp->chgSData(oldp+413,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT____Vcellout__gen_pe_row__BRA__1__KET____DOT__gen_pe_col__BRA__1__KET____DOT__pe_inst__o_a),16);
        bufp->chgSData(oldp+414,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT____Vcellout__gen_pe_row__BRA__1__KET____DOT__gen_pe_col__BRA__1__KET____DOT__pe_inst__o_c),16);
        bufp->chgSData(oldp+415,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT__gen_pe_row__BRA__1__KET____DOT__gen_pe_col__BRA__1__KET____DOT__pe_inst__DOT__b_reg),16);
        bufp->chgBit(oldp+416,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT__we_sig
                               [1U][2U]));
        bufp->chgBit(oldp+417,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT__a_vld_sig
                               [1U][2U]));
        bufp->chgBit(oldp+418,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT__c_vld_sig
                               [1U][2U]));
        bufp->chgSData(oldp+419,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT__a_sig
                                 [1U][2U]),16);
        bufp->chgBit(oldp+420,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT____Vcellout__gen_pe_row__BRA__1__KET____DOT__gen_pe_col__BRA__2__KET____DOT__pe_inst__o_we));
        bufp->chgBit(oldp+421,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT____Vcellout__gen_pe_row__BRA__1__KET____DOT__gen_pe_col__BRA__2__KET____DOT__pe_inst__o_a_vld));
        bufp->chgBit(oldp+422,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT____Vcellout__gen_pe_row__BRA__1__KET____DOT__gen_pe_col__BRA__2__KET____DOT__pe_inst__o_c_vld));
        bufp->chgSData(oldp+423,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT____Vcellout__gen_pe_row__BRA__1__KET____DOT__gen_pe_col__BRA__2__KET____DOT__pe_inst__o_a),16);
        bufp->chgSData(oldp+424,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT____Vcellout__gen_pe_row__BRA__1__KET____DOT__gen_pe_col__BRA__2__KET____DOT__pe_inst__o_c),16);
        bufp->chgSData(oldp+425,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT__gen_pe_row__BRA__1__KET____DOT__gen_pe_col__BRA__2__KET____DOT__pe_inst__DOT__b_reg),16);
        bufp->chgBit(oldp+426,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT__we_sig
                               [1U][3U]));
        bufp->chgBit(oldp+427,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT__a_vld_sig
                               [1U][3U]));
        bufp->chgBit(oldp+428,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT__c_vld_sig
                               [1U][3U]));
        bufp->chgSData(oldp+429,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT__a_sig
                                 [1U][3U]),16);
        bufp->chgBit(oldp+430,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT____Vcellout__gen_pe_row__BRA__1__KET____DOT__gen_pe_col__BRA__3__KET____DOT__pe_inst__o_we));
        bufp->chgBit(oldp+431,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT____Vcellout__gen_pe_row__BRA__1__KET____DOT__gen_pe_col__BRA__3__KET____DOT__pe_inst__o_a_vld));
        bufp->chgBit(oldp+432,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT____Vcellout__gen_pe_row__BRA__1__KET____DOT__gen_pe_col__BRA__3__KET____DOT__pe_inst__o_c_vld));
        bufp->chgSData(oldp+433,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT____Vcellout__gen_pe_row__BRA__1__KET____DOT__gen_pe_col__BRA__3__KET____DOT__pe_inst__o_a),16);
        bufp->chgSData(oldp+434,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT____Vcellout__gen_pe_row__BRA__1__KET____DOT__gen_pe_col__BRA__3__KET____DOT__pe_inst__o_c),16);
        bufp->chgSData(oldp+435,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT__gen_pe_row__BRA__1__KET____DOT__gen_pe_col__BRA__3__KET____DOT__pe_inst__DOT__b_reg),16);
        bufp->chgBit(oldp+436,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT__we_sig
                               [2U][0U]));
        bufp->chgBit(oldp+437,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT__a_vld_sig
                               [2U][0U]));
        bufp->chgBit(oldp+438,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT__c_vld_sig
                               [2U][0U]));
        bufp->chgSData(oldp+439,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT__a_sig
                                 [2U][0U]),16);
        bufp->chgBit(oldp+440,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT____Vcellout__gen_pe_row__BRA__2__KET____DOT__gen_pe_col__BRA__0__KET____DOT__pe_inst__o_we));
        bufp->chgBit(oldp+441,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT____Vcellout__gen_pe_row__BRA__2__KET____DOT__gen_pe_col__BRA__0__KET____DOT__pe_inst__o_a_vld));
        bufp->chgBit(oldp+442,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT____Vcellout__gen_pe_row__BRA__2__KET____DOT__gen_pe_col__BRA__0__KET____DOT__pe_inst__o_c_vld));
        bufp->chgSData(oldp+443,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT____Vcellout__gen_pe_row__BRA__2__KET____DOT__gen_pe_col__BRA__0__KET____DOT__pe_inst__o_a),16);
        bufp->chgSData(oldp+444,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT____Vcellout__gen_pe_row__BRA__2__KET____DOT__gen_pe_col__BRA__0__KET____DOT__pe_inst__o_c),16);
        bufp->chgSData(oldp+445,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT__gen_pe_row__BRA__2__KET____DOT__gen_pe_col__BRA__0__KET____DOT__pe_inst__DOT__b_reg),16);
        bufp->chgBit(oldp+446,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT__we_sig
                               [2U][1U]));
        bufp->chgBit(oldp+447,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT__a_vld_sig
                               [2U][1U]));
        bufp->chgBit(oldp+448,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT__c_vld_sig
                               [2U][1U]));
        bufp->chgSData(oldp+449,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT__a_sig
                                 [2U][1U]),16);
        bufp->chgBit(oldp+450,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT____Vcellout__gen_pe_row__BRA__2__KET____DOT__gen_pe_col__BRA__1__KET____DOT__pe_inst__o_we));
        bufp->chgBit(oldp+451,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT____Vcellout__gen_pe_row__BRA__2__KET____DOT__gen_pe_col__BRA__1__KET____DOT__pe_inst__o_a_vld));
        bufp->chgBit(oldp+452,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT____Vcellout__gen_pe_row__BRA__2__KET____DOT__gen_pe_col__BRA__1__KET____DOT__pe_inst__o_c_vld));
        bufp->chgSData(oldp+453,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT____Vcellout__gen_pe_row__BRA__2__KET____DOT__gen_pe_col__BRA__1__KET____DOT__pe_inst__o_a),16);
        bufp->chgSData(oldp+454,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT____Vcellout__gen_pe_row__BRA__2__KET____DOT__gen_pe_col__BRA__1__KET____DOT__pe_inst__o_c),16);
        bufp->chgSData(oldp+455,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT__gen_pe_row__BRA__2__KET____DOT__gen_pe_col__BRA__1__KET____DOT__pe_inst__DOT__b_reg),16);
        bufp->chgBit(oldp+456,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT__we_sig
                               [2U][2U]));
        bufp->chgBit(oldp+457,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT__a_vld_sig
                               [2U][2U]));
        bufp->chgBit(oldp+458,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT__c_vld_sig
                               [2U][2U]));
        bufp->chgSData(oldp+459,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT__a_sig
                                 [2U][2U]),16);
        bufp->chgBit(oldp+460,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT____Vcellout__gen_pe_row__BRA__2__KET____DOT__gen_pe_col__BRA__2__KET____DOT__pe_inst__o_we));
        bufp->chgBit(oldp+461,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT____Vcellout__gen_pe_row__BRA__2__KET____DOT__gen_pe_col__BRA__2__KET____DOT__pe_inst__o_a_vld));
        bufp->chgBit(oldp+462,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT____Vcellout__gen_pe_row__BRA__2__KET____DOT__gen_pe_col__BRA__2__KET____DOT__pe_inst__o_c_vld));
        bufp->chgSData(oldp+463,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT____Vcellout__gen_pe_row__BRA__2__KET____DOT__gen_pe_col__BRA__2__KET____DOT__pe_inst__o_a),16);
        bufp->chgSData(oldp+464,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT____Vcellout__gen_pe_row__BRA__2__KET____DOT__gen_pe_col__BRA__2__KET____DOT__pe_inst__o_c),16);
        bufp->chgSData(oldp+465,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT__gen_pe_row__BRA__2__KET____DOT__gen_pe_col__BRA__2__KET____DOT__pe_inst__DOT__b_reg),16);
        bufp->chgBit(oldp+466,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT__we_sig
                               [2U][3U]));
        bufp->chgBit(oldp+467,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT__a_vld_sig
                               [2U][3U]));
        bufp->chgBit(oldp+468,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT__c_vld_sig
                               [2U][3U]));
        bufp->chgSData(oldp+469,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT__a_sig
                                 [2U][3U]),16);
        bufp->chgBit(oldp+470,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT____Vcellout__gen_pe_row__BRA__2__KET____DOT__gen_pe_col__BRA__3__KET____DOT__pe_inst__o_we));
        bufp->chgBit(oldp+471,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT____Vcellout__gen_pe_row__BRA__2__KET____DOT__gen_pe_col__BRA__3__KET____DOT__pe_inst__o_a_vld));
        bufp->chgBit(oldp+472,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT____Vcellout__gen_pe_row__BRA__2__KET____DOT__gen_pe_col__BRA__3__KET____DOT__pe_inst__o_c_vld));
        bufp->chgSData(oldp+473,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT____Vcellout__gen_pe_row__BRA__2__KET____DOT__gen_pe_col__BRA__3__KET____DOT__pe_inst__o_a),16);
        bufp->chgSData(oldp+474,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT____Vcellout__gen_pe_row__BRA__2__KET____DOT__gen_pe_col__BRA__3__KET____DOT__pe_inst__o_c),16);
        bufp->chgSData(oldp+475,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT__gen_pe_row__BRA__2__KET____DOT__gen_pe_col__BRA__3__KET____DOT__pe_inst__DOT__b_reg),16);
        bufp->chgBit(oldp+476,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT__we_sig
                               [3U][0U]));
        bufp->chgBit(oldp+477,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT__a_vld_sig
                               [3U][0U]));
        bufp->chgBit(oldp+478,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT__c_vld_sig
                               [3U][0U]));
        bufp->chgSData(oldp+479,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT__a_sig
                                 [3U][0U]),16);
        bufp->chgBit(oldp+480,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT____Vcellout__gen_pe_row__BRA__3__KET____DOT__gen_pe_col__BRA__0__KET____DOT__pe_inst__o_we));
        bufp->chgBit(oldp+481,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT____Vcellout__gen_pe_row__BRA__3__KET____DOT__gen_pe_col__BRA__0__KET____DOT__pe_inst__o_a_vld));
        bufp->chgBit(oldp+482,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT____Vcellout__gen_pe_row__BRA__3__KET____DOT__gen_pe_col__BRA__0__KET____DOT__pe_inst__o_c_vld));
        bufp->chgSData(oldp+483,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT____Vcellout__gen_pe_row__BRA__3__KET____DOT__gen_pe_col__BRA__0__KET____DOT__pe_inst__o_a),16);
        bufp->chgSData(oldp+484,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT____Vcellout__gen_pe_row__BRA__3__KET____DOT__gen_pe_col__BRA__0__KET____DOT__pe_inst__o_c),16);
        bufp->chgSData(oldp+485,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT__gen_pe_row__BRA__3__KET____DOT__gen_pe_col__BRA__0__KET____DOT__pe_inst__DOT__b_reg),16);
        bufp->chgBit(oldp+486,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT__we_sig
                               [3U][1U]));
        bufp->chgBit(oldp+487,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT__a_vld_sig
                               [3U][1U]));
        bufp->chgBit(oldp+488,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT__c_vld_sig
                               [3U][1U]));
        bufp->chgSData(oldp+489,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT__a_sig
                                 [3U][1U]),16);
        bufp->chgBit(oldp+490,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT____Vcellout__gen_pe_row__BRA__3__KET____DOT__gen_pe_col__BRA__1__KET____DOT__pe_inst__o_we));
        bufp->chgBit(oldp+491,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT____Vcellout__gen_pe_row__BRA__3__KET____DOT__gen_pe_col__BRA__1__KET____DOT__pe_inst__o_a_vld));
        bufp->chgBit(oldp+492,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT____Vcellout__gen_pe_row__BRA__3__KET____DOT__gen_pe_col__BRA__1__KET____DOT__pe_inst__o_c_vld));
        bufp->chgSData(oldp+493,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT____Vcellout__gen_pe_row__BRA__3__KET____DOT__gen_pe_col__BRA__1__KET____DOT__pe_inst__o_a),16);
        bufp->chgSData(oldp+494,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT____Vcellout__gen_pe_row__BRA__3__KET____DOT__gen_pe_col__BRA__1__KET____DOT__pe_inst__o_c),16);
        bufp->chgSData(oldp+495,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT__gen_pe_row__BRA__3__KET____DOT__gen_pe_col__BRA__1__KET____DOT__pe_inst__DOT__b_reg),16);
        bufp->chgBit(oldp+496,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT__we_sig
                               [3U][2U]));
        bufp->chgBit(oldp+497,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT__a_vld_sig
                               [3U][2U]));
        bufp->chgBit(oldp+498,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT__c_vld_sig
                               [3U][2U]));
        bufp->chgSData(oldp+499,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT__a_sig
                                 [3U][2U]),16);
        bufp->chgBit(oldp+500,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT____Vcellout__gen_pe_row__BRA__3__KET____DOT__gen_pe_col__BRA__2__KET____DOT__pe_inst__o_we));
        bufp->chgBit(oldp+501,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT____Vcellout__gen_pe_row__BRA__3__KET____DOT__gen_pe_col__BRA__2__KET____DOT__pe_inst__o_a_vld));
        bufp->chgBit(oldp+502,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT____Vcellout__gen_pe_row__BRA__3__KET____DOT__gen_pe_col__BRA__2__KET____DOT__pe_inst__o_c_vld));
        bufp->chgSData(oldp+503,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT____Vcellout__gen_pe_row__BRA__3__KET____DOT__gen_pe_col__BRA__2__KET____DOT__pe_inst__o_a),16);
        bufp->chgSData(oldp+504,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT____Vcellout__gen_pe_row__BRA__3__KET____DOT__gen_pe_col__BRA__2__KET____DOT__pe_inst__o_c),16);
        bufp->chgSData(oldp+505,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT__gen_pe_row__BRA__3__KET____DOT__gen_pe_col__BRA__2__KET____DOT__pe_inst__DOT__b_reg),16);
        bufp->chgBit(oldp+506,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT__we_sig
                               [3U][3U]));
        bufp->chgBit(oldp+507,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT__a_vld_sig
                               [3U][3U]));
        bufp->chgBit(oldp+508,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT__c_vld_sig
                               [3U][3U]));
        bufp->chgSData(oldp+509,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT__a_sig
                                 [3U][3U]),16);
        bufp->chgBit(oldp+510,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT____Vcellout__gen_pe_row__BRA__3__KET____DOT__gen_pe_col__BRA__3__KET____DOT__pe_inst__o_we));
        bufp->chgBit(oldp+511,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT____Vcellout__gen_pe_row__BRA__3__KET____DOT__gen_pe_col__BRA__3__KET____DOT__pe_inst__o_a_vld));
        bufp->chgBit(oldp+512,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT____Vcellout__gen_pe_row__BRA__3__KET____DOT__gen_pe_col__BRA__3__KET____DOT__pe_inst__o_c_vld));
        bufp->chgSData(oldp+513,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT____Vcellout__gen_pe_row__BRA__3__KET____DOT__gen_pe_col__BRA__3__KET____DOT__pe_inst__o_a),16);
        bufp->chgSData(oldp+514,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT____Vcellout__gen_pe_row__BRA__3__KET____DOT__gen_pe_col__BRA__3__KET____DOT__pe_inst__o_c),16);
        bufp->chgSData(oldp+515,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__sa_core_inst__DOT__gen_pe_row__BRA__3__KET____DOT__gen_pe_col__BRA__3__KET____DOT__pe_inst__DOT__b_reg),16);
        bufp->chgCData(oldp+516,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__we_line_inst__DOT__dl_inst__DOT__i_data),4);
        bufp->chgBit(oldp+517,((1U & ((IData)(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__we_line_inst__DOT__dl_inst__DOT__i_data) 
                                      >> 1U))));
        bufp->chgBit(oldp+518,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__we_line_inst__DOT__dl_inst__DOT__gen_shift_reg__BRA__1__KET____DOT__sr_inst__DOT__shift_reg
                               [0U]));
        bufp->chgBit(oldp+519,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__we_line_inst__DOT__dl_inst__DOT__gen_shift_reg__BRA__1__KET____DOT__sr_inst__DOT__shift_reg[0]));
        bufp->chgIData(oldp+520,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__we_line_inst__DOT__dl_inst__DOT__gen_shift_reg__BRA__1__KET____DOT__sr_inst__DOT__unnamedblk1__DOT__i),32);
        bufp->chgIData(oldp+521,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__we_line_inst__DOT__dl_inst__DOT__gen_shift_reg__BRA__1__KET____DOT__sr_inst__DOT__unnamedblk2__DOT__i),32);
        bufp->chgBit(oldp+522,((1U & ((IData)(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__we_line_inst__DOT__dl_inst__DOT__i_data) 
                                      >> 2U))));
        bufp->chgBit(oldp+523,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__we_line_inst__DOT__dl_inst__DOT__gen_shift_reg__BRA__2__KET____DOT__sr_inst__DOT__shift_reg
                               [1U]));
        bufp->chgBit(oldp+524,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__we_line_inst__DOT__dl_inst__DOT__gen_shift_reg__BRA__2__KET____DOT__sr_inst__DOT__shift_reg[0]));
        bufp->chgBit(oldp+525,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__we_line_inst__DOT__dl_inst__DOT__gen_shift_reg__BRA__2__KET____DOT__sr_inst__DOT__shift_reg[1]));
        bufp->chgIData(oldp+526,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__we_line_inst__DOT__dl_inst__DOT__gen_shift_reg__BRA__2__KET____DOT__sr_inst__DOT__unnamedblk1__DOT__i),32);
        bufp->chgIData(oldp+527,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__we_line_inst__DOT__dl_inst__DOT__gen_shift_reg__BRA__2__KET____DOT__sr_inst__DOT__unnamedblk2__DOT__i),32);
        bufp->chgBit(oldp+528,((1U & ((IData)(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__we_line_inst__DOT__dl_inst__DOT__i_data) 
                                      >> 3U))));
        bufp->chgBit(oldp+529,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__we_line_inst__DOT__dl_inst__DOT__gen_shift_reg__BRA__3__KET____DOT__sr_inst__DOT__shift_reg
                               [2U]));
        bufp->chgBit(oldp+530,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__we_line_inst__DOT__dl_inst__DOT__gen_shift_reg__BRA__3__KET____DOT__sr_inst__DOT__shift_reg[0]));
        bufp->chgBit(oldp+531,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__we_line_inst__DOT__dl_inst__DOT__gen_shift_reg__BRA__3__KET____DOT__sr_inst__DOT__shift_reg[1]));
        bufp->chgBit(oldp+532,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__we_line_inst__DOT__dl_inst__DOT__gen_shift_reg__BRA__3__KET____DOT__sr_inst__DOT__shift_reg[2]));
        bufp->chgIData(oldp+533,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__we_line_inst__DOT__dl_inst__DOT__gen_shift_reg__BRA__3__KET____DOT__sr_inst__DOT__unnamedblk1__DOT__i),32);
        bufp->chgIData(oldp+534,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__sa_top_inst__DOT__we_line_inst__DOT__dl_inst__DOT__gen_shift_reg__BRA__3__KET____DOT__sr_inst__DOT__unnamedblk2__DOT__i),32);
    }
    bufp->chgBit(oldp+535,(vlSelfRef.sa_axi_top_tb__DOT__clk));
    bufp->chgCData(oldp+536,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__addr_gen_inst__DOT__next_state),3);
    bufp->chgBit(oldp+537,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__addr_gen_inst__DOT__start_b_pulse));
    bufp->chgBit(oldp+538,(vlSelfRef.sa_axi_top_tb__DOT__dut__DOT__addr_gen_inst__DOT__start_ac_pulse));
}

void Vsa_axi_top_tb___024root__trace_cleanup(void* voidSelf, VerilatedVcd* /*unused*/) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vsa_axi_top_tb___024root__trace_cleanup\n"); );
    // Body
    Vsa_axi_top_tb___024root* const __restrict vlSelf VL_ATTR_UNUSED = static_cast<Vsa_axi_top_tb___024root*>(voidSelf);
    Vsa_axi_top_tb__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    vlSymsp->__Vm_activity = false;
    vlSymsp->TOP.__Vm_traceActivity[0U] = 0U;
    vlSymsp->TOP.__Vm_traceActivity[1U] = 0U;
    vlSymsp->TOP.__Vm_traceActivity[2U] = 0U;
    vlSymsp->TOP.__Vm_traceActivity[3U] = 0U;
}
