// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design internal header
// See Vtop.h for the primary calling header

#ifndef VERILATED_VTOP___024ROOT_H_
#define VERILATED_VTOP___024ROOT_H_  // guard

#include "verilated.h"


class Vtop__Syms;

class alignas(VL_CACHE_LINE_BYTES) Vtop___024root final : public VerilatedModule {
  public:

    // DESIGN SPECIFIC STATE
    // Anonymous structures to workaround compiler member-count bugs
    struct {
        VL_IN8(clk,0,0);
        VL_IN8(rst_n,0,0);
        VL_IN8(i_vld,0,0);
        VL_OUT8(o_rdy,0,0);
        VL_IN8(i_rdy,0,0);
        VL_OUT8(o_vld,0,0);
        CData/*0:0*/ sa_credit_top__DOT__clk;
        CData/*0:0*/ sa_credit_top__DOT__rst_n;
        CData/*0:0*/ sa_credit_top__DOT__i_vld;
        CData/*0:0*/ sa_credit_top__DOT__o_rdy;
        CData/*0:0*/ sa_credit_top__DOT__i_rdy;
        CData/*0:0*/ sa_credit_top__DOT__o_vld;
        CData/*0:0*/ sa_credit_top__DOT__a_vld;
        CData/*2:0*/ sa_credit_top__DOT__count;
        CData/*0:0*/ sa_credit_top__DOT__is_a;
        CData/*0:0*/ sa_credit_top__DOT__last_line;
        CData/*0:0*/ sa_credit_top__DOT__c_vld_top2sa;
        CData/*0:0*/ sa_credit_top__DOT__we;
        CData/*0:0*/ sa_credit_top__DOT__c_vld_sa2top;
        CData/*0:0*/ sa_credit_top__DOT__fifo_full;
        CData/*0:0*/ sa_credit_top__DOT__fifo_empty;
        CData/*0:0*/ sa_credit_top__DOT__fifo_wr_en;
        CData/*0:0*/ sa_credit_top__DOT__fifo_rd_en;
        CData/*0:0*/ sa_credit_top__DOT__inc;
        CData/*0:0*/ sa_credit_top__DOT__sa_top_inst__DOT__clk;
        CData/*0:0*/ sa_credit_top__DOT__sa_top_inst__DOT__rst_n;
        CData/*0:0*/ sa_credit_top__DOT__sa_top_inst__DOT__i_we;
        CData/*0:0*/ sa_credit_top__DOT__sa_top_inst__DOT__i_a_vld;
        CData/*0:0*/ sa_credit_top__DOT__sa_top_inst__DOT__i_c_vld;
        CData/*0:0*/ sa_credit_top__DOT__sa_top_inst__DOT__o_c_vld;
        CData/*3:0*/ sa_credit_top__DOT__sa_top_inst__DOT__we_line;
        CData/*3:0*/ sa_credit_top__DOT__sa_top_inst__DOT__a_vld_line;
        CData/*3:0*/ sa_credit_top__DOT__sa_top_inst__DOT__c_vld_line_top2core;
        CData/*3:0*/ sa_credit_top__DOT__sa_top_inst__DOT__c_vld_line_core2top;
        CData/*3:0*/ sa_credit_top__DOT__sa_top_inst__DOT__c_vld_line_delayed_core2top;
        CData/*0:0*/ sa_credit_top__DOT__sa_top_inst__DOT__we_line_inst__DOT__clk;
        CData/*0:0*/ sa_credit_top__DOT__sa_top_inst__DOT__we_line_inst__DOT__rst_n;
        CData/*0:0*/ sa_credit_top__DOT__sa_top_inst__DOT__we_line_inst__DOT__i_we;
        CData/*3:0*/ sa_credit_top__DOT__sa_top_inst__DOT__we_line_inst__DOT__o_we_line;
        CData/*3:0*/ sa_credit_top__DOT__sa_top_inst__DOT__we_line_inst__DOT__we_shift;
        CData/*3:0*/ sa_credit_top__DOT__sa_top_inst__DOT__we_line_inst__DOT__we_gen;
        CData/*0:0*/ sa_credit_top__DOT__sa_top_inst__DOT__we_line_inst__DOT__dl_inst__DOT__clk;
        CData/*0:0*/ sa_credit_top__DOT__sa_top_inst__DOT__we_line_inst__DOT__dl_inst__DOT__rst_n;
        CData/*3:0*/ sa_credit_top__DOT__sa_top_inst__DOT__we_line_inst__DOT__dl_inst__DOT__i_data;
        CData/*3:0*/ sa_credit_top__DOT__sa_top_inst__DOT__we_line_inst__DOT__dl_inst__DOT__o_data;
        CData/*0:0*/ sa_credit_top__DOT__sa_top_inst__DOT__we_line_inst__DOT__dl_inst__DOT__sr_gen__BRA__1__KET____DOT__sr_inst__DOT__clk;
        CData/*0:0*/ sa_credit_top__DOT__sa_top_inst__DOT__we_line_inst__DOT__dl_inst__DOT__sr_gen__BRA__1__KET____DOT__sr_inst__DOT__rst_n;
        CData/*0:0*/ sa_credit_top__DOT__sa_top_inst__DOT__we_line_inst__DOT__dl_inst__DOT__sr_gen__BRA__1__KET____DOT__sr_inst__DOT__i_data;
        CData/*0:0*/ sa_credit_top__DOT__sa_top_inst__DOT__we_line_inst__DOT__dl_inst__DOT__sr_gen__BRA__1__KET____DOT__sr_inst__DOT__o_data;
        CData/*0:0*/ sa_credit_top__DOT__sa_top_inst__DOT__we_line_inst__DOT__dl_inst__DOT__sr_gen__BRA__1__KET____DOT__sr_inst__DOT____Vlvbound_hefb97aa7__0;
        CData/*0:0*/ sa_credit_top__DOT__sa_top_inst__DOT__we_line_inst__DOT__dl_inst__DOT__sr_gen__BRA__1__KET____DOT__sr_inst__DOT____Vlvbound_h8300f980__0;
        CData/*0:0*/ sa_credit_top__DOT__sa_top_inst__DOT__we_line_inst__DOT__dl_inst__DOT__sr_gen__BRA__2__KET____DOT__sr_inst__DOT__clk;
        CData/*0:0*/ sa_credit_top__DOT__sa_top_inst__DOT__we_line_inst__DOT__dl_inst__DOT__sr_gen__BRA__2__KET____DOT__sr_inst__DOT__rst_n;
        CData/*0:0*/ sa_credit_top__DOT__sa_top_inst__DOT__we_line_inst__DOT__dl_inst__DOT__sr_gen__BRA__2__KET____DOT__sr_inst__DOT__i_data;
        CData/*0:0*/ sa_credit_top__DOT__sa_top_inst__DOT__we_line_inst__DOT__dl_inst__DOT__sr_gen__BRA__2__KET____DOT__sr_inst__DOT__o_data;
        CData/*0:0*/ sa_credit_top__DOT__sa_top_inst__DOT__we_line_inst__DOT__dl_inst__DOT__sr_gen__BRA__3__KET____DOT__sr_inst__DOT__clk;
        CData/*0:0*/ sa_credit_top__DOT__sa_top_inst__DOT__we_line_inst__DOT__dl_inst__DOT__sr_gen__BRA__3__KET____DOT__sr_inst__DOT__rst_n;
        CData/*0:0*/ sa_credit_top__DOT__sa_top_inst__DOT__we_line_inst__DOT__dl_inst__DOT__sr_gen__BRA__3__KET____DOT__sr_inst__DOT__i_data;
        CData/*0:0*/ sa_credit_top__DOT__sa_top_inst__DOT__we_line_inst__DOT__dl_inst__DOT__sr_gen__BRA__3__KET____DOT__sr_inst__DOT__o_data;
        CData/*0:0*/ sa_credit_top__DOT__sa_top_inst__DOT__we_line_inst__DOT__dl_inst__DOT__sr_gen__BRA__3__KET____DOT__sr_inst__DOT____Vlvbound_hed2f8500__0;
        CData/*0:0*/ sa_credit_top__DOT__sa_top_inst__DOT__we_line_inst__DOT__dl_inst__DOT__sr_gen__BRA__3__KET____DOT__sr_inst__DOT____Vlvbound_h99f6fe1b__0;
        CData/*0:0*/ sa_credit_top__DOT__sa_top_inst__DOT__dl_a_vld_inst__DOT__clk;
        CData/*0:0*/ sa_credit_top__DOT__sa_top_inst__DOT__dl_a_vld_inst__DOT__rst_n;
        CData/*3:0*/ sa_credit_top__DOT__sa_top_inst__DOT__dl_a_vld_inst__DOT__i_data;
    };
    struct {
        CData/*3:0*/ sa_credit_top__DOT__sa_top_inst__DOT__dl_a_vld_inst__DOT__o_data;
        CData/*0:0*/ sa_credit_top__DOT__sa_top_inst__DOT__dl_a_vld_inst__DOT__sr_gen__BRA__1__KET____DOT__sr_inst__DOT__clk;
        CData/*0:0*/ sa_credit_top__DOT__sa_top_inst__DOT__dl_a_vld_inst__DOT__sr_gen__BRA__1__KET____DOT__sr_inst__DOT__rst_n;
        CData/*0:0*/ sa_credit_top__DOT__sa_top_inst__DOT__dl_a_vld_inst__DOT__sr_gen__BRA__1__KET____DOT__sr_inst__DOT__i_data;
        CData/*0:0*/ sa_credit_top__DOT__sa_top_inst__DOT__dl_a_vld_inst__DOT__sr_gen__BRA__1__KET____DOT__sr_inst__DOT__o_data;
        CData/*0:0*/ sa_credit_top__DOT__sa_top_inst__DOT__dl_a_vld_inst__DOT__sr_gen__BRA__1__KET____DOT__sr_inst__DOT____Vlvbound_hefb97aa7__0;
        CData/*0:0*/ sa_credit_top__DOT__sa_top_inst__DOT__dl_a_vld_inst__DOT__sr_gen__BRA__1__KET____DOT__sr_inst__DOT____Vlvbound_h8300f980__0;
        CData/*0:0*/ sa_credit_top__DOT__sa_top_inst__DOT__dl_a_vld_inst__DOT__sr_gen__BRA__2__KET____DOT__sr_inst__DOT__clk;
        CData/*0:0*/ sa_credit_top__DOT__sa_top_inst__DOT__dl_a_vld_inst__DOT__sr_gen__BRA__2__KET____DOT__sr_inst__DOT__rst_n;
        CData/*0:0*/ sa_credit_top__DOT__sa_top_inst__DOT__dl_a_vld_inst__DOT__sr_gen__BRA__2__KET____DOT__sr_inst__DOT__i_data;
        CData/*0:0*/ sa_credit_top__DOT__sa_top_inst__DOT__dl_a_vld_inst__DOT__sr_gen__BRA__2__KET____DOT__sr_inst__DOT__o_data;
        CData/*0:0*/ sa_credit_top__DOT__sa_top_inst__DOT__dl_a_vld_inst__DOT__sr_gen__BRA__3__KET____DOT__sr_inst__DOT__clk;
        CData/*0:0*/ sa_credit_top__DOT__sa_top_inst__DOT__dl_a_vld_inst__DOT__sr_gen__BRA__3__KET____DOT__sr_inst__DOT__rst_n;
        CData/*0:0*/ sa_credit_top__DOT__sa_top_inst__DOT__dl_a_vld_inst__DOT__sr_gen__BRA__3__KET____DOT__sr_inst__DOT__i_data;
        CData/*0:0*/ sa_credit_top__DOT__sa_top_inst__DOT__dl_a_vld_inst__DOT__sr_gen__BRA__3__KET____DOT__sr_inst__DOT__o_data;
        CData/*0:0*/ sa_credit_top__DOT__sa_top_inst__DOT__dl_a_vld_inst__DOT__sr_gen__BRA__3__KET____DOT__sr_inst__DOT____Vlvbound_hed2f8500__0;
        CData/*0:0*/ sa_credit_top__DOT__sa_top_inst__DOT__dl_a_vld_inst__DOT__sr_gen__BRA__3__KET____DOT__sr_inst__DOT____Vlvbound_h99f6fe1b__0;
        CData/*0:0*/ sa_credit_top__DOT__sa_top_inst__DOT__dl_c_vld_top2core_inst__DOT__clk;
        CData/*0:0*/ sa_credit_top__DOT__sa_top_inst__DOT__dl_c_vld_top2core_inst__DOT__rst_n;
        CData/*3:0*/ sa_credit_top__DOT__sa_top_inst__DOT__dl_c_vld_top2core_inst__DOT__i_data;
        CData/*3:0*/ sa_credit_top__DOT__sa_top_inst__DOT__dl_c_vld_top2core_inst__DOT__o_data;
        CData/*0:0*/ sa_credit_top__DOT__sa_top_inst__DOT__dl_c_vld_top2core_inst__DOT__sr_gen__BRA__1__KET____DOT__sr_inst__DOT__clk;
        CData/*0:0*/ sa_credit_top__DOT__sa_top_inst__DOT__dl_c_vld_top2core_inst__DOT__sr_gen__BRA__1__KET____DOT__sr_inst__DOT__rst_n;
        CData/*0:0*/ sa_credit_top__DOT__sa_top_inst__DOT__dl_c_vld_top2core_inst__DOT__sr_gen__BRA__1__KET____DOT__sr_inst__DOT__i_data;
        CData/*0:0*/ sa_credit_top__DOT__sa_top_inst__DOT__dl_c_vld_top2core_inst__DOT__sr_gen__BRA__1__KET____DOT__sr_inst__DOT__o_data;
        CData/*0:0*/ sa_credit_top__DOT__sa_top_inst__DOT__dl_c_vld_top2core_inst__DOT__sr_gen__BRA__1__KET____DOT__sr_inst__DOT____Vlvbound_hefb97aa7__0;
        CData/*0:0*/ sa_credit_top__DOT__sa_top_inst__DOT__dl_c_vld_top2core_inst__DOT__sr_gen__BRA__1__KET____DOT__sr_inst__DOT____Vlvbound_h8300f980__0;
        CData/*0:0*/ sa_credit_top__DOT__sa_top_inst__DOT__dl_c_vld_top2core_inst__DOT__sr_gen__BRA__2__KET____DOT__sr_inst__DOT__clk;
        CData/*0:0*/ sa_credit_top__DOT__sa_top_inst__DOT__dl_c_vld_top2core_inst__DOT__sr_gen__BRA__2__KET____DOT__sr_inst__DOT__rst_n;
        CData/*0:0*/ sa_credit_top__DOT__sa_top_inst__DOT__dl_c_vld_top2core_inst__DOT__sr_gen__BRA__2__KET____DOT__sr_inst__DOT__i_data;
        CData/*0:0*/ sa_credit_top__DOT__sa_top_inst__DOT__dl_c_vld_top2core_inst__DOT__sr_gen__BRA__2__KET____DOT__sr_inst__DOT__o_data;
        CData/*0:0*/ sa_credit_top__DOT__sa_top_inst__DOT__dl_c_vld_top2core_inst__DOT__sr_gen__BRA__3__KET____DOT__sr_inst__DOT__clk;
        CData/*0:0*/ sa_credit_top__DOT__sa_top_inst__DOT__dl_c_vld_top2core_inst__DOT__sr_gen__BRA__3__KET____DOT__sr_inst__DOT__rst_n;
        CData/*0:0*/ sa_credit_top__DOT__sa_top_inst__DOT__dl_c_vld_top2core_inst__DOT__sr_gen__BRA__3__KET____DOT__sr_inst__DOT__i_data;
        CData/*0:0*/ sa_credit_top__DOT__sa_top_inst__DOT__dl_c_vld_top2core_inst__DOT__sr_gen__BRA__3__KET____DOT__sr_inst__DOT__o_data;
        CData/*0:0*/ sa_credit_top__DOT__sa_top_inst__DOT__dl_c_vld_top2core_inst__DOT__sr_gen__BRA__3__KET____DOT__sr_inst__DOT____Vlvbound_hed2f8500__0;
        CData/*0:0*/ sa_credit_top__DOT__sa_top_inst__DOT__dl_c_vld_top2core_inst__DOT__sr_gen__BRA__3__KET____DOT__sr_inst__DOT____Vlvbound_h99f6fe1b__0;
        CData/*0:0*/ sa_credit_top__DOT__sa_top_inst__DOT__dl_a_inst__DOT__clk;
        CData/*0:0*/ sa_credit_top__DOT__sa_top_inst__DOT__dl_a_inst__DOT__rst_n;
        CData/*0:0*/ sa_credit_top__DOT__sa_top_inst__DOT__dl_a_inst__DOT__sr_gen__BRA__1__KET____DOT__sr_inst__DOT__clk;
        CData/*0:0*/ sa_credit_top__DOT__sa_top_inst__DOT__dl_a_inst__DOT__sr_gen__BRA__1__KET____DOT__sr_inst__DOT__rst_n;
        CData/*0:0*/ sa_credit_top__DOT__sa_top_inst__DOT__dl_a_inst__DOT__sr_gen__BRA__2__KET____DOT__sr_inst__DOT__clk;
        CData/*0:0*/ sa_credit_top__DOT__sa_top_inst__DOT__dl_a_inst__DOT__sr_gen__BRA__2__KET____DOT__sr_inst__DOT__rst_n;
        CData/*0:0*/ sa_credit_top__DOT__sa_top_inst__DOT__dl_a_inst__DOT__sr_gen__BRA__3__KET____DOT__sr_inst__DOT__clk;
        CData/*0:0*/ sa_credit_top__DOT__sa_top_inst__DOT__dl_a_inst__DOT__sr_gen__BRA__3__KET____DOT__sr_inst__DOT__rst_n;
        CData/*0:0*/ sa_credit_top__DOT__sa_top_inst__DOT__dl_c_vld_core2top_inst__DOT__clk;
        CData/*0:0*/ sa_credit_top__DOT__sa_top_inst__DOT__dl_c_vld_core2top_inst__DOT__rst_n;
        CData/*3:0*/ sa_credit_top__DOT__sa_top_inst__DOT__dl_c_vld_core2top_inst__DOT__i_data;
        CData/*3:0*/ sa_credit_top__DOT__sa_top_inst__DOT__dl_c_vld_core2top_inst__DOT__o_data;
        CData/*0:0*/ sa_credit_top__DOT__sa_top_inst__DOT__dl_c_vld_core2top_inst__DOT__sr_gen__BRA__0__KET____DOT__sr_inst__DOT__clk;
        CData/*0:0*/ sa_credit_top__DOT__sa_top_inst__DOT__dl_c_vld_core2top_inst__DOT__sr_gen__BRA__0__KET____DOT__sr_inst__DOT__rst_n;
        CData/*0:0*/ sa_credit_top__DOT__sa_top_inst__DOT__dl_c_vld_core2top_inst__DOT__sr_gen__BRA__0__KET____DOT__sr_inst__DOT__i_data;
        CData/*0:0*/ sa_credit_top__DOT__sa_top_inst__DOT__dl_c_vld_core2top_inst__DOT__sr_gen__BRA__0__KET____DOT__sr_inst__DOT__o_data;
        CData/*0:0*/ sa_credit_top__DOT__sa_top_inst__DOT__dl_c_vld_core2top_inst__DOT__sr_gen__BRA__0__KET____DOT__sr_inst__DOT____Vlvbound_hed2f8500__0;
        CData/*0:0*/ sa_credit_top__DOT__sa_top_inst__DOT__dl_c_vld_core2top_inst__DOT__sr_gen__BRA__0__KET____DOT__sr_inst__DOT____Vlvbound_h99f6fe1b__0;
        CData/*0:0*/ sa_credit_top__DOT__sa_top_inst__DOT__dl_c_vld_core2top_inst__DOT__sr_gen__BRA__1__KET____DOT__sr_inst__DOT__clk;
        CData/*0:0*/ sa_credit_top__DOT__sa_top_inst__DOT__dl_c_vld_core2top_inst__DOT__sr_gen__BRA__1__KET____DOT__sr_inst__DOT__rst_n;
        CData/*0:0*/ sa_credit_top__DOT__sa_top_inst__DOT__dl_c_vld_core2top_inst__DOT__sr_gen__BRA__1__KET____DOT__sr_inst__DOT__i_data;
        CData/*0:0*/ sa_credit_top__DOT__sa_top_inst__DOT__dl_c_vld_core2top_inst__DOT__sr_gen__BRA__1__KET____DOT__sr_inst__DOT__o_data;
        CData/*0:0*/ sa_credit_top__DOT__sa_top_inst__DOT__dl_c_vld_core2top_inst__DOT__sr_gen__BRA__2__KET____DOT__sr_inst__DOT__clk;
        CData/*0:0*/ sa_credit_top__DOT__sa_top_inst__DOT__dl_c_vld_core2top_inst__DOT__sr_gen__BRA__2__KET____DOT__sr_inst__DOT__rst_n;
        CData/*0:0*/ sa_credit_top__DOT__sa_top_inst__DOT__dl_c_vld_core2top_inst__DOT__sr_gen__BRA__2__KET____DOT__sr_inst__DOT__i_data;
        CData/*0:0*/ sa_credit_top__DOT__sa_top_inst__DOT__dl_c_vld_core2top_inst__DOT__sr_gen__BRA__2__KET____DOT__sr_inst__DOT__o_data;
        CData/*0:0*/ sa_credit_top__DOT__sa_top_inst__DOT__dl_c_vld_core2top_inst__DOT__sr_gen__BRA__2__KET____DOT__sr_inst__DOT____Vlvbound_hefb97aa7__0;
    };
    struct {
        CData/*0:0*/ sa_credit_top__DOT__sa_top_inst__DOT__dl_c_vld_core2top_inst__DOT__sr_gen__BRA__2__KET____DOT__sr_inst__DOT____Vlvbound_h8300f980__0;
        CData/*0:0*/ sa_credit_top__DOT__sa_top_inst__DOT__dl_c_core2top_inst__DOT__clk;
        CData/*0:0*/ sa_credit_top__DOT__sa_top_inst__DOT__dl_c_core2top_inst__DOT__rst_n;
        CData/*0:0*/ sa_credit_top__DOT__sa_top_inst__DOT__dl_c_core2top_inst__DOT__sr_gen__BRA__0__KET____DOT__sr_inst__DOT__clk;
        CData/*0:0*/ sa_credit_top__DOT__sa_top_inst__DOT__dl_c_core2top_inst__DOT__sr_gen__BRA__0__KET____DOT__sr_inst__DOT__rst_n;
        CData/*0:0*/ sa_credit_top__DOT__sa_top_inst__DOT__dl_c_core2top_inst__DOT__sr_gen__BRA__1__KET____DOT__sr_inst__DOT__clk;
        CData/*0:0*/ sa_credit_top__DOT__sa_top_inst__DOT__dl_c_core2top_inst__DOT__sr_gen__BRA__1__KET____DOT__sr_inst__DOT__rst_n;
        CData/*0:0*/ sa_credit_top__DOT__sa_top_inst__DOT__dl_c_core2top_inst__DOT__sr_gen__BRA__2__KET____DOT__sr_inst__DOT__clk;
        CData/*0:0*/ sa_credit_top__DOT__sa_top_inst__DOT__dl_c_core2top_inst__DOT__sr_gen__BRA__2__KET____DOT__sr_inst__DOT__rst_n;
        CData/*0:0*/ sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__clk;
        CData/*0:0*/ sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__rst_n;
        CData/*3:0*/ sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__i_we_line;
        CData/*3:0*/ sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__i_a_vld_line;
        CData/*3:0*/ sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__i_c_vld_line;
        CData/*3:0*/ sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__o_c_vld_line;
        CData/*0:0*/ sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__0__KET____DOT__pe_inner__BRA__0__KET____DOT__pe_inst__DOT__clk;
        CData/*0:0*/ sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__0__KET____DOT__pe_inner__BRA__0__KET____DOT__pe_inst__DOT__rst_n;
        CData/*0:0*/ sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__0__KET____DOT__pe_inner__BRA__0__KET____DOT__pe_inst__DOT__i_we;
        CData/*0:0*/ sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__0__KET____DOT__pe_inner__BRA__0__KET____DOT__pe_inst__DOT__i_a_vld;
        CData/*0:0*/ sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__0__KET____DOT__pe_inner__BRA__0__KET____DOT__pe_inst__DOT__i_c_vld;
        CData/*0:0*/ sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__0__KET____DOT__pe_inner__BRA__0__KET____DOT__pe_inst__DOT__o_we;
        CData/*0:0*/ sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__0__KET____DOT__pe_inner__BRA__0__KET____DOT__pe_inst__DOT__o_a_vld;
        CData/*0:0*/ sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__0__KET____DOT__pe_inner__BRA__0__KET____DOT__pe_inst__DOT__o_c_vld;
        CData/*0:0*/ sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__0__KET____DOT__pe_inner__BRA__1__KET____DOT__pe_inst__DOT__clk;
        CData/*0:0*/ sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__0__KET____DOT__pe_inner__BRA__1__KET____DOT__pe_inst__DOT__rst_n;
        CData/*0:0*/ sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__0__KET____DOT__pe_inner__BRA__1__KET____DOT__pe_inst__DOT__i_we;
        CData/*0:0*/ sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__0__KET____DOT__pe_inner__BRA__1__KET____DOT__pe_inst__DOT__i_a_vld;
        CData/*0:0*/ sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__0__KET____DOT__pe_inner__BRA__1__KET____DOT__pe_inst__DOT__i_c_vld;
        CData/*0:0*/ sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__0__KET____DOT__pe_inner__BRA__1__KET____DOT__pe_inst__DOT__o_we;
        CData/*0:0*/ sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__0__KET____DOT__pe_inner__BRA__1__KET____DOT__pe_inst__DOT__o_a_vld;
        CData/*0:0*/ sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__0__KET____DOT__pe_inner__BRA__1__KET____DOT__pe_inst__DOT__o_c_vld;
        CData/*0:0*/ sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__0__KET____DOT__pe_inner__BRA__2__KET____DOT__pe_inst__DOT__clk;
        CData/*0:0*/ sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__0__KET____DOT__pe_inner__BRA__2__KET____DOT__pe_inst__DOT__rst_n;
        CData/*0:0*/ sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__0__KET____DOT__pe_inner__BRA__2__KET____DOT__pe_inst__DOT__i_we;
        CData/*0:0*/ sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__0__KET____DOT__pe_inner__BRA__2__KET____DOT__pe_inst__DOT__i_a_vld;
        CData/*0:0*/ sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__0__KET____DOT__pe_inner__BRA__2__KET____DOT__pe_inst__DOT__i_c_vld;
        CData/*0:0*/ sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__0__KET____DOT__pe_inner__BRA__2__KET____DOT__pe_inst__DOT__o_we;
        CData/*0:0*/ sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__0__KET____DOT__pe_inner__BRA__2__KET____DOT__pe_inst__DOT__o_a_vld;
        CData/*0:0*/ sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__0__KET____DOT__pe_inner__BRA__2__KET____DOT__pe_inst__DOT__o_c_vld;
        CData/*0:0*/ sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__0__KET____DOT__pe_inner__BRA__3__KET____DOT__pe_inst__DOT__clk;
        CData/*0:0*/ sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__0__KET____DOT__pe_inner__BRA__3__KET____DOT__pe_inst__DOT__rst_n;
        CData/*0:0*/ sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__0__KET____DOT__pe_inner__BRA__3__KET____DOT__pe_inst__DOT__i_we;
        CData/*0:0*/ sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__0__KET____DOT__pe_inner__BRA__3__KET____DOT__pe_inst__DOT__i_a_vld;
        CData/*0:0*/ sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__0__KET____DOT__pe_inner__BRA__3__KET____DOT__pe_inst__DOT__i_c_vld;
        CData/*0:0*/ sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__0__KET____DOT__pe_inner__BRA__3__KET____DOT__pe_inst__DOT__o_we;
        CData/*0:0*/ sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__0__KET____DOT__pe_inner__BRA__3__KET____DOT__pe_inst__DOT__o_a_vld;
        CData/*0:0*/ sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__0__KET____DOT__pe_inner__BRA__3__KET____DOT__pe_inst__DOT__o_c_vld;
        CData/*0:0*/ sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__1__KET____DOT__pe_inner__BRA__0__KET____DOT__pe_inst__DOT__clk;
        CData/*0:0*/ sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__1__KET____DOT__pe_inner__BRA__0__KET____DOT__pe_inst__DOT__rst_n;
        CData/*0:0*/ sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__1__KET____DOT__pe_inner__BRA__0__KET____DOT__pe_inst__DOT__i_we;
        CData/*0:0*/ sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__1__KET____DOT__pe_inner__BRA__0__KET____DOT__pe_inst__DOT__i_a_vld;
        CData/*0:0*/ sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__1__KET____DOT__pe_inner__BRA__0__KET____DOT__pe_inst__DOT__i_c_vld;
        CData/*0:0*/ sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__1__KET____DOT__pe_inner__BRA__0__KET____DOT__pe_inst__DOT__o_we;
        CData/*0:0*/ sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__1__KET____DOT__pe_inner__BRA__0__KET____DOT__pe_inst__DOT__o_a_vld;
        CData/*0:0*/ sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__1__KET____DOT__pe_inner__BRA__0__KET____DOT__pe_inst__DOT__o_c_vld;
        CData/*0:0*/ sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__1__KET____DOT__pe_inner__BRA__1__KET____DOT__pe_inst__DOT__clk;
        CData/*0:0*/ sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__1__KET____DOT__pe_inner__BRA__1__KET____DOT__pe_inst__DOT__rst_n;
        CData/*0:0*/ sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__1__KET____DOT__pe_inner__BRA__1__KET____DOT__pe_inst__DOT__i_we;
        CData/*0:0*/ sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__1__KET____DOT__pe_inner__BRA__1__KET____DOT__pe_inst__DOT__i_a_vld;
        CData/*0:0*/ sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__1__KET____DOT__pe_inner__BRA__1__KET____DOT__pe_inst__DOT__i_c_vld;
        CData/*0:0*/ sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__1__KET____DOT__pe_inner__BRA__1__KET____DOT__pe_inst__DOT__o_we;
        CData/*0:0*/ sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__1__KET____DOT__pe_inner__BRA__1__KET____DOT__pe_inst__DOT__o_a_vld;
        CData/*0:0*/ sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__1__KET____DOT__pe_inner__BRA__1__KET____DOT__pe_inst__DOT__o_c_vld;
        CData/*0:0*/ sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__1__KET____DOT__pe_inner__BRA__2__KET____DOT__pe_inst__DOT__clk;
    };
    struct {
        CData/*0:0*/ sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__1__KET____DOT__pe_inner__BRA__2__KET____DOT__pe_inst__DOT__rst_n;
        CData/*0:0*/ sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__1__KET____DOT__pe_inner__BRA__2__KET____DOT__pe_inst__DOT__i_we;
        CData/*0:0*/ sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__1__KET____DOT__pe_inner__BRA__2__KET____DOT__pe_inst__DOT__i_a_vld;
        CData/*0:0*/ sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__1__KET____DOT__pe_inner__BRA__2__KET____DOT__pe_inst__DOT__i_c_vld;
        CData/*0:0*/ sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__1__KET____DOT__pe_inner__BRA__2__KET____DOT__pe_inst__DOT__o_we;
        CData/*0:0*/ sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__1__KET____DOT__pe_inner__BRA__2__KET____DOT__pe_inst__DOT__o_a_vld;
        CData/*0:0*/ sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__1__KET____DOT__pe_inner__BRA__2__KET____DOT__pe_inst__DOT__o_c_vld;
        CData/*0:0*/ sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__1__KET____DOT__pe_inner__BRA__3__KET____DOT__pe_inst__DOT__clk;
        CData/*0:0*/ sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__1__KET____DOT__pe_inner__BRA__3__KET____DOT__pe_inst__DOT__rst_n;
        CData/*0:0*/ sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__1__KET____DOT__pe_inner__BRA__3__KET____DOT__pe_inst__DOT__i_we;
        CData/*0:0*/ sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__1__KET____DOT__pe_inner__BRA__3__KET____DOT__pe_inst__DOT__i_a_vld;
        CData/*0:0*/ sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__1__KET____DOT__pe_inner__BRA__3__KET____DOT__pe_inst__DOT__i_c_vld;
        CData/*0:0*/ sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__1__KET____DOT__pe_inner__BRA__3__KET____DOT__pe_inst__DOT__o_we;
        CData/*0:0*/ sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__1__KET____DOT__pe_inner__BRA__3__KET____DOT__pe_inst__DOT__o_a_vld;
        CData/*0:0*/ sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__1__KET____DOT__pe_inner__BRA__3__KET____DOT__pe_inst__DOT__o_c_vld;
        CData/*0:0*/ sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__2__KET____DOT__pe_inner__BRA__0__KET____DOT__pe_inst__DOT__clk;
        CData/*0:0*/ sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__2__KET____DOT__pe_inner__BRA__0__KET____DOT__pe_inst__DOT__rst_n;
        CData/*0:0*/ sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__2__KET____DOT__pe_inner__BRA__0__KET____DOT__pe_inst__DOT__i_we;
        CData/*0:0*/ sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__2__KET____DOT__pe_inner__BRA__0__KET____DOT__pe_inst__DOT__i_a_vld;
        CData/*0:0*/ sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__2__KET____DOT__pe_inner__BRA__0__KET____DOT__pe_inst__DOT__i_c_vld;
        CData/*0:0*/ sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__2__KET____DOT__pe_inner__BRA__0__KET____DOT__pe_inst__DOT__o_we;
        CData/*0:0*/ sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__2__KET____DOT__pe_inner__BRA__0__KET____DOT__pe_inst__DOT__o_a_vld;
        CData/*0:0*/ sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__2__KET____DOT__pe_inner__BRA__0__KET____DOT__pe_inst__DOT__o_c_vld;
        CData/*0:0*/ sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__2__KET____DOT__pe_inner__BRA__1__KET____DOT__pe_inst__DOT__clk;
        CData/*0:0*/ sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__2__KET____DOT__pe_inner__BRA__1__KET____DOT__pe_inst__DOT__rst_n;
        CData/*0:0*/ sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__2__KET____DOT__pe_inner__BRA__1__KET____DOT__pe_inst__DOT__i_we;
        CData/*0:0*/ sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__2__KET____DOT__pe_inner__BRA__1__KET____DOT__pe_inst__DOT__i_a_vld;
        CData/*0:0*/ sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__2__KET____DOT__pe_inner__BRA__1__KET____DOT__pe_inst__DOT__i_c_vld;
        CData/*0:0*/ sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__2__KET____DOT__pe_inner__BRA__1__KET____DOT__pe_inst__DOT__o_we;
        CData/*0:0*/ sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__2__KET____DOT__pe_inner__BRA__1__KET____DOT__pe_inst__DOT__o_a_vld;
        CData/*0:0*/ sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__2__KET____DOT__pe_inner__BRA__1__KET____DOT__pe_inst__DOT__o_c_vld;
        CData/*0:0*/ sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__2__KET____DOT__pe_inner__BRA__2__KET____DOT__pe_inst__DOT__clk;
        CData/*0:0*/ sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__2__KET____DOT__pe_inner__BRA__2__KET____DOT__pe_inst__DOT__rst_n;
        CData/*0:0*/ sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__2__KET____DOT__pe_inner__BRA__2__KET____DOT__pe_inst__DOT__i_we;
        CData/*0:0*/ sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__2__KET____DOT__pe_inner__BRA__2__KET____DOT__pe_inst__DOT__i_a_vld;
        CData/*0:0*/ sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__2__KET____DOT__pe_inner__BRA__2__KET____DOT__pe_inst__DOT__i_c_vld;
        CData/*0:0*/ sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__2__KET____DOT__pe_inner__BRA__2__KET____DOT__pe_inst__DOT__o_we;
        CData/*0:0*/ sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__2__KET____DOT__pe_inner__BRA__2__KET____DOT__pe_inst__DOT__o_a_vld;
        CData/*0:0*/ sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__2__KET____DOT__pe_inner__BRA__2__KET____DOT__pe_inst__DOT__o_c_vld;
        CData/*0:0*/ sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__2__KET____DOT__pe_inner__BRA__3__KET____DOT__pe_inst__DOT__clk;
        CData/*0:0*/ sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__2__KET____DOT__pe_inner__BRA__3__KET____DOT__pe_inst__DOT__rst_n;
        CData/*0:0*/ sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__2__KET____DOT__pe_inner__BRA__3__KET____DOT__pe_inst__DOT__i_we;
        CData/*0:0*/ sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__2__KET____DOT__pe_inner__BRA__3__KET____DOT__pe_inst__DOT__i_a_vld;
        CData/*0:0*/ sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__2__KET____DOT__pe_inner__BRA__3__KET____DOT__pe_inst__DOT__i_c_vld;
        CData/*0:0*/ sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__2__KET____DOT__pe_inner__BRA__3__KET____DOT__pe_inst__DOT__o_we;
        CData/*0:0*/ sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__2__KET____DOT__pe_inner__BRA__3__KET____DOT__pe_inst__DOT__o_a_vld;
        CData/*0:0*/ sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__2__KET____DOT__pe_inner__BRA__3__KET____DOT__pe_inst__DOT__o_c_vld;
        CData/*0:0*/ sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__3__KET____DOT__pe_inner__BRA__0__KET____DOT__pe_inst__DOT__clk;
        CData/*0:0*/ sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__3__KET____DOT__pe_inner__BRA__0__KET____DOT__pe_inst__DOT__rst_n;
        CData/*0:0*/ sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__3__KET____DOT__pe_inner__BRA__0__KET____DOT__pe_inst__DOT__i_we;
        CData/*0:0*/ sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__3__KET____DOT__pe_inner__BRA__0__KET____DOT__pe_inst__DOT__i_a_vld;
        CData/*0:0*/ sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__3__KET____DOT__pe_inner__BRA__0__KET____DOT__pe_inst__DOT__i_c_vld;
        CData/*0:0*/ sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__3__KET____DOT__pe_inner__BRA__0__KET____DOT__pe_inst__DOT__o_we;
        CData/*0:0*/ sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__3__KET____DOT__pe_inner__BRA__0__KET____DOT__pe_inst__DOT__o_a_vld;
        CData/*0:0*/ sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__3__KET____DOT__pe_inner__BRA__0__KET____DOT__pe_inst__DOT__o_c_vld;
        CData/*0:0*/ sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__3__KET____DOT__pe_inner__BRA__1__KET____DOT__pe_inst__DOT__clk;
        CData/*0:0*/ sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__3__KET____DOT__pe_inner__BRA__1__KET____DOT__pe_inst__DOT__rst_n;
        CData/*0:0*/ sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__3__KET____DOT__pe_inner__BRA__1__KET____DOT__pe_inst__DOT__i_we;
        CData/*0:0*/ sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__3__KET____DOT__pe_inner__BRA__1__KET____DOT__pe_inst__DOT__i_a_vld;
        CData/*0:0*/ sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__3__KET____DOT__pe_inner__BRA__1__KET____DOT__pe_inst__DOT__i_c_vld;
        CData/*0:0*/ sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__3__KET____DOT__pe_inner__BRA__1__KET____DOT__pe_inst__DOT__o_we;
        CData/*0:0*/ sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__3__KET____DOT__pe_inner__BRA__1__KET____DOT__pe_inst__DOT__o_a_vld;
        CData/*0:0*/ sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__3__KET____DOT__pe_inner__BRA__1__KET____DOT__pe_inst__DOT__o_c_vld;
        CData/*0:0*/ sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__3__KET____DOT__pe_inner__BRA__2__KET____DOT__pe_inst__DOT__clk;
    };
    struct {
        CData/*0:0*/ sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__3__KET____DOT__pe_inner__BRA__2__KET____DOT__pe_inst__DOT__rst_n;
        CData/*0:0*/ sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__3__KET____DOT__pe_inner__BRA__2__KET____DOT__pe_inst__DOT__i_we;
        CData/*0:0*/ sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__3__KET____DOT__pe_inner__BRA__2__KET____DOT__pe_inst__DOT__i_a_vld;
        CData/*0:0*/ sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__3__KET____DOT__pe_inner__BRA__2__KET____DOT__pe_inst__DOT__i_c_vld;
        CData/*0:0*/ sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__3__KET____DOT__pe_inner__BRA__2__KET____DOT__pe_inst__DOT__o_we;
        CData/*0:0*/ sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__3__KET____DOT__pe_inner__BRA__2__KET____DOT__pe_inst__DOT__o_a_vld;
        CData/*0:0*/ sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__3__KET____DOT__pe_inner__BRA__2__KET____DOT__pe_inst__DOT__o_c_vld;
        CData/*0:0*/ sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__3__KET____DOT__pe_inner__BRA__3__KET____DOT__pe_inst__DOT__clk;
        CData/*0:0*/ sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__3__KET____DOT__pe_inner__BRA__3__KET____DOT__pe_inst__DOT__rst_n;
        CData/*0:0*/ sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__3__KET____DOT__pe_inner__BRA__3__KET____DOT__pe_inst__DOT__i_we;
        CData/*0:0*/ sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__3__KET____DOT__pe_inner__BRA__3__KET____DOT__pe_inst__DOT__i_a_vld;
        CData/*0:0*/ sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__3__KET____DOT__pe_inner__BRA__3__KET____DOT__pe_inst__DOT__i_c_vld;
        CData/*0:0*/ sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__3__KET____DOT__pe_inner__BRA__3__KET____DOT__pe_inst__DOT__o_we;
        CData/*0:0*/ sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__3__KET____DOT__pe_inner__BRA__3__KET____DOT__pe_inst__DOT__o_a_vld;
        CData/*0:0*/ sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__3__KET____DOT__pe_inner__BRA__3__KET____DOT__pe_inst__DOT__o_c_vld;
        CData/*0:0*/ sa_credit_top__DOT__fifo_inst__DOT__clk;
        CData/*0:0*/ sa_credit_top__DOT__fifo_inst__DOT__rst_n;
        CData/*0:0*/ sa_credit_top__DOT__fifo_inst__DOT__i_wr_en;
        CData/*0:0*/ sa_credit_top__DOT__fifo_inst__DOT__i_rd_en;
        CData/*0:0*/ sa_credit_top__DOT__fifo_inst__DOT__o_full;
        CData/*0:0*/ sa_credit_top__DOT__fifo_inst__DOT__o_empty;
        CData/*2:0*/ sa_credit_top__DOT__fifo_inst__DOT__wr_ptr;
        CData/*2:0*/ sa_credit_top__DOT__fifo_inst__DOT__rd_ptr;
        CData/*3:0*/ sa_credit_top__DOT__fifo_inst__DOT__count;
        CData/*0:0*/ sa_credit_top__DOT__fifo_inst__DOT__wr_en;
        CData/*0:0*/ sa_credit_top__DOT__fifo_inst__DOT__rd_en;
        CData/*0:0*/ sa_credit_top__DOT__credit_inst__DOT__clk;
        CData/*0:0*/ sa_credit_top__DOT__credit_inst__DOT__rst_n;
        CData/*0:0*/ sa_credit_top__DOT__credit_inst__DOT__i_inc;
        CData/*0:0*/ sa_credit_top__DOT__credit_inst__DOT__i_vld;
        CData/*0:0*/ sa_credit_top__DOT__credit_inst__DOT__o_vld;
        CData/*0:0*/ sa_credit_top__DOT__credit_inst__DOT__o_rdy;
        CData/*3:0*/ sa_credit_top__DOT__credit_inst__DOT__count;
        CData/*0:0*/ __VstlFirstIteration;
        CData/*0:0*/ __VicoFirstIteration;
        CData/*0:0*/ __Vtrigprevexpr___TOP__sa_credit_top__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__sa_credit_top__DOT__rst_n__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__sa_credit_top__DOT__sa_top_inst__DOT__we_line_inst__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__sa_credit_top__DOT__sa_top_inst__DOT__we_line_inst__DOT__rst_n__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__sa_credit_top__DOT__sa_top_inst__DOT__we_line_inst__DOT__dl_inst__DOT__sr_gen__BRA__1__KET____DOT__sr_inst__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__sa_credit_top__DOT__sa_top_inst__DOT__we_line_inst__DOT__dl_inst__DOT__sr_gen__BRA__1__KET____DOT__sr_inst__DOT__rst_n__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__sa_credit_top__DOT__sa_top_inst__DOT__we_line_inst__DOT__dl_inst__DOT__sr_gen__BRA__2__KET____DOT__sr_inst__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__sa_credit_top__DOT__sa_top_inst__DOT__we_line_inst__DOT__dl_inst__DOT__sr_gen__BRA__2__KET____DOT__sr_inst__DOT__rst_n__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__sa_credit_top__DOT__sa_top_inst__DOT__we_line_inst__DOT__dl_inst__DOT__sr_gen__BRA__3__KET____DOT__sr_inst__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__sa_credit_top__DOT__sa_top_inst__DOT__we_line_inst__DOT__dl_inst__DOT__sr_gen__BRA__3__KET____DOT__sr_inst__DOT__rst_n__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__sa_credit_top__DOT__sa_top_inst__DOT__dl_a_vld_inst__DOT__sr_gen__BRA__1__KET____DOT__sr_inst__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__sa_credit_top__DOT__sa_top_inst__DOT__dl_a_vld_inst__DOT__sr_gen__BRA__1__KET____DOT__sr_inst__DOT__rst_n__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__sa_credit_top__DOT__sa_top_inst__DOT__dl_a_vld_inst__DOT__sr_gen__BRA__2__KET____DOT__sr_inst__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__sa_credit_top__DOT__sa_top_inst__DOT__dl_a_vld_inst__DOT__sr_gen__BRA__2__KET____DOT__sr_inst__DOT__rst_n__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__sa_credit_top__DOT__sa_top_inst__DOT__dl_a_vld_inst__DOT__sr_gen__BRA__3__KET____DOT__sr_inst__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__sa_credit_top__DOT__sa_top_inst__DOT__dl_a_vld_inst__DOT__sr_gen__BRA__3__KET____DOT__sr_inst__DOT__rst_n__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__sa_credit_top__DOT__sa_top_inst__DOT__dl_c_vld_top2core_inst__DOT__sr_gen__BRA__1__KET____DOT__sr_inst__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__sa_credit_top__DOT__sa_top_inst__DOT__dl_c_vld_top2core_inst__DOT__sr_gen__BRA__1__KET____DOT__sr_inst__DOT__rst_n__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__sa_credit_top__DOT__sa_top_inst__DOT__dl_c_vld_top2core_inst__DOT__sr_gen__BRA__2__KET____DOT__sr_inst__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__sa_credit_top__DOT__sa_top_inst__DOT__dl_c_vld_top2core_inst__DOT__sr_gen__BRA__2__KET____DOT__sr_inst__DOT__rst_n__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__sa_credit_top__DOT__sa_top_inst__DOT__dl_c_vld_top2core_inst__DOT__sr_gen__BRA__3__KET____DOT__sr_inst__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__sa_credit_top__DOT__sa_top_inst__DOT__dl_c_vld_top2core_inst__DOT__sr_gen__BRA__3__KET____DOT__sr_inst__DOT__rst_n__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__sa_credit_top__DOT__sa_top_inst__DOT__dl_a_inst__DOT__sr_gen__BRA__1__KET____DOT__sr_inst__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__sa_credit_top__DOT__sa_top_inst__DOT__dl_a_inst__DOT__sr_gen__BRA__1__KET____DOT__sr_inst__DOT__rst_n__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__sa_credit_top__DOT__sa_top_inst__DOT__dl_a_inst__DOT__sr_gen__BRA__2__KET____DOT__sr_inst__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__sa_credit_top__DOT__sa_top_inst__DOT__dl_a_inst__DOT__sr_gen__BRA__2__KET____DOT__sr_inst__DOT__rst_n__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__sa_credit_top__DOT__sa_top_inst__DOT__dl_a_inst__DOT__sr_gen__BRA__3__KET____DOT__sr_inst__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__sa_credit_top__DOT__sa_top_inst__DOT__dl_a_inst__DOT__sr_gen__BRA__3__KET____DOT__sr_inst__DOT__rst_n__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__sa_credit_top__DOT__sa_top_inst__DOT__dl_c_vld_core2top_inst__DOT__sr_gen__BRA__0__KET____DOT__sr_inst__DOT__clk__0;
    };
    struct {
        CData/*0:0*/ __Vtrigprevexpr___TOP__sa_credit_top__DOT__sa_top_inst__DOT__dl_c_vld_core2top_inst__DOT__sr_gen__BRA__0__KET____DOT__sr_inst__DOT__rst_n__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__sa_credit_top__DOT__sa_top_inst__DOT__dl_c_vld_core2top_inst__DOT__sr_gen__BRA__1__KET____DOT__sr_inst__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__sa_credit_top__DOT__sa_top_inst__DOT__dl_c_vld_core2top_inst__DOT__sr_gen__BRA__1__KET____DOT__sr_inst__DOT__rst_n__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__sa_credit_top__DOT__sa_top_inst__DOT__dl_c_vld_core2top_inst__DOT__sr_gen__BRA__2__KET____DOT__sr_inst__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__sa_credit_top__DOT__sa_top_inst__DOT__dl_c_vld_core2top_inst__DOT__sr_gen__BRA__2__KET____DOT__sr_inst__DOT__rst_n__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__sa_credit_top__DOT__sa_top_inst__DOT__dl_c_core2top_inst__DOT__sr_gen__BRA__0__KET____DOT__sr_inst__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__sa_credit_top__DOT__sa_top_inst__DOT__dl_c_core2top_inst__DOT__sr_gen__BRA__0__KET____DOT__sr_inst__DOT__rst_n__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__sa_credit_top__DOT__sa_top_inst__DOT__dl_c_core2top_inst__DOT__sr_gen__BRA__1__KET____DOT__sr_inst__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__sa_credit_top__DOT__sa_top_inst__DOT__dl_c_core2top_inst__DOT__sr_gen__BRA__1__KET____DOT__sr_inst__DOT__rst_n__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__sa_credit_top__DOT__sa_top_inst__DOT__dl_c_core2top_inst__DOT__sr_gen__BRA__2__KET____DOT__sr_inst__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__sa_credit_top__DOT__sa_top_inst__DOT__dl_c_core2top_inst__DOT__sr_gen__BRA__2__KET____DOT__sr_inst__DOT__rst_n__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__0__KET____DOT__pe_inner__BRA__0__KET____DOT__pe_inst__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__0__KET____DOT__pe_inner__BRA__0__KET____DOT__pe_inst__DOT__rst_n__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__0__KET____DOT__pe_inner__BRA__1__KET____DOT__pe_inst__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__0__KET____DOT__pe_inner__BRA__1__KET____DOT__pe_inst__DOT__rst_n__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__0__KET____DOT__pe_inner__BRA__2__KET____DOT__pe_inst__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__0__KET____DOT__pe_inner__BRA__2__KET____DOT__pe_inst__DOT__rst_n__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__0__KET____DOT__pe_inner__BRA__3__KET____DOT__pe_inst__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__0__KET____DOT__pe_inner__BRA__3__KET____DOT__pe_inst__DOT__rst_n__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__1__KET____DOT__pe_inner__BRA__0__KET____DOT__pe_inst__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__1__KET____DOT__pe_inner__BRA__0__KET____DOT__pe_inst__DOT__rst_n__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__1__KET____DOT__pe_inner__BRA__1__KET____DOT__pe_inst__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__1__KET____DOT__pe_inner__BRA__1__KET____DOT__pe_inst__DOT__rst_n__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__1__KET____DOT__pe_inner__BRA__2__KET____DOT__pe_inst__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__1__KET____DOT__pe_inner__BRA__2__KET____DOT__pe_inst__DOT__rst_n__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__1__KET____DOT__pe_inner__BRA__3__KET____DOT__pe_inst__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__1__KET____DOT__pe_inner__BRA__3__KET____DOT__pe_inst__DOT__rst_n__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__2__KET____DOT__pe_inner__BRA__0__KET____DOT__pe_inst__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__2__KET____DOT__pe_inner__BRA__0__KET____DOT__pe_inst__DOT__rst_n__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__2__KET____DOT__pe_inner__BRA__1__KET____DOT__pe_inst__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__2__KET____DOT__pe_inner__BRA__1__KET____DOT__pe_inst__DOT__rst_n__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__2__KET____DOT__pe_inner__BRA__2__KET____DOT__pe_inst__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__2__KET____DOT__pe_inner__BRA__2__KET____DOT__pe_inst__DOT__rst_n__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__2__KET____DOT__pe_inner__BRA__3__KET____DOT__pe_inst__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__2__KET____DOT__pe_inner__BRA__3__KET____DOT__pe_inst__DOT__rst_n__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__3__KET____DOT__pe_inner__BRA__0__KET____DOT__pe_inst__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__3__KET____DOT__pe_inner__BRA__0__KET____DOT__pe_inst__DOT__rst_n__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__3__KET____DOT__pe_inner__BRA__1__KET____DOT__pe_inst__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__3__KET____DOT__pe_inner__BRA__1__KET____DOT__pe_inst__DOT__rst_n__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__3__KET____DOT__pe_inner__BRA__2__KET____DOT__pe_inst__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__3__KET____DOT__pe_inner__BRA__2__KET____DOT__pe_inst__DOT__rst_n__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__3__KET____DOT__pe_inner__BRA__3__KET____DOT__pe_inst__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__3__KET____DOT__pe_inner__BRA__3__KET____DOT__pe_inst__DOT__rst_n__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__sa_credit_top__DOT__fifo_inst__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__sa_credit_top__DOT__fifo_inst__DOT__rst_n__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__sa_credit_top__DOT__credit_inst__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__sa_credit_top__DOT__credit_inst__DOT__rst_n__0;
        VL_IN64(i_ab_line,63,0);
        VL_OUT64(o_c_line,63,0);
        QData/*63:0*/ sa_credit_top__DOT__i_ab_line;
        QData/*63:0*/ sa_credit_top__DOT__o_c_line;
        QData/*63:0*/ sa_credit_top__DOT__c_line_sa2fifo;
        QData/*63:0*/ sa_credit_top__DOT__sa_top_inst__DOT__i_a_line;
        QData/*63:0*/ sa_credit_top__DOT__sa_top_inst__DOT__o_c_line;
        QData/*63:0*/ sa_credit_top__DOT__sa_top_inst__DOT__a_line;
        QData/*63:0*/ sa_credit_top__DOT__sa_top_inst__DOT__c_line_core2top;
        QData/*63:0*/ sa_credit_top__DOT__sa_top_inst__DOT__dl_a_inst__DOT__i_data;
        QData/*63:0*/ sa_credit_top__DOT__sa_top_inst__DOT__dl_a_inst__DOT__o_data;
        SData/*15:0*/ sa_credit_top__DOT__sa_top_inst__DOT__dl_a_inst__DOT__sr_gen__BRA__1__KET____DOT__sr_inst__DOT__i_data;
        SData/*15:0*/ sa_credit_top__DOT__sa_top_inst__DOT__dl_a_inst__DOT__sr_gen__BRA__1__KET____DOT__sr_inst__DOT__o_data;
        SData/*15:0*/ sa_credit_top__DOT__sa_top_inst__DOT__dl_a_inst__DOT__sr_gen__BRA__1__KET____DOT__sr_inst__DOT____Vlvbound_h90f613b2__0;
        SData/*15:0*/ sa_credit_top__DOT__sa_top_inst__DOT__dl_a_inst__DOT__sr_gen__BRA__1__KET____DOT__sr_inst__DOT____Vlvbound_he8313a39__0;
        SData/*15:0*/ sa_credit_top__DOT__sa_top_inst__DOT__dl_a_inst__DOT__sr_gen__BRA__2__KET____DOT__sr_inst__DOT__i_data;
        SData/*15:0*/ sa_credit_top__DOT__sa_top_inst__DOT__dl_a_inst__DOT__sr_gen__BRA__2__KET____DOT__sr_inst__DOT__o_data;
    };
    struct {
        SData/*15:0*/ sa_credit_top__DOT__sa_top_inst__DOT__dl_a_inst__DOT__sr_gen__BRA__3__KET____DOT__sr_inst__DOT__i_data;
        SData/*15:0*/ sa_credit_top__DOT__sa_top_inst__DOT__dl_a_inst__DOT__sr_gen__BRA__3__KET____DOT__sr_inst__DOT__o_data;
        SData/*15:0*/ sa_credit_top__DOT__sa_top_inst__DOT__dl_a_inst__DOT__sr_gen__BRA__3__KET____DOT__sr_inst__DOT____Vlvbound_h07c77690__0;
        SData/*15:0*/ sa_credit_top__DOT__sa_top_inst__DOT__dl_a_inst__DOT__sr_gen__BRA__3__KET____DOT__sr_inst__DOT____Vlvbound_h70abe3ab__0;
        QData/*63:0*/ sa_credit_top__DOT__sa_top_inst__DOT__dl_c_core2top_inst__DOT__i_data;
        QData/*63:0*/ sa_credit_top__DOT__sa_top_inst__DOT__dl_c_core2top_inst__DOT__o_data;
        SData/*15:0*/ sa_credit_top__DOT__sa_top_inst__DOT__dl_c_core2top_inst__DOT__sr_gen__BRA__0__KET____DOT__sr_inst__DOT__i_data;
        SData/*15:0*/ sa_credit_top__DOT__sa_top_inst__DOT__dl_c_core2top_inst__DOT__sr_gen__BRA__0__KET____DOT__sr_inst__DOT__o_data;
        SData/*15:0*/ sa_credit_top__DOT__sa_top_inst__DOT__dl_c_core2top_inst__DOT__sr_gen__BRA__0__KET____DOT__sr_inst__DOT____Vlvbound_h07c77690__0;
        SData/*15:0*/ sa_credit_top__DOT__sa_top_inst__DOT__dl_c_core2top_inst__DOT__sr_gen__BRA__0__KET____DOT__sr_inst__DOT____Vlvbound_h70abe3ab__0;
        SData/*15:0*/ sa_credit_top__DOT__sa_top_inst__DOT__dl_c_core2top_inst__DOT__sr_gen__BRA__1__KET____DOT__sr_inst__DOT__i_data;
        SData/*15:0*/ sa_credit_top__DOT__sa_top_inst__DOT__dl_c_core2top_inst__DOT__sr_gen__BRA__1__KET____DOT__sr_inst__DOT__o_data;
        SData/*15:0*/ sa_credit_top__DOT__sa_top_inst__DOT__dl_c_core2top_inst__DOT__sr_gen__BRA__2__KET____DOT__sr_inst__DOT__i_data;
        SData/*15:0*/ sa_credit_top__DOT__sa_top_inst__DOT__dl_c_core2top_inst__DOT__sr_gen__BRA__2__KET____DOT__sr_inst__DOT__o_data;
        SData/*15:0*/ sa_credit_top__DOT__sa_top_inst__DOT__dl_c_core2top_inst__DOT__sr_gen__BRA__2__KET____DOT__sr_inst__DOT____Vlvbound_h90f613b2__0;
        SData/*15:0*/ sa_credit_top__DOT__sa_top_inst__DOT__dl_c_core2top_inst__DOT__sr_gen__BRA__2__KET____DOT__sr_inst__DOT____Vlvbound_he8313a39__0;
        QData/*63:0*/ sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__i_a_line;
        QData/*63:0*/ sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__o_c_line;
        SData/*15:0*/ sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__0__KET____DOT__pe_inner__BRA__0__KET____DOT__pe_inst__DOT__i_a;
        SData/*15:0*/ sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__0__KET____DOT__pe_inner__BRA__0__KET____DOT__pe_inst__DOT__i_c;
        SData/*15:0*/ sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__0__KET____DOT__pe_inner__BRA__0__KET____DOT__pe_inst__DOT__o_a;
        SData/*15:0*/ sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__0__KET____DOT__pe_inner__BRA__0__KET____DOT__pe_inst__DOT__o_c;
        SData/*15:0*/ sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__0__KET____DOT__pe_inner__BRA__0__KET____DOT__pe_inst__DOT__b;
        SData/*15:0*/ sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__0__KET____DOT__pe_inner__BRA__1__KET____DOT__pe_inst__DOT__i_a;
        SData/*15:0*/ sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__0__KET____DOT__pe_inner__BRA__1__KET____DOT__pe_inst__DOT__i_c;
        SData/*15:0*/ sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__0__KET____DOT__pe_inner__BRA__1__KET____DOT__pe_inst__DOT__o_a;
        SData/*15:0*/ sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__0__KET____DOT__pe_inner__BRA__1__KET____DOT__pe_inst__DOT__o_c;
        SData/*15:0*/ sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__0__KET____DOT__pe_inner__BRA__1__KET____DOT__pe_inst__DOT__b;
        SData/*15:0*/ sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__0__KET____DOT__pe_inner__BRA__2__KET____DOT__pe_inst__DOT__i_a;
        SData/*15:0*/ sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__0__KET____DOT__pe_inner__BRA__2__KET____DOT__pe_inst__DOT__i_c;
        SData/*15:0*/ sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__0__KET____DOT__pe_inner__BRA__2__KET____DOT__pe_inst__DOT__o_a;
        SData/*15:0*/ sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__0__KET____DOT__pe_inner__BRA__2__KET____DOT__pe_inst__DOT__o_c;
        SData/*15:0*/ sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__0__KET____DOT__pe_inner__BRA__2__KET____DOT__pe_inst__DOT__b;
        SData/*15:0*/ sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__0__KET____DOT__pe_inner__BRA__3__KET____DOT__pe_inst__DOT__i_a;
        SData/*15:0*/ sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__0__KET____DOT__pe_inner__BRA__3__KET____DOT__pe_inst__DOT__i_c;
        SData/*15:0*/ sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__0__KET____DOT__pe_inner__BRA__3__KET____DOT__pe_inst__DOT__o_a;
        SData/*15:0*/ sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__0__KET____DOT__pe_inner__BRA__3__KET____DOT__pe_inst__DOT__o_c;
        SData/*15:0*/ sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__0__KET____DOT__pe_inner__BRA__3__KET____DOT__pe_inst__DOT__b;
        SData/*15:0*/ sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__1__KET____DOT__pe_inner__BRA__0__KET____DOT__pe_inst__DOT__i_a;
        SData/*15:0*/ sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__1__KET____DOT__pe_inner__BRA__0__KET____DOT__pe_inst__DOT__i_c;
        SData/*15:0*/ sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__1__KET____DOT__pe_inner__BRA__0__KET____DOT__pe_inst__DOT__o_a;
        SData/*15:0*/ sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__1__KET____DOT__pe_inner__BRA__0__KET____DOT__pe_inst__DOT__o_c;
        SData/*15:0*/ sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__1__KET____DOT__pe_inner__BRA__0__KET____DOT__pe_inst__DOT__b;
        SData/*15:0*/ sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__1__KET____DOT__pe_inner__BRA__1__KET____DOT__pe_inst__DOT__i_a;
        SData/*15:0*/ sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__1__KET____DOT__pe_inner__BRA__1__KET____DOT__pe_inst__DOT__i_c;
        SData/*15:0*/ sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__1__KET____DOT__pe_inner__BRA__1__KET____DOT__pe_inst__DOT__o_a;
        SData/*15:0*/ sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__1__KET____DOT__pe_inner__BRA__1__KET____DOT__pe_inst__DOT__o_c;
        SData/*15:0*/ sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__1__KET____DOT__pe_inner__BRA__1__KET____DOT__pe_inst__DOT__b;
        SData/*15:0*/ sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__1__KET____DOT__pe_inner__BRA__2__KET____DOT__pe_inst__DOT__i_a;
        SData/*15:0*/ sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__1__KET____DOT__pe_inner__BRA__2__KET____DOT__pe_inst__DOT__i_c;
        SData/*15:0*/ sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__1__KET____DOT__pe_inner__BRA__2__KET____DOT__pe_inst__DOT__o_a;
        SData/*15:0*/ sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__1__KET____DOT__pe_inner__BRA__2__KET____DOT__pe_inst__DOT__o_c;
        SData/*15:0*/ sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__1__KET____DOT__pe_inner__BRA__2__KET____DOT__pe_inst__DOT__b;
        SData/*15:0*/ sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__1__KET____DOT__pe_inner__BRA__3__KET____DOT__pe_inst__DOT__i_a;
        SData/*15:0*/ sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__1__KET____DOT__pe_inner__BRA__3__KET____DOT__pe_inst__DOT__i_c;
        SData/*15:0*/ sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__1__KET____DOT__pe_inner__BRA__3__KET____DOT__pe_inst__DOT__o_a;
        SData/*15:0*/ sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__1__KET____DOT__pe_inner__BRA__3__KET____DOT__pe_inst__DOT__o_c;
        SData/*15:0*/ sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__1__KET____DOT__pe_inner__BRA__3__KET____DOT__pe_inst__DOT__b;
        SData/*15:0*/ sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__2__KET____DOT__pe_inner__BRA__0__KET____DOT__pe_inst__DOT__i_a;
        SData/*15:0*/ sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__2__KET____DOT__pe_inner__BRA__0__KET____DOT__pe_inst__DOT__i_c;
        SData/*15:0*/ sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__2__KET____DOT__pe_inner__BRA__0__KET____DOT__pe_inst__DOT__o_a;
        SData/*15:0*/ sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__2__KET____DOT__pe_inner__BRA__0__KET____DOT__pe_inst__DOT__o_c;
        SData/*15:0*/ sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__2__KET____DOT__pe_inner__BRA__0__KET____DOT__pe_inst__DOT__b;
        SData/*15:0*/ sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__2__KET____DOT__pe_inner__BRA__1__KET____DOT__pe_inst__DOT__i_a;
    };
    struct {
        SData/*15:0*/ sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__2__KET____DOT__pe_inner__BRA__1__KET____DOT__pe_inst__DOT__i_c;
        SData/*15:0*/ sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__2__KET____DOT__pe_inner__BRA__1__KET____DOT__pe_inst__DOT__o_a;
        SData/*15:0*/ sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__2__KET____DOT__pe_inner__BRA__1__KET____DOT__pe_inst__DOT__o_c;
        SData/*15:0*/ sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__2__KET____DOT__pe_inner__BRA__1__KET____DOT__pe_inst__DOT__b;
        SData/*15:0*/ sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__2__KET____DOT__pe_inner__BRA__2__KET____DOT__pe_inst__DOT__i_a;
        SData/*15:0*/ sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__2__KET____DOT__pe_inner__BRA__2__KET____DOT__pe_inst__DOT__i_c;
        SData/*15:0*/ sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__2__KET____DOT__pe_inner__BRA__2__KET____DOT__pe_inst__DOT__o_a;
        SData/*15:0*/ sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__2__KET____DOT__pe_inner__BRA__2__KET____DOT__pe_inst__DOT__o_c;
        SData/*15:0*/ sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__2__KET____DOT__pe_inner__BRA__2__KET____DOT__pe_inst__DOT__b;
        SData/*15:0*/ sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__2__KET____DOT__pe_inner__BRA__3__KET____DOT__pe_inst__DOT__i_a;
        SData/*15:0*/ sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__2__KET____DOT__pe_inner__BRA__3__KET____DOT__pe_inst__DOT__i_c;
        SData/*15:0*/ sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__2__KET____DOT__pe_inner__BRA__3__KET____DOT__pe_inst__DOT__o_a;
        SData/*15:0*/ sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__2__KET____DOT__pe_inner__BRA__3__KET____DOT__pe_inst__DOT__o_c;
        SData/*15:0*/ sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__2__KET____DOT__pe_inner__BRA__3__KET____DOT__pe_inst__DOT__b;
        SData/*15:0*/ sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__3__KET____DOT__pe_inner__BRA__0__KET____DOT__pe_inst__DOT__i_a;
        SData/*15:0*/ sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__3__KET____DOT__pe_inner__BRA__0__KET____DOT__pe_inst__DOT__i_c;
        SData/*15:0*/ sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__3__KET____DOT__pe_inner__BRA__0__KET____DOT__pe_inst__DOT__o_a;
        SData/*15:0*/ sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__3__KET____DOT__pe_inner__BRA__0__KET____DOT__pe_inst__DOT__o_c;
        SData/*15:0*/ sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__3__KET____DOT__pe_inner__BRA__0__KET____DOT__pe_inst__DOT__b;
        SData/*15:0*/ sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__3__KET____DOT__pe_inner__BRA__1__KET____DOT__pe_inst__DOT__i_a;
        SData/*15:0*/ sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__3__KET____DOT__pe_inner__BRA__1__KET____DOT__pe_inst__DOT__i_c;
        SData/*15:0*/ sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__3__KET____DOT__pe_inner__BRA__1__KET____DOT__pe_inst__DOT__o_a;
        SData/*15:0*/ sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__3__KET____DOT__pe_inner__BRA__1__KET____DOT__pe_inst__DOT__o_c;
        SData/*15:0*/ sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__3__KET____DOT__pe_inner__BRA__1__KET____DOT__pe_inst__DOT__b;
        SData/*15:0*/ sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__3__KET____DOT__pe_inner__BRA__2__KET____DOT__pe_inst__DOT__i_a;
        SData/*15:0*/ sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__3__KET____DOT__pe_inner__BRA__2__KET____DOT__pe_inst__DOT__i_c;
        SData/*15:0*/ sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__3__KET____DOT__pe_inner__BRA__2__KET____DOT__pe_inst__DOT__o_a;
        SData/*15:0*/ sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__3__KET____DOT__pe_inner__BRA__2__KET____DOT__pe_inst__DOT__o_c;
        SData/*15:0*/ sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__3__KET____DOT__pe_inner__BRA__2__KET____DOT__pe_inst__DOT__b;
        SData/*15:0*/ sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__3__KET____DOT__pe_inner__BRA__3__KET____DOT__pe_inst__DOT__i_a;
        SData/*15:0*/ sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__3__KET____DOT__pe_inner__BRA__3__KET____DOT__pe_inst__DOT__i_c;
        SData/*15:0*/ sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__3__KET____DOT__pe_inner__BRA__3__KET____DOT__pe_inst__DOT__o_a;
        SData/*15:0*/ sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__3__KET____DOT__pe_inner__BRA__3__KET____DOT__pe_inst__DOT__o_c;
        SData/*15:0*/ sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__3__KET____DOT__pe_inner__BRA__3__KET____DOT__pe_inst__DOT__b;
        IData/*31:0*/ sa_credit_top__DOT__sa_top_inst__DOT__we_line_inst__DOT__dl_inst__DOT__sr_gen__BRA__1__KET____DOT__sr_inst__DOT__unnamedblk2__DOT__i;
        IData/*31:0*/ sa_credit_top__DOT__sa_top_inst__DOT__we_line_inst__DOT__dl_inst__DOT__sr_gen__BRA__1__KET____DOT__sr_inst__DOT__unnamedblk1__DOT__i;
        IData/*31:0*/ sa_credit_top__DOT__sa_top_inst__DOT__we_line_inst__DOT__dl_inst__DOT__sr_gen__BRA__2__KET____DOT__sr_inst__DOT__unnamedblk2__DOT__i;
        IData/*31:0*/ sa_credit_top__DOT__sa_top_inst__DOT__we_line_inst__DOT__dl_inst__DOT__sr_gen__BRA__2__KET____DOT__sr_inst__DOT__unnamedblk1__DOT__i;
        IData/*31:0*/ sa_credit_top__DOT__sa_top_inst__DOT__we_line_inst__DOT__dl_inst__DOT__sr_gen__BRA__3__KET____DOT__sr_inst__DOT__unnamedblk2__DOT__i;
        IData/*31:0*/ sa_credit_top__DOT__sa_top_inst__DOT__we_line_inst__DOT__dl_inst__DOT__sr_gen__BRA__3__KET____DOT__sr_inst__DOT__unnamedblk1__DOT__i;
        IData/*31:0*/ sa_credit_top__DOT__sa_top_inst__DOT__dl_a_vld_inst__DOT__sr_gen__BRA__1__KET____DOT__sr_inst__DOT__unnamedblk2__DOT__i;
        IData/*31:0*/ sa_credit_top__DOT__sa_top_inst__DOT__dl_a_vld_inst__DOT__sr_gen__BRA__1__KET____DOT__sr_inst__DOT__unnamedblk1__DOT__i;
        IData/*31:0*/ sa_credit_top__DOT__sa_top_inst__DOT__dl_a_vld_inst__DOT__sr_gen__BRA__2__KET____DOT__sr_inst__DOT__unnamedblk2__DOT__i;
        IData/*31:0*/ sa_credit_top__DOT__sa_top_inst__DOT__dl_a_vld_inst__DOT__sr_gen__BRA__2__KET____DOT__sr_inst__DOT__unnamedblk1__DOT__i;
        IData/*31:0*/ sa_credit_top__DOT__sa_top_inst__DOT__dl_a_vld_inst__DOT__sr_gen__BRA__3__KET____DOT__sr_inst__DOT__unnamedblk2__DOT__i;
        IData/*31:0*/ sa_credit_top__DOT__sa_top_inst__DOT__dl_a_vld_inst__DOT__sr_gen__BRA__3__KET____DOT__sr_inst__DOT__unnamedblk1__DOT__i;
        IData/*31:0*/ sa_credit_top__DOT__sa_top_inst__DOT__dl_c_vld_top2core_inst__DOT__sr_gen__BRA__1__KET____DOT__sr_inst__DOT__unnamedblk2__DOT__i;
        IData/*31:0*/ sa_credit_top__DOT__sa_top_inst__DOT__dl_c_vld_top2core_inst__DOT__sr_gen__BRA__1__KET____DOT__sr_inst__DOT__unnamedblk1__DOT__i;
        IData/*31:0*/ sa_credit_top__DOT__sa_top_inst__DOT__dl_c_vld_top2core_inst__DOT__sr_gen__BRA__2__KET____DOT__sr_inst__DOT__unnamedblk2__DOT__i;
        IData/*31:0*/ sa_credit_top__DOT__sa_top_inst__DOT__dl_c_vld_top2core_inst__DOT__sr_gen__BRA__2__KET____DOT__sr_inst__DOT__unnamedblk1__DOT__i;
        IData/*31:0*/ sa_credit_top__DOT__sa_top_inst__DOT__dl_c_vld_top2core_inst__DOT__sr_gen__BRA__3__KET____DOT__sr_inst__DOT__unnamedblk2__DOT__i;
        IData/*31:0*/ sa_credit_top__DOT__sa_top_inst__DOT__dl_c_vld_top2core_inst__DOT__sr_gen__BRA__3__KET____DOT__sr_inst__DOT__unnamedblk1__DOT__i;
        IData/*31:0*/ sa_credit_top__DOT__sa_top_inst__DOT__dl_a_inst__DOT__sr_gen__BRA__1__KET____DOT__sr_inst__DOT__unnamedblk2__DOT__i;
        IData/*31:0*/ sa_credit_top__DOT__sa_top_inst__DOT__dl_a_inst__DOT__sr_gen__BRA__1__KET____DOT__sr_inst__DOT__unnamedblk1__DOT__i;
        IData/*31:0*/ sa_credit_top__DOT__sa_top_inst__DOT__dl_a_inst__DOT__sr_gen__BRA__2__KET____DOT__sr_inst__DOT__unnamedblk2__DOT__i;
        IData/*31:0*/ sa_credit_top__DOT__sa_top_inst__DOT__dl_a_inst__DOT__sr_gen__BRA__2__KET____DOT__sr_inst__DOT__unnamedblk1__DOT__i;
        IData/*31:0*/ sa_credit_top__DOT__sa_top_inst__DOT__dl_a_inst__DOT__sr_gen__BRA__3__KET____DOT__sr_inst__DOT__unnamedblk2__DOT__i;
        IData/*31:0*/ sa_credit_top__DOT__sa_top_inst__DOT__dl_a_inst__DOT__sr_gen__BRA__3__KET____DOT__sr_inst__DOT__unnamedblk1__DOT__i;
        IData/*31:0*/ sa_credit_top__DOT__sa_top_inst__DOT__dl_c_vld_core2top_inst__DOT__sr_gen__BRA__0__KET____DOT__sr_inst__DOT__unnamedblk2__DOT__i;
        IData/*31:0*/ sa_credit_top__DOT__sa_top_inst__DOT__dl_c_vld_core2top_inst__DOT__sr_gen__BRA__0__KET____DOT__sr_inst__DOT__unnamedblk1__DOT__i;
        IData/*31:0*/ sa_credit_top__DOT__sa_top_inst__DOT__dl_c_vld_core2top_inst__DOT__sr_gen__BRA__1__KET____DOT__sr_inst__DOT__unnamedblk2__DOT__i;
        IData/*31:0*/ sa_credit_top__DOT__sa_top_inst__DOT__dl_c_vld_core2top_inst__DOT__sr_gen__BRA__1__KET____DOT__sr_inst__DOT__unnamedblk1__DOT__i;
        IData/*31:0*/ sa_credit_top__DOT__sa_top_inst__DOT__dl_c_vld_core2top_inst__DOT__sr_gen__BRA__2__KET____DOT__sr_inst__DOT__unnamedblk2__DOT__i;
        IData/*31:0*/ sa_credit_top__DOT__sa_top_inst__DOT__dl_c_vld_core2top_inst__DOT__sr_gen__BRA__2__KET____DOT__sr_inst__DOT__unnamedblk1__DOT__i;
    };
    struct {
        IData/*31:0*/ sa_credit_top__DOT__sa_top_inst__DOT__dl_c_core2top_inst__DOT__sr_gen__BRA__0__KET____DOT__sr_inst__DOT__unnamedblk2__DOT__i;
        IData/*31:0*/ sa_credit_top__DOT__sa_top_inst__DOT__dl_c_core2top_inst__DOT__sr_gen__BRA__0__KET____DOT__sr_inst__DOT__unnamedblk1__DOT__i;
        IData/*31:0*/ sa_credit_top__DOT__sa_top_inst__DOT__dl_c_core2top_inst__DOT__sr_gen__BRA__1__KET____DOT__sr_inst__DOT__unnamedblk2__DOT__i;
        IData/*31:0*/ sa_credit_top__DOT__sa_top_inst__DOT__dl_c_core2top_inst__DOT__sr_gen__BRA__1__KET____DOT__sr_inst__DOT__unnamedblk1__DOT__i;
        IData/*31:0*/ sa_credit_top__DOT__sa_top_inst__DOT__dl_c_core2top_inst__DOT__sr_gen__BRA__2__KET____DOT__sr_inst__DOT__unnamedblk2__DOT__i;
        IData/*31:0*/ sa_credit_top__DOT__sa_top_inst__DOT__dl_c_core2top_inst__DOT__sr_gen__BRA__2__KET____DOT__sr_inst__DOT__unnamedblk1__DOT__i;
        IData/*31:0*/ __VactIterCount;
        QData/*63:0*/ sa_credit_top__DOT__fifo_inst__DOT__i_wr_data;
        QData/*63:0*/ sa_credit_top__DOT__fifo_inst__DOT__o_rd_data;
        VlUnpacked<CData/*0:0*/, 1> sa_credit_top__DOT__sa_top_inst__DOT__we_line_inst__DOT__dl_inst__DOT__sr_gen__BRA__1__KET____DOT__sr_inst__DOT__reg_data;
        VlUnpacked<CData/*0:0*/, 2> sa_credit_top__DOT__sa_top_inst__DOT__we_line_inst__DOT__dl_inst__DOT__sr_gen__BRA__2__KET____DOT__sr_inst__DOT__reg_data;
        VlUnpacked<CData/*0:0*/, 3> sa_credit_top__DOT__sa_top_inst__DOT__we_line_inst__DOT__dl_inst__DOT__sr_gen__BRA__3__KET____DOT__sr_inst__DOT__reg_data;
        VlUnpacked<CData/*0:0*/, 1> sa_credit_top__DOT__sa_top_inst__DOT__dl_a_vld_inst__DOT__sr_gen__BRA__1__KET____DOT__sr_inst__DOT__reg_data;
        VlUnpacked<CData/*0:0*/, 2> sa_credit_top__DOT__sa_top_inst__DOT__dl_a_vld_inst__DOT__sr_gen__BRA__2__KET____DOT__sr_inst__DOT__reg_data;
        VlUnpacked<CData/*0:0*/, 3> sa_credit_top__DOT__sa_top_inst__DOT__dl_a_vld_inst__DOT__sr_gen__BRA__3__KET____DOT__sr_inst__DOT__reg_data;
        VlUnpacked<CData/*0:0*/, 1> sa_credit_top__DOT__sa_top_inst__DOT__dl_c_vld_top2core_inst__DOT__sr_gen__BRA__1__KET____DOT__sr_inst__DOT__reg_data;
        VlUnpacked<CData/*0:0*/, 2> sa_credit_top__DOT__sa_top_inst__DOT__dl_c_vld_top2core_inst__DOT__sr_gen__BRA__2__KET____DOT__sr_inst__DOT__reg_data;
        VlUnpacked<CData/*0:0*/, 3> sa_credit_top__DOT__sa_top_inst__DOT__dl_c_vld_top2core_inst__DOT__sr_gen__BRA__3__KET____DOT__sr_inst__DOT__reg_data;
        VlUnpacked<SData/*15:0*/, 1> sa_credit_top__DOT__sa_top_inst__DOT__dl_a_inst__DOT__sr_gen__BRA__1__KET____DOT__sr_inst__DOT__reg_data;
        VlUnpacked<SData/*15:0*/, 2> sa_credit_top__DOT__sa_top_inst__DOT__dl_a_inst__DOT__sr_gen__BRA__2__KET____DOT__sr_inst__DOT__reg_data;
        VlUnpacked<SData/*15:0*/, 3> sa_credit_top__DOT__sa_top_inst__DOT__dl_a_inst__DOT__sr_gen__BRA__3__KET____DOT__sr_inst__DOT__reg_data;
        VlUnpacked<CData/*0:0*/, 3> sa_credit_top__DOT__sa_top_inst__DOT__dl_c_vld_core2top_inst__DOT__sr_gen__BRA__0__KET____DOT__sr_inst__DOT__reg_data;
        VlUnpacked<CData/*0:0*/, 2> sa_credit_top__DOT__sa_top_inst__DOT__dl_c_vld_core2top_inst__DOT__sr_gen__BRA__1__KET____DOT__sr_inst__DOT__reg_data;
        VlUnpacked<CData/*0:0*/, 1> sa_credit_top__DOT__sa_top_inst__DOT__dl_c_vld_core2top_inst__DOT__sr_gen__BRA__2__KET____DOT__sr_inst__DOT__reg_data;
        VlUnpacked<SData/*15:0*/, 3> sa_credit_top__DOT__sa_top_inst__DOT__dl_c_core2top_inst__DOT__sr_gen__BRA__0__KET____DOT__sr_inst__DOT__reg_data;
        VlUnpacked<SData/*15:0*/, 2> sa_credit_top__DOT__sa_top_inst__DOT__dl_c_core2top_inst__DOT__sr_gen__BRA__1__KET____DOT__sr_inst__DOT__reg_data;
        VlUnpacked<SData/*15:0*/, 1> sa_credit_top__DOT__sa_top_inst__DOT__dl_c_core2top_inst__DOT__sr_gen__BRA__2__KET____DOT__sr_inst__DOT__reg_data;
        VlUnpacked<VlUnpacked<CData/*0:0*/, 5>, 5> sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__we;
        VlUnpacked<VlUnpacked<CData/*0:0*/, 5>, 5> sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__a_vld;
        VlUnpacked<VlUnpacked<CData/*0:0*/, 5>, 5> sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__c_vld;
        VlUnpacked<VlUnpacked<SData/*15:0*/, 5>, 5> sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__a;
        VlUnpacked<VlUnpacked<SData/*15:0*/, 5>, 5> sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__c;
        VlUnpacked<QData/*63:0*/, 8> sa_credit_top__DOT__fifo_inst__DOT__fifo_mem;
        VlUnpacked<QData/*63:0*/, 1> __VstlTriggered;
        VlUnpacked<QData/*63:0*/, 1> __VicoTriggered;
        VlUnpacked<QData/*63:0*/, 2> __VactTriggered;
        VlUnpacked<QData/*63:0*/, 2> __VnbaTriggered;
    };
    VlNBACommitQueue<VlUnpacked<CData/*0:0*/, 1>, false, CData/*0:0*/, 1> __VdlyCommitQueuesa_credit_top__DOT__sa_top_inst__DOT__we_line_inst__DOT__dl_inst__DOT__sr_gen__BRA__1__KET____DOT__sr_inst__DOT__reg_data;
    VlNBACommitQueue<VlUnpacked<CData/*0:0*/, 2>, false, CData/*0:0*/, 1> __VdlyCommitQueuesa_credit_top__DOT__sa_top_inst__DOT__we_line_inst__DOT__dl_inst__DOT__sr_gen__BRA__2__KET____DOT__sr_inst__DOT__reg_data;
    VlNBACommitQueue<VlUnpacked<CData/*0:0*/, 3>, false, CData/*0:0*/, 1> __VdlyCommitQueuesa_credit_top__DOT__sa_top_inst__DOT__we_line_inst__DOT__dl_inst__DOT__sr_gen__BRA__3__KET____DOT__sr_inst__DOT__reg_data;
    VlNBACommitQueue<VlUnpacked<CData/*0:0*/, 1>, false, CData/*0:0*/, 1> __VdlyCommitQueuesa_credit_top__DOT__sa_top_inst__DOT__dl_a_vld_inst__DOT__sr_gen__BRA__1__KET____DOT__sr_inst__DOT__reg_data;
    VlNBACommitQueue<VlUnpacked<CData/*0:0*/, 2>, false, CData/*0:0*/, 1> __VdlyCommitQueuesa_credit_top__DOT__sa_top_inst__DOT__dl_a_vld_inst__DOT__sr_gen__BRA__2__KET____DOT__sr_inst__DOT__reg_data;
    VlNBACommitQueue<VlUnpacked<CData/*0:0*/, 3>, false, CData/*0:0*/, 1> __VdlyCommitQueuesa_credit_top__DOT__sa_top_inst__DOT__dl_a_vld_inst__DOT__sr_gen__BRA__3__KET____DOT__sr_inst__DOT__reg_data;
    VlNBACommitQueue<VlUnpacked<CData/*0:0*/, 1>, false, CData/*0:0*/, 1> __VdlyCommitQueuesa_credit_top__DOT__sa_top_inst__DOT__dl_c_vld_top2core_inst__DOT__sr_gen__BRA__1__KET____DOT__sr_inst__DOT__reg_data;
    VlNBACommitQueue<VlUnpacked<CData/*0:0*/, 2>, false, CData/*0:0*/, 1> __VdlyCommitQueuesa_credit_top__DOT__sa_top_inst__DOT__dl_c_vld_top2core_inst__DOT__sr_gen__BRA__2__KET____DOT__sr_inst__DOT__reg_data;
    VlNBACommitQueue<VlUnpacked<CData/*0:0*/, 3>, false, CData/*0:0*/, 1> __VdlyCommitQueuesa_credit_top__DOT__sa_top_inst__DOT__dl_c_vld_top2core_inst__DOT__sr_gen__BRA__3__KET____DOT__sr_inst__DOT__reg_data;
    VlNBACommitQueue<VlUnpacked<SData/*15:0*/, 1>, false, SData/*15:0*/, 1> __VdlyCommitQueuesa_credit_top__DOT__sa_top_inst__DOT__dl_a_inst__DOT__sr_gen__BRA__1__KET____DOT__sr_inst__DOT__reg_data;
    VlNBACommitQueue<VlUnpacked<SData/*15:0*/, 2>, false, SData/*15:0*/, 1> __VdlyCommitQueuesa_credit_top__DOT__sa_top_inst__DOT__dl_a_inst__DOT__sr_gen__BRA__2__KET____DOT__sr_inst__DOT__reg_data;
    VlNBACommitQueue<VlUnpacked<SData/*15:0*/, 3>, false, SData/*15:0*/, 1> __VdlyCommitQueuesa_credit_top__DOT__sa_top_inst__DOT__dl_a_inst__DOT__sr_gen__BRA__3__KET____DOT__sr_inst__DOT__reg_data;
    VlNBACommitQueue<VlUnpacked<CData/*0:0*/, 3>, false, CData/*0:0*/, 1> __VdlyCommitQueuesa_credit_top__DOT__sa_top_inst__DOT__dl_c_vld_core2top_inst__DOT__sr_gen__BRA__0__KET____DOT__sr_inst__DOT__reg_data;
    VlNBACommitQueue<VlUnpacked<CData/*0:0*/, 2>, false, CData/*0:0*/, 1> __VdlyCommitQueuesa_credit_top__DOT__sa_top_inst__DOT__dl_c_vld_core2top_inst__DOT__sr_gen__BRA__1__KET____DOT__sr_inst__DOT__reg_data;
    VlNBACommitQueue<VlUnpacked<CData/*0:0*/, 1>, false, CData/*0:0*/, 1> __VdlyCommitQueuesa_credit_top__DOT__sa_top_inst__DOT__dl_c_vld_core2top_inst__DOT__sr_gen__BRA__2__KET____DOT__sr_inst__DOT__reg_data;
    VlNBACommitQueue<VlUnpacked<SData/*15:0*/, 3>, false, SData/*15:0*/, 1> __VdlyCommitQueuesa_credit_top__DOT__sa_top_inst__DOT__dl_c_core2top_inst__DOT__sr_gen__BRA__0__KET____DOT__sr_inst__DOT__reg_data;
    VlNBACommitQueue<VlUnpacked<SData/*15:0*/, 2>, false, SData/*15:0*/, 1> __VdlyCommitQueuesa_credit_top__DOT__sa_top_inst__DOT__dl_c_core2top_inst__DOT__sr_gen__BRA__1__KET____DOT__sr_inst__DOT__reg_data;
    VlNBACommitQueue<VlUnpacked<SData/*15:0*/, 1>, false, SData/*15:0*/, 1> __VdlyCommitQueuesa_credit_top__DOT__sa_top_inst__DOT__dl_c_core2top_inst__DOT__sr_gen__BRA__2__KET____DOT__sr_inst__DOT__reg_data;

    // INTERNAL VARIABLES
    Vtop__Syms* const vlSymsp;

    // PARAMETERS
    static constexpr IData/*31:0*/ sa_credit_top__DOT__WIDTH = 0x00000010U;
    static constexpr IData/*31:0*/ sa_credit_top__DOT__SIZE = 4U;
    static constexpr IData/*31:0*/ sa_credit_top__DOT__DEPTH = 8U;
    static constexpr IData/*31:0*/ sa_credit_top__DOT__sa_top_inst__DOT__WIDTH = 0x00000010U;
    static constexpr IData/*31:0*/ sa_credit_top__DOT__sa_top_inst__DOT__SIZE = 4U;
    static constexpr IData/*31:0*/ sa_credit_top__DOT__sa_top_inst__DOT__we_line_inst__DOT__SIZE = 4U;
    static constexpr IData/*31:0*/ sa_credit_top__DOT__sa_top_inst__DOT__we_line_inst__DOT__dl_inst__DOT__WIDTH = 1U;
    static constexpr IData/*31:0*/ sa_credit_top__DOT__sa_top_inst__DOT__we_line_inst__DOT__dl_inst__DOT__SIZE = 4U;
    static constexpr IData/*31:0*/ sa_credit_top__DOT__sa_top_inst__DOT__we_line_inst__DOT__dl_inst__DOT__sr_gen__BRA__1__KET____DOT__sr_inst__DOT__WIDTH = 1U;
    static constexpr IData/*31:0*/ sa_credit_top__DOT__sa_top_inst__DOT__we_line_inst__DOT__dl_inst__DOT__sr_gen__BRA__1__KET____DOT__sr_inst__DOT__SIZE = 1U;
    static constexpr IData/*31:0*/ sa_credit_top__DOT__sa_top_inst__DOT__we_line_inst__DOT__dl_inst__DOT__sr_gen__BRA__2__KET____DOT__sr_inst__DOT__WIDTH = 1U;
    static constexpr IData/*31:0*/ sa_credit_top__DOT__sa_top_inst__DOT__we_line_inst__DOT__dl_inst__DOT__sr_gen__BRA__2__KET____DOT__sr_inst__DOT__SIZE = 2U;
    static constexpr IData/*31:0*/ sa_credit_top__DOT__sa_top_inst__DOT__we_line_inst__DOT__dl_inst__DOT__sr_gen__BRA__3__KET____DOT__sr_inst__DOT__WIDTH = 1U;
    static constexpr IData/*31:0*/ sa_credit_top__DOT__sa_top_inst__DOT__we_line_inst__DOT__dl_inst__DOT__sr_gen__BRA__3__KET____DOT__sr_inst__DOT__SIZE = 3U;
    static constexpr IData/*31:0*/ sa_credit_top__DOT__sa_top_inst__DOT__dl_a_vld_inst__DOT__WIDTH = 1U;
    static constexpr IData/*31:0*/ sa_credit_top__DOT__sa_top_inst__DOT__dl_a_vld_inst__DOT__SIZE = 4U;
    static constexpr IData/*31:0*/ sa_credit_top__DOT__sa_top_inst__DOT__dl_a_vld_inst__DOT__sr_gen__BRA__1__KET____DOT__sr_inst__DOT__WIDTH = 1U;
    static constexpr IData/*31:0*/ sa_credit_top__DOT__sa_top_inst__DOT__dl_a_vld_inst__DOT__sr_gen__BRA__1__KET____DOT__sr_inst__DOT__SIZE = 1U;
    static constexpr IData/*31:0*/ sa_credit_top__DOT__sa_top_inst__DOT__dl_a_vld_inst__DOT__sr_gen__BRA__2__KET____DOT__sr_inst__DOT__WIDTH = 1U;
    static constexpr IData/*31:0*/ sa_credit_top__DOT__sa_top_inst__DOT__dl_a_vld_inst__DOT__sr_gen__BRA__2__KET____DOT__sr_inst__DOT__SIZE = 2U;
    static constexpr IData/*31:0*/ sa_credit_top__DOT__sa_top_inst__DOT__dl_a_vld_inst__DOT__sr_gen__BRA__3__KET____DOT__sr_inst__DOT__WIDTH = 1U;
    static constexpr IData/*31:0*/ sa_credit_top__DOT__sa_top_inst__DOT__dl_a_vld_inst__DOT__sr_gen__BRA__3__KET____DOT__sr_inst__DOT__SIZE = 3U;
    static constexpr IData/*31:0*/ sa_credit_top__DOT__sa_top_inst__DOT__dl_c_vld_top2core_inst__DOT__WIDTH = 1U;
    static constexpr IData/*31:0*/ sa_credit_top__DOT__sa_top_inst__DOT__dl_c_vld_top2core_inst__DOT__SIZE = 4U;
    static constexpr IData/*31:0*/ sa_credit_top__DOT__sa_top_inst__DOT__dl_c_vld_top2core_inst__DOT__sr_gen__BRA__1__KET____DOT__sr_inst__DOT__WIDTH = 1U;
    static constexpr IData/*31:0*/ sa_credit_top__DOT__sa_top_inst__DOT__dl_c_vld_top2core_inst__DOT__sr_gen__BRA__1__KET____DOT__sr_inst__DOT__SIZE = 1U;
    static constexpr IData/*31:0*/ sa_credit_top__DOT__sa_top_inst__DOT__dl_c_vld_top2core_inst__DOT__sr_gen__BRA__2__KET____DOT__sr_inst__DOT__WIDTH = 1U;
    static constexpr IData/*31:0*/ sa_credit_top__DOT__sa_top_inst__DOT__dl_c_vld_top2core_inst__DOT__sr_gen__BRA__2__KET____DOT__sr_inst__DOT__SIZE = 2U;
    static constexpr IData/*31:0*/ sa_credit_top__DOT__sa_top_inst__DOT__dl_c_vld_top2core_inst__DOT__sr_gen__BRA__3__KET____DOT__sr_inst__DOT__WIDTH = 1U;
    static constexpr IData/*31:0*/ sa_credit_top__DOT__sa_top_inst__DOT__dl_c_vld_top2core_inst__DOT__sr_gen__BRA__3__KET____DOT__sr_inst__DOT__SIZE = 3U;
    static constexpr IData/*31:0*/ sa_credit_top__DOT__sa_top_inst__DOT__dl_a_inst__DOT__WIDTH = 0x00000010U;
    static constexpr IData/*31:0*/ sa_credit_top__DOT__sa_top_inst__DOT__dl_a_inst__DOT__SIZE = 4U;
    static constexpr IData/*31:0*/ sa_credit_top__DOT__sa_top_inst__DOT__dl_a_inst__DOT__sr_gen__BRA__1__KET____DOT__sr_inst__DOT__WIDTH = 0x00000010U;
    static constexpr IData/*31:0*/ sa_credit_top__DOT__sa_top_inst__DOT__dl_a_inst__DOT__sr_gen__BRA__1__KET____DOT__sr_inst__DOT__SIZE = 1U;
    static constexpr IData/*31:0*/ sa_credit_top__DOT__sa_top_inst__DOT__dl_a_inst__DOT__sr_gen__BRA__2__KET____DOT__sr_inst__DOT__WIDTH = 0x00000010U;
    static constexpr IData/*31:0*/ sa_credit_top__DOT__sa_top_inst__DOT__dl_a_inst__DOT__sr_gen__BRA__2__KET____DOT__sr_inst__DOT__SIZE = 2U;
    static constexpr IData/*31:0*/ sa_credit_top__DOT__sa_top_inst__DOT__dl_a_inst__DOT__sr_gen__BRA__3__KET____DOT__sr_inst__DOT__WIDTH = 0x00000010U;
    static constexpr IData/*31:0*/ sa_credit_top__DOT__sa_top_inst__DOT__dl_a_inst__DOT__sr_gen__BRA__3__KET____DOT__sr_inst__DOT__SIZE = 3U;
    static constexpr IData/*31:0*/ sa_credit_top__DOT__sa_top_inst__DOT__dl_c_vld_core2top_inst__DOT__WIDTH = 1U;
    static constexpr IData/*31:0*/ sa_credit_top__DOT__sa_top_inst__DOT__dl_c_vld_core2top_inst__DOT__SIZE = 4U;
    static constexpr IData/*31:0*/ sa_credit_top__DOT__sa_top_inst__DOT__dl_c_vld_core2top_inst__DOT__sr_gen__BRA__0__KET____DOT__sr_inst__DOT__WIDTH = 1U;
    static constexpr IData/*31:0*/ sa_credit_top__DOT__sa_top_inst__DOT__dl_c_vld_core2top_inst__DOT__sr_gen__BRA__0__KET____DOT__sr_inst__DOT__SIZE = 3U;
    static constexpr IData/*31:0*/ sa_credit_top__DOT__sa_top_inst__DOT__dl_c_vld_core2top_inst__DOT__sr_gen__BRA__1__KET____DOT__sr_inst__DOT__WIDTH = 1U;
    static constexpr IData/*31:0*/ sa_credit_top__DOT__sa_top_inst__DOT__dl_c_vld_core2top_inst__DOT__sr_gen__BRA__1__KET____DOT__sr_inst__DOT__SIZE = 2U;
    static constexpr IData/*31:0*/ sa_credit_top__DOT__sa_top_inst__DOT__dl_c_vld_core2top_inst__DOT__sr_gen__BRA__2__KET____DOT__sr_inst__DOT__WIDTH = 1U;
    static constexpr IData/*31:0*/ sa_credit_top__DOT__sa_top_inst__DOT__dl_c_vld_core2top_inst__DOT__sr_gen__BRA__2__KET____DOT__sr_inst__DOT__SIZE = 1U;
    static constexpr IData/*31:0*/ sa_credit_top__DOT__sa_top_inst__DOT__dl_c_core2top_inst__DOT__WIDTH = 0x00000010U;
    static constexpr IData/*31:0*/ sa_credit_top__DOT__sa_top_inst__DOT__dl_c_core2top_inst__DOT__SIZE = 4U;
    static constexpr IData/*31:0*/ sa_credit_top__DOT__sa_top_inst__DOT__dl_c_core2top_inst__DOT__sr_gen__BRA__0__KET____DOT__sr_inst__DOT__WIDTH = 0x00000010U;
    static constexpr IData/*31:0*/ sa_credit_top__DOT__sa_top_inst__DOT__dl_c_core2top_inst__DOT__sr_gen__BRA__0__KET____DOT__sr_inst__DOT__SIZE = 3U;
    static constexpr IData/*31:0*/ sa_credit_top__DOT__sa_top_inst__DOT__dl_c_core2top_inst__DOT__sr_gen__BRA__1__KET____DOT__sr_inst__DOT__WIDTH = 0x00000010U;
    static constexpr IData/*31:0*/ sa_credit_top__DOT__sa_top_inst__DOT__dl_c_core2top_inst__DOT__sr_gen__BRA__1__KET____DOT__sr_inst__DOT__SIZE = 2U;
    static constexpr IData/*31:0*/ sa_credit_top__DOT__sa_top_inst__DOT__dl_c_core2top_inst__DOT__sr_gen__BRA__2__KET____DOT__sr_inst__DOT__WIDTH = 0x00000010U;
    static constexpr IData/*31:0*/ sa_credit_top__DOT__sa_top_inst__DOT__dl_c_core2top_inst__DOT__sr_gen__BRA__2__KET____DOT__sr_inst__DOT__SIZE = 1U;
    static constexpr IData/*31:0*/ sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__WIDTH = 0x00000010U;
    static constexpr IData/*31:0*/ sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__SIZE = 4U;
    static constexpr IData/*31:0*/ sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__0__KET____DOT__pe_inner__BRA__0__KET____DOT__pe_inst__DOT__WIDTH = 0x00000010U;
    static constexpr IData/*31:0*/ sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__0__KET____DOT__pe_inner__BRA__1__KET____DOT__pe_inst__DOT__WIDTH = 0x00000010U;
    static constexpr IData/*31:0*/ sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__0__KET____DOT__pe_inner__BRA__2__KET____DOT__pe_inst__DOT__WIDTH = 0x00000010U;
    static constexpr IData/*31:0*/ sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__0__KET____DOT__pe_inner__BRA__3__KET____DOT__pe_inst__DOT__WIDTH = 0x00000010U;
    static constexpr IData/*31:0*/ sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__1__KET____DOT__pe_inner__BRA__0__KET____DOT__pe_inst__DOT__WIDTH = 0x00000010U;
    static constexpr IData/*31:0*/ sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__1__KET____DOT__pe_inner__BRA__1__KET____DOT__pe_inst__DOT__WIDTH = 0x00000010U;
    static constexpr IData/*31:0*/ sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__1__KET____DOT__pe_inner__BRA__2__KET____DOT__pe_inst__DOT__WIDTH = 0x00000010U;
    static constexpr IData/*31:0*/ sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__1__KET____DOT__pe_inner__BRA__3__KET____DOT__pe_inst__DOT__WIDTH = 0x00000010U;
    static constexpr IData/*31:0*/ sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__2__KET____DOT__pe_inner__BRA__0__KET____DOT__pe_inst__DOT__WIDTH = 0x00000010U;
    static constexpr IData/*31:0*/ sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__2__KET____DOT__pe_inner__BRA__1__KET____DOT__pe_inst__DOT__WIDTH = 0x00000010U;
    static constexpr IData/*31:0*/ sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__2__KET____DOT__pe_inner__BRA__2__KET____DOT__pe_inst__DOT__WIDTH = 0x00000010U;
    static constexpr IData/*31:0*/ sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__2__KET____DOT__pe_inner__BRA__3__KET____DOT__pe_inst__DOT__WIDTH = 0x00000010U;
    static constexpr IData/*31:0*/ sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__3__KET____DOT__pe_inner__BRA__0__KET____DOT__pe_inst__DOT__WIDTH = 0x00000010U;
    static constexpr IData/*31:0*/ sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__3__KET____DOT__pe_inner__BRA__1__KET____DOT__pe_inst__DOT__WIDTH = 0x00000010U;
    static constexpr IData/*31:0*/ sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__3__KET____DOT__pe_inner__BRA__2__KET____DOT__pe_inst__DOT__WIDTH = 0x00000010U;
    static constexpr IData/*31:0*/ sa_credit_top__DOT__sa_top_inst__DOT__sa_core_inst__DOT__pe_outer__BRA__3__KET____DOT__pe_inner__BRA__3__KET____DOT__pe_inst__DOT__WIDTH = 0x00000010U;
    static constexpr IData/*31:0*/ sa_credit_top__DOT__fifo_inst__DOT__DATA_WIDTH = 0x00000040U;
    static constexpr IData/*31:0*/ sa_credit_top__DOT__fifo_inst__DOT__DEPTH = 8U;
    static constexpr IData/*31:0*/ sa_credit_top__DOT__fifo_inst__DOT__ADDR_WIDTH = 3U;
    static constexpr IData/*31:0*/ sa_credit_top__DOT__credit_inst__DOT__DEPTH = 8U;

    // CONSTRUCTORS
    Vtop___024root(Vtop__Syms* symsp, const char* v__name);
    ~Vtop___024root();
    VL_UNCOPYABLE(Vtop___024root);

    // INTERNAL METHODS
    void __Vconfigure(bool first);
};


#endif  // guard
