// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Symbol table internal header
//
// Internal details; most calling programs do not need this header,
// unless using verilator public meta comments.

#ifndef VERILATED_VTOP__SYMS_H_
#define VERILATED_VTOP__SYMS_H_  // guard

#include "verilated.h"

// INCLUDE MODEL CLASS

#include "Vtop.h"

// INCLUDE MODULE CLASSES
#include "Vtop___024root.h"

// DPI TYPES for DPI Export callbacks (Internal use)

// SYMS CLASS (contains all model state)
class alignas(VL_CACHE_LINE_BYTES) Vtop__Syms final : public VerilatedSyms {
  public:
    // INTERNAL STATE
    Vtop* const __Vm_modelp;
    bool __Vm_activity = false;  ///< Used by trace routines to determine change occurred
    uint32_t __Vm_baseCode = 0;  ///< Used by trace routines when tracing multiple models
    VlDeleter __Vm_deleter;
    bool __Vm_didInit = false;

    // MODULE INSTANCE STATE
    Vtop___024root                 TOP;

    // SCOPE NAMES
    VerilatedScope __Vscope_TOP;
    VerilatedScope __Vscope_sa_credit_top;
    VerilatedScope __Vscope_sa_credit_top__credit_inst;
    VerilatedScope __Vscope_sa_credit_top__fifo_inst;
    VerilatedScope __Vscope_sa_credit_top__sa_top_inst;
    VerilatedScope __Vscope_sa_credit_top__sa_top_inst__dl_a_inst;
    VerilatedScope __Vscope_sa_credit_top__sa_top_inst__dl_a_inst__sr_gen__BRA__1__KET__;
    VerilatedScope __Vscope_sa_credit_top__sa_top_inst__dl_a_inst__sr_gen__BRA__1__KET____sr_inst;
    VerilatedScope __Vscope_sa_credit_top__sa_top_inst__dl_a_inst__sr_gen__BRA__1__KET____sr_inst__unnamedblk1;
    VerilatedScope __Vscope_sa_credit_top__sa_top_inst__dl_a_inst__sr_gen__BRA__1__KET____sr_inst__unnamedblk2;
    VerilatedScope __Vscope_sa_credit_top__sa_top_inst__dl_a_inst__sr_gen__BRA__2__KET__;
    VerilatedScope __Vscope_sa_credit_top__sa_top_inst__dl_a_inst__sr_gen__BRA__2__KET____sr_inst;
    VerilatedScope __Vscope_sa_credit_top__sa_top_inst__dl_a_inst__sr_gen__BRA__2__KET____sr_inst__unnamedblk1;
    VerilatedScope __Vscope_sa_credit_top__sa_top_inst__dl_a_inst__sr_gen__BRA__2__KET____sr_inst__unnamedblk2;
    VerilatedScope __Vscope_sa_credit_top__sa_top_inst__dl_a_inst__sr_gen__BRA__3__KET__;
    VerilatedScope __Vscope_sa_credit_top__sa_top_inst__dl_a_inst__sr_gen__BRA__3__KET____sr_inst;
    VerilatedScope __Vscope_sa_credit_top__sa_top_inst__dl_a_inst__sr_gen__BRA__3__KET____sr_inst__unnamedblk1;
    VerilatedScope __Vscope_sa_credit_top__sa_top_inst__dl_a_inst__sr_gen__BRA__3__KET____sr_inst__unnamedblk2;
    VerilatedScope __Vscope_sa_credit_top__sa_top_inst__dl_a_vld_inst;
    VerilatedScope __Vscope_sa_credit_top__sa_top_inst__dl_a_vld_inst__sr_gen__BRA__1__KET__;
    VerilatedScope __Vscope_sa_credit_top__sa_top_inst__dl_a_vld_inst__sr_gen__BRA__1__KET____sr_inst;
    VerilatedScope __Vscope_sa_credit_top__sa_top_inst__dl_a_vld_inst__sr_gen__BRA__1__KET____sr_inst__unnamedblk1;
    VerilatedScope __Vscope_sa_credit_top__sa_top_inst__dl_a_vld_inst__sr_gen__BRA__1__KET____sr_inst__unnamedblk2;
    VerilatedScope __Vscope_sa_credit_top__sa_top_inst__dl_a_vld_inst__sr_gen__BRA__2__KET__;
    VerilatedScope __Vscope_sa_credit_top__sa_top_inst__dl_a_vld_inst__sr_gen__BRA__2__KET____sr_inst;
    VerilatedScope __Vscope_sa_credit_top__sa_top_inst__dl_a_vld_inst__sr_gen__BRA__2__KET____sr_inst__unnamedblk1;
    VerilatedScope __Vscope_sa_credit_top__sa_top_inst__dl_a_vld_inst__sr_gen__BRA__2__KET____sr_inst__unnamedblk2;
    VerilatedScope __Vscope_sa_credit_top__sa_top_inst__dl_a_vld_inst__sr_gen__BRA__3__KET__;
    VerilatedScope __Vscope_sa_credit_top__sa_top_inst__dl_a_vld_inst__sr_gen__BRA__3__KET____sr_inst;
    VerilatedScope __Vscope_sa_credit_top__sa_top_inst__dl_a_vld_inst__sr_gen__BRA__3__KET____sr_inst__unnamedblk1;
    VerilatedScope __Vscope_sa_credit_top__sa_top_inst__dl_a_vld_inst__sr_gen__BRA__3__KET____sr_inst__unnamedblk2;
    VerilatedScope __Vscope_sa_credit_top__sa_top_inst__dl_c_core2top_inst;
    VerilatedScope __Vscope_sa_credit_top__sa_top_inst__dl_c_core2top_inst__sr_gen__BRA__0__KET__;
    VerilatedScope __Vscope_sa_credit_top__sa_top_inst__dl_c_core2top_inst__sr_gen__BRA__0__KET____sr_inst;
    VerilatedScope __Vscope_sa_credit_top__sa_top_inst__dl_c_core2top_inst__sr_gen__BRA__0__KET____sr_inst__unnamedblk1;
    VerilatedScope __Vscope_sa_credit_top__sa_top_inst__dl_c_core2top_inst__sr_gen__BRA__0__KET____sr_inst__unnamedblk2;
    VerilatedScope __Vscope_sa_credit_top__sa_top_inst__dl_c_core2top_inst__sr_gen__BRA__1__KET__;
    VerilatedScope __Vscope_sa_credit_top__sa_top_inst__dl_c_core2top_inst__sr_gen__BRA__1__KET____sr_inst;
    VerilatedScope __Vscope_sa_credit_top__sa_top_inst__dl_c_core2top_inst__sr_gen__BRA__1__KET____sr_inst__unnamedblk1;
    VerilatedScope __Vscope_sa_credit_top__sa_top_inst__dl_c_core2top_inst__sr_gen__BRA__1__KET____sr_inst__unnamedblk2;
    VerilatedScope __Vscope_sa_credit_top__sa_top_inst__dl_c_core2top_inst__sr_gen__BRA__2__KET__;
    VerilatedScope __Vscope_sa_credit_top__sa_top_inst__dl_c_core2top_inst__sr_gen__BRA__2__KET____sr_inst;
    VerilatedScope __Vscope_sa_credit_top__sa_top_inst__dl_c_core2top_inst__sr_gen__BRA__2__KET____sr_inst__unnamedblk1;
    VerilatedScope __Vscope_sa_credit_top__sa_top_inst__dl_c_core2top_inst__sr_gen__BRA__2__KET____sr_inst__unnamedblk2;
    VerilatedScope __Vscope_sa_credit_top__sa_top_inst__dl_c_vld_core2top_inst;
    VerilatedScope __Vscope_sa_credit_top__sa_top_inst__dl_c_vld_core2top_inst__sr_gen__BRA__0__KET__;
    VerilatedScope __Vscope_sa_credit_top__sa_top_inst__dl_c_vld_core2top_inst__sr_gen__BRA__0__KET____sr_inst;
    VerilatedScope __Vscope_sa_credit_top__sa_top_inst__dl_c_vld_core2top_inst__sr_gen__BRA__0__KET____sr_inst__unnamedblk1;
    VerilatedScope __Vscope_sa_credit_top__sa_top_inst__dl_c_vld_core2top_inst__sr_gen__BRA__0__KET____sr_inst__unnamedblk2;
    VerilatedScope __Vscope_sa_credit_top__sa_top_inst__dl_c_vld_core2top_inst__sr_gen__BRA__1__KET__;
    VerilatedScope __Vscope_sa_credit_top__sa_top_inst__dl_c_vld_core2top_inst__sr_gen__BRA__1__KET____sr_inst;
    VerilatedScope __Vscope_sa_credit_top__sa_top_inst__dl_c_vld_core2top_inst__sr_gen__BRA__1__KET____sr_inst__unnamedblk1;
    VerilatedScope __Vscope_sa_credit_top__sa_top_inst__dl_c_vld_core2top_inst__sr_gen__BRA__1__KET____sr_inst__unnamedblk2;
    VerilatedScope __Vscope_sa_credit_top__sa_top_inst__dl_c_vld_core2top_inst__sr_gen__BRA__2__KET__;
    VerilatedScope __Vscope_sa_credit_top__sa_top_inst__dl_c_vld_core2top_inst__sr_gen__BRA__2__KET____sr_inst;
    VerilatedScope __Vscope_sa_credit_top__sa_top_inst__dl_c_vld_core2top_inst__sr_gen__BRA__2__KET____sr_inst__unnamedblk1;
    VerilatedScope __Vscope_sa_credit_top__sa_top_inst__dl_c_vld_core2top_inst__sr_gen__BRA__2__KET____sr_inst__unnamedblk2;
    VerilatedScope __Vscope_sa_credit_top__sa_top_inst__dl_c_vld_top2core_inst;
    VerilatedScope __Vscope_sa_credit_top__sa_top_inst__dl_c_vld_top2core_inst__sr_gen__BRA__1__KET__;
    VerilatedScope __Vscope_sa_credit_top__sa_top_inst__dl_c_vld_top2core_inst__sr_gen__BRA__1__KET____sr_inst;
    VerilatedScope __Vscope_sa_credit_top__sa_top_inst__dl_c_vld_top2core_inst__sr_gen__BRA__1__KET____sr_inst__unnamedblk1;
    VerilatedScope __Vscope_sa_credit_top__sa_top_inst__dl_c_vld_top2core_inst__sr_gen__BRA__1__KET____sr_inst__unnamedblk2;
    VerilatedScope __Vscope_sa_credit_top__sa_top_inst__dl_c_vld_top2core_inst__sr_gen__BRA__2__KET__;
    VerilatedScope __Vscope_sa_credit_top__sa_top_inst__dl_c_vld_top2core_inst__sr_gen__BRA__2__KET____sr_inst;
    VerilatedScope __Vscope_sa_credit_top__sa_top_inst__dl_c_vld_top2core_inst__sr_gen__BRA__2__KET____sr_inst__unnamedblk1;
    VerilatedScope __Vscope_sa_credit_top__sa_top_inst__dl_c_vld_top2core_inst__sr_gen__BRA__2__KET____sr_inst__unnamedblk2;
    VerilatedScope __Vscope_sa_credit_top__sa_top_inst__dl_c_vld_top2core_inst__sr_gen__BRA__3__KET__;
    VerilatedScope __Vscope_sa_credit_top__sa_top_inst__dl_c_vld_top2core_inst__sr_gen__BRA__3__KET____sr_inst;
    VerilatedScope __Vscope_sa_credit_top__sa_top_inst__dl_c_vld_top2core_inst__sr_gen__BRA__3__KET____sr_inst__unnamedblk1;
    VerilatedScope __Vscope_sa_credit_top__sa_top_inst__dl_c_vld_top2core_inst__sr_gen__BRA__3__KET____sr_inst__unnamedblk2;
    VerilatedScope __Vscope_sa_credit_top__sa_top_inst__sa_core_inst;
    VerilatedScope __Vscope_sa_credit_top__sa_top_inst__sa_core_inst__pe_outer__BRA__0__KET__;
    VerilatedScope __Vscope_sa_credit_top__sa_top_inst__sa_core_inst__pe_outer__BRA__0__KET____pe_inner__BRA__0__KET__;
    VerilatedScope __Vscope_sa_credit_top__sa_top_inst__sa_core_inst__pe_outer__BRA__0__KET____pe_inner__BRA__0__KET____pe_inst;
    VerilatedScope __Vscope_sa_credit_top__sa_top_inst__sa_core_inst__pe_outer__BRA__0__KET____pe_inner__BRA__1__KET__;
    VerilatedScope __Vscope_sa_credit_top__sa_top_inst__sa_core_inst__pe_outer__BRA__0__KET____pe_inner__BRA__1__KET____pe_inst;
    VerilatedScope __Vscope_sa_credit_top__sa_top_inst__sa_core_inst__pe_outer__BRA__0__KET____pe_inner__BRA__2__KET__;
    VerilatedScope __Vscope_sa_credit_top__sa_top_inst__sa_core_inst__pe_outer__BRA__0__KET____pe_inner__BRA__2__KET____pe_inst;
    VerilatedScope __Vscope_sa_credit_top__sa_top_inst__sa_core_inst__pe_outer__BRA__0__KET____pe_inner__BRA__3__KET__;
    VerilatedScope __Vscope_sa_credit_top__sa_top_inst__sa_core_inst__pe_outer__BRA__0__KET____pe_inner__BRA__3__KET____pe_inst;
    VerilatedScope __Vscope_sa_credit_top__sa_top_inst__sa_core_inst__pe_outer__BRA__1__KET__;
    VerilatedScope __Vscope_sa_credit_top__sa_top_inst__sa_core_inst__pe_outer__BRA__1__KET____pe_inner__BRA__0__KET__;
    VerilatedScope __Vscope_sa_credit_top__sa_top_inst__sa_core_inst__pe_outer__BRA__1__KET____pe_inner__BRA__0__KET____pe_inst;
    VerilatedScope __Vscope_sa_credit_top__sa_top_inst__sa_core_inst__pe_outer__BRA__1__KET____pe_inner__BRA__1__KET__;
    VerilatedScope __Vscope_sa_credit_top__sa_top_inst__sa_core_inst__pe_outer__BRA__1__KET____pe_inner__BRA__1__KET____pe_inst;
    VerilatedScope __Vscope_sa_credit_top__sa_top_inst__sa_core_inst__pe_outer__BRA__1__KET____pe_inner__BRA__2__KET__;
    VerilatedScope __Vscope_sa_credit_top__sa_top_inst__sa_core_inst__pe_outer__BRA__1__KET____pe_inner__BRA__2__KET____pe_inst;
    VerilatedScope __Vscope_sa_credit_top__sa_top_inst__sa_core_inst__pe_outer__BRA__1__KET____pe_inner__BRA__3__KET__;
    VerilatedScope __Vscope_sa_credit_top__sa_top_inst__sa_core_inst__pe_outer__BRA__1__KET____pe_inner__BRA__3__KET____pe_inst;
    VerilatedScope __Vscope_sa_credit_top__sa_top_inst__sa_core_inst__pe_outer__BRA__2__KET__;
    VerilatedScope __Vscope_sa_credit_top__sa_top_inst__sa_core_inst__pe_outer__BRA__2__KET____pe_inner__BRA__0__KET__;
    VerilatedScope __Vscope_sa_credit_top__sa_top_inst__sa_core_inst__pe_outer__BRA__2__KET____pe_inner__BRA__0__KET____pe_inst;
    VerilatedScope __Vscope_sa_credit_top__sa_top_inst__sa_core_inst__pe_outer__BRA__2__KET____pe_inner__BRA__1__KET__;
    VerilatedScope __Vscope_sa_credit_top__sa_top_inst__sa_core_inst__pe_outer__BRA__2__KET____pe_inner__BRA__1__KET____pe_inst;
    VerilatedScope __Vscope_sa_credit_top__sa_top_inst__sa_core_inst__pe_outer__BRA__2__KET____pe_inner__BRA__2__KET__;
    VerilatedScope __Vscope_sa_credit_top__sa_top_inst__sa_core_inst__pe_outer__BRA__2__KET____pe_inner__BRA__2__KET____pe_inst;
    VerilatedScope __Vscope_sa_credit_top__sa_top_inst__sa_core_inst__pe_outer__BRA__2__KET____pe_inner__BRA__3__KET__;
    VerilatedScope __Vscope_sa_credit_top__sa_top_inst__sa_core_inst__pe_outer__BRA__2__KET____pe_inner__BRA__3__KET____pe_inst;
    VerilatedScope __Vscope_sa_credit_top__sa_top_inst__sa_core_inst__pe_outer__BRA__3__KET__;
    VerilatedScope __Vscope_sa_credit_top__sa_top_inst__sa_core_inst__pe_outer__BRA__3__KET____pe_inner__BRA__0__KET__;
    VerilatedScope __Vscope_sa_credit_top__sa_top_inst__sa_core_inst__pe_outer__BRA__3__KET____pe_inner__BRA__0__KET____pe_inst;
    VerilatedScope __Vscope_sa_credit_top__sa_top_inst__sa_core_inst__pe_outer__BRA__3__KET____pe_inner__BRA__1__KET__;
    VerilatedScope __Vscope_sa_credit_top__sa_top_inst__sa_core_inst__pe_outer__BRA__3__KET____pe_inner__BRA__1__KET____pe_inst;
    VerilatedScope __Vscope_sa_credit_top__sa_top_inst__sa_core_inst__pe_outer__BRA__3__KET____pe_inner__BRA__2__KET__;
    VerilatedScope __Vscope_sa_credit_top__sa_top_inst__sa_core_inst__pe_outer__BRA__3__KET____pe_inner__BRA__2__KET____pe_inst;
    VerilatedScope __Vscope_sa_credit_top__sa_top_inst__sa_core_inst__pe_outer__BRA__3__KET____pe_inner__BRA__3__KET__;
    VerilatedScope __Vscope_sa_credit_top__sa_top_inst__sa_core_inst__pe_outer__BRA__3__KET____pe_inner__BRA__3__KET____pe_inst;
    VerilatedScope __Vscope_sa_credit_top__sa_top_inst__we_line_inst;
    VerilatedScope __Vscope_sa_credit_top__sa_top_inst__we_line_inst__dl_inst;
    VerilatedScope __Vscope_sa_credit_top__sa_top_inst__we_line_inst__dl_inst__sr_gen__BRA__1__KET__;
    VerilatedScope __Vscope_sa_credit_top__sa_top_inst__we_line_inst__dl_inst__sr_gen__BRA__1__KET____sr_inst;
    VerilatedScope __Vscope_sa_credit_top__sa_top_inst__we_line_inst__dl_inst__sr_gen__BRA__1__KET____sr_inst__unnamedblk1;
    VerilatedScope __Vscope_sa_credit_top__sa_top_inst__we_line_inst__dl_inst__sr_gen__BRA__1__KET____sr_inst__unnamedblk2;
    VerilatedScope __Vscope_sa_credit_top__sa_top_inst__we_line_inst__dl_inst__sr_gen__BRA__2__KET__;
    VerilatedScope __Vscope_sa_credit_top__sa_top_inst__we_line_inst__dl_inst__sr_gen__BRA__2__KET____sr_inst;
    VerilatedScope __Vscope_sa_credit_top__sa_top_inst__we_line_inst__dl_inst__sr_gen__BRA__2__KET____sr_inst__unnamedblk1;
    VerilatedScope __Vscope_sa_credit_top__sa_top_inst__we_line_inst__dl_inst__sr_gen__BRA__2__KET____sr_inst__unnamedblk2;
    VerilatedScope __Vscope_sa_credit_top__sa_top_inst__we_line_inst__dl_inst__sr_gen__BRA__3__KET__;
    VerilatedScope __Vscope_sa_credit_top__sa_top_inst__we_line_inst__dl_inst__sr_gen__BRA__3__KET____sr_inst;
    VerilatedScope __Vscope_sa_credit_top__sa_top_inst__we_line_inst__dl_inst__sr_gen__BRA__3__KET____sr_inst__unnamedblk1;
    VerilatedScope __Vscope_sa_credit_top__sa_top_inst__we_line_inst__dl_inst__sr_gen__BRA__3__KET____sr_inst__unnamedblk2;

    // SCOPE HIERARCHY
    VerilatedHierarchy __Vhier;

    // CONSTRUCTORS
    Vtop__Syms(VerilatedContext* contextp, const char* namep, Vtop* modelp);
    ~Vtop__Syms();

    // METHODS
    const char* name() { return TOP.name(); }
};

#endif  // guard
